import Quadrature.Compiler.LTL.Syntax

/-!
# Actual LTL output for all ten applications

Generated by `scripts/import-ltl.py` from the pinned configured compiler.
All 73 globals, CFG nodes, machine registers and stack slots, and constant bits are retained.
A separate Rocq certificate checks exact syntax against `Allocation.transf_program`;
the rendering and a cross-kernel semantics interpretation remain unproved.
-/

namespace Quadrature.LTL.Imported

open CC

def global0 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 21435762804951289275389675485319102),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_va_int32"
          (mksignature
            [.Xptr]
            .Xint
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global1 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 22100011719470881481773947964936126),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_va_int64"
          (mksignature
            [.Xptr]
            .Xlong
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global2 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 90521582509840790022117316103474565054),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_va_float64"
          (mksignature
            [.Xptr]
            .Xfloat
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global3 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 427163956635663619511819329762952789151678),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_va_composite"
          (mksignature
            [.Xptr, .Xlong]
            .Xptr
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global4 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 29979716304623666515338210580680638),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_i64_dtos"
          (mksignature
            [.Xfloat]
            .Xlong
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global5 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 30628753411940519968904522621833150),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_i64_dtou"
          (mksignature
            [.Xfloat]
            .Xlong
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global6 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 25111956568847854894294993758900158),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_i64_stod"
          (mksignature
            [.Xlong]
            .Xfloat
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global7 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 25111959044727933465055543557148606),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_i64_utod"
          (mksignature
            [.Xlong]
            .Xfloat
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global8 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 25760993676164708347861305800052670),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_i64_stof"
          (mksignature
            [.Xlong]
            .Xsingle
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global9 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 25760996152044786918621855598301118),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_i64_utof"
          (mksignature
            [.Xlong]
            .Xsingle
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global10 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 30921599269693830241354384549138366),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_i64_sdiv"
          (mksignature
            [.Xlong, .Xlong]
            .Xlong
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global11 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 30921601745573908812114934347386814),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_i64_udiv"
          (mksignature
            [.Xlong, .Xlong]
            .Xlong
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global12 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 25111401971710255043931838951247806),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_i64_smod"
          (mksignature
            [.Xlong, .Xlong]
            .Xlong
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global13 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 25111404447590333614692388749496254),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_i64_umod"
          (mksignature
            [.Xlong, .Xlong]
            .Xlong
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global14 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 432383945654513733906053229236158),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_i64_shl"
          (mksignature
            [.Xlong, .Xint]
            .Xlong
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global15 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 462807560059991239541974106165182),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_i64_shr"
          (mksignature
            [.Xlong, .Xint]
            .Xlong
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global16 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 462252962922391389178819298512830),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_i64_sar"
          (mksignature
            [.Xlong, .Xint]
            .Xlong
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global17 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 1689272968746527987493591833343217598),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_i64_smulh"
          (mksignature
            [.Xlong, .Xlong]
            .Xlong
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global18 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 1689272971222408066064352383141466046),
    (.Gfun
      (.External
        (.EF_runtime
          "__compcert_i64_umulh"
          (mksignature
            [.Xlong, .Xlong]
            .Xlong
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global19 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 311562378882557268053950),
    (.Gvar
      {
        gvar_info := (),
        gvar_init :=
          [
            (.Init_int8 (Integers.Int.repr 37)),
            (.Init_int8 (Integers.Int.repr 100)),
            (.Init_int8 (Integers.Int.repr 32)),
            (.Init_int8 (Integers.Int.repr 113)),
            (.Init_int8 (Integers.Int.repr 117)),
            (.Init_int8 (Integers.Int.repr 97)),
            (.Init_int8 (Integers.Int.repr 100)),
            (.Init_int8 (Integers.Int.repr 114)),
            (.Init_int8 (Integers.Int.repr 97)),
            (.Init_int8 (Integers.Int.repr 116)),
            (.Init_int8 (Integers.Int.repr 117)),
            (.Init_int8 (Integers.Int.repr 114)),
            (.Init_int8 (Integers.Int.repr 101)),
            (.Init_int8 (Integers.Int.repr 32)),
            (.Init_int8 (Integers.Int.repr 112)),
            (.Init_int8 (Integers.Int.repr 111)),
            (.Init_int8 (Integers.Int.repr 105)),
            (.Init_int8 (Integers.Int.repr 110)),
            (.Init_int8 (Integers.Int.repr 116)),
            (.Init_int8 (Integers.Int.repr 115)),
            (.Init_int8 (Integers.Int.repr 32)),
            (.Init_int8 (Integers.Int.repr 117)),
            (.Init_int8 (Integers.Int.repr 110)),
            (.Init_int8 (Integers.Int.repr 115)),
            (.Init_int8 (Integers.Int.repr 117)),
            (.Init_int8 (Integers.Int.repr 112)),
            (.Init_int8 (Integers.Int.repr 112)),
            (.Init_int8 (Integers.Int.repr 111)),
            (.Init_int8 (Integers.Int.repr 114)),
            (.Init_int8 (Integers.Int.repr 116)),
            (.Init_int8 (Integers.Int.repr 101)),
            (.Init_int8 (Integers.Int.repr 100)),
            (.Init_int8 (Integers.Int.repr 32)),
            (.Init_int8 (Integers.Int.repr 98)),
            (.Init_int8 (Integers.Int.repr 121)),
            (.Init_int8 (Integers.Int.repr 32)),
            (.Init_int8 (Integers.Int.repr 114)),
            (.Init_int8 (Integers.Int.repr 117)),
            (.Init_int8 (Integers.Int.repr 108)),
            (.Init_int8 (Integers.Int.repr 101)),
            (.Init_int8 (Integers.Int.repr 10)),
            (.Init_int8 (Integers.Int.repr 0))],
        gvar_readonly := true,
        gvar_volatile := false }))

def global20 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 316284745365426913267646),
    (.Gvar
      {
        gvar_info := (),
        gvar_init :=
          [
            (.Init_int8 (Integers.Int.repr 81)),
            (.Init_int8 (Integers.Int.repr 117)),
            (.Init_int8 (Integers.Int.repr 97)),
            (.Init_int8 (Integers.Int.repr 100)),
            (.Init_int8 (Integers.Int.repr 114)),
            (.Init_int8 (Integers.Int.repr 97)),
            (.Init_int8 (Integers.Int.repr 116)),
            (.Init_int8 (Integers.Int.repr 117)),
            (.Init_int8 (Integers.Int.repr 114)),
            (.Init_int8 (Integers.Int.repr 101)),
            (.Init_int8 (Integers.Int.repr 32)),
            (.Init_int8 (Integers.Int.repr 110)),
            (.Init_int8 (Integers.Int.repr 111)),
            (.Init_int8 (Integers.Int.repr 100)),
            (.Init_int8 (Integers.Int.repr 101)),
            (.Init_int8 (Integers.Int.repr 32)),
            (.Init_int8 (Integers.Int.repr 105)),
            (.Init_int8 (Integers.Int.repr 110)),
            (.Init_int8 (Integers.Int.repr 100)),
            (.Init_int8 (Integers.Int.repr 101)),
            (.Init_int8 (Integers.Int.repr 120)),
            (.Init_int8 (Integers.Int.repr 32)),
            (.Init_int8 (Integers.Int.repr 111)),
            (.Init_int8 (Integers.Int.repr 117)),
            (.Init_int8 (Integers.Int.repr 116)),
            (.Init_int8 (Integers.Int.repr 32)),
            (.Init_int8 (Integers.Int.repr 111)),
            (.Init_int8 (Integers.Int.repr 102)),
            (.Init_int8 (Integers.Int.repr 32)),
            (.Init_int8 (Integers.Int.repr 98)),
            (.Init_int8 (Integers.Int.repr 111)),
            (.Init_int8 (Integers.Int.repr 117)),
            (.Init_int8 (Integers.Int.repr 110)),
            (.Init_int8 (Integers.Int.repr 100)),
            (.Init_int8 (Integers.Int.repr 115)),
            (.Init_int8 (Integers.Int.repr 10)),
            (.Init_int8 (Integers.Int.repr 0))],
        gvar_readonly := true,
        gvar_volatile := false }))

def global21 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 5395429437043650498700607274942),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_bswap64"
          (mksignature
            [.Xlong]
            .Xlong
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global22 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 1724685877248640965123030974),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_bswap"
          (mksignature
            [.Xint]
            .Xint
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global23 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 5233259291897265682688822001598),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_bswap32"
          (mksignature
            [.Xint]
            .Xint
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global24 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 5547696061875752272513199554494),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_bswap16"
          (mksignature
            [.Xint16unsigned]
            .Xint16unsigned
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global25 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 469078766812154373390270),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_clz"
          (mksignature
            [.Xint]
            .Xint
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global26 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 25856520978719367042219966),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_clzl"
          (mksignature
            [.Xlong]
            .Xint
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global27 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 1650652822540780977847320510),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_clzll"
          (mksignature
            [.Xlong]
            .Xint
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global28 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 469669062622513079041982),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_ctz"
          (mksignature
            [.Xint]
            .Xint
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global29 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 25857111274529725747871678),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_ctzl"
          (mksignature
            [.Xlong]
            .Xint
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global30 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 1650653412836591336552972222),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_ctzll"
          (mksignature
            [.Xlong]
            .Xint
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global31 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 27857996169481367213096894),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_fabs"
          (mksignature
            [.Xfloat]
            .Xfloat
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global32 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 1536597419048538577246404542),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_fabsf"
          (mksignature
            [.Xsingle]
            .Xsingle
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global33 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 1807166734850128206852833214),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_fsqrt"
          (mksignature
            [.Xfloat]
            .Xfloat
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global34 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 28236981067711216130506686),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_sqrt"
          (mksignature
            [.Xfloat]
            .Xfloat
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global35 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 26908785589146098326477794481020231027834814),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_memcpy_aligned"
          (mksignature
            [.Xptr, .Xptr, .Xlong, .Xlong]
            .Xvoid
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global36 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 402467573961989182504894),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_sel"
          (mksignature
            [.Xbool]
            .Xvoid
            { cc_vararg := (some 1), cc_unproto := false, cc_structret := false })))))

def global37 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 1806245498686479628810895294),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_annot"
          (mksignature
            [.Xptr]
            .Xvoid
            { cc_vararg := (some 1), cc_unproto := false, cc_structret := false })))))

def global38 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 7244945951003588654475720662375441416126),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_annot_intval"
          (mksignature
            [.Xptr, .Xint]
            .Xint
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global39 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 112849401203679898087896694718),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_membar"
          (mksignature
            []
            .Xvoid
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global40 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 473718132770801822480211367215038),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_va_start"
          (mksignature
            [.Xptr]
            .Xvoid
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global41 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 99560774972908693690150076350),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_va_arg"
          (mksignature
            [.Xptr, .Xint]
            .Xvoid
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global42 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 7795776575233686167852206833598),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_va_copy"
          (mksignature
            [.Xptr, .Xptr]
            .Xvoid
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global43 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 95770792528416831227446214590),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_va_end"
          (mksignature
            [.Xptr]
            .Xvoid
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global44 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 104119558379386447252596066449494687678),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_unreachable"
          (mksignature
            []
            .Xvoid
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global45 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 115364889162671663917173358526),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_expect"
          (mksignature
            [.Xlong, .Xlong]
            .Xlong
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global46 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 436022201432066856894398),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_cls"
          (mksignature
            [.Xint]
            .Xint
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global47 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 25823464413339279525724094),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_clsl"
          (mksignature
            [.Xlong]
            .Xint
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global48 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 1650619765975400890330824638),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_clsll"
          (mksignature
            [.Xlong]
            .Xint
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global49 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 1493374484074548252663922622),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_fmadd"
          (mksignature
            [.Xfloat, .Xfloat, .Xfloat]
            .Xfloat
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global50 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 1459911795176933946679672766),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_fmsub"
          (mksignature
            [.Xfloat, .Xfloat, .Xfloat]
            .Xfloat
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global51 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 95575967517583508903697104830),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_fnmadd"
          (mksignature
            [.Xfloat, .Xfloat, .Xfloat]
            .Xfloat
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global52 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 93434355428136193320705114046),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_fnmsub"
          (mksignature
            [.Xfloat, .Xfloat, .Xfloat]
            .Xfloat
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global53 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 29365316521232322094743486),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_fmax"
          (mksignature
            [.Xfloat, .Xfloat]
            .Xfloat
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global54 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 26380780904058706319687614),
    (.Gfun
      (.External
        (.EF_builtin
          "__builtin_fmin"
          (mksignature
            [.Xfloat, .Xfloat]
            .Xfloat
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global55 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 1556544987914242128768188350),
    (.Gfun
      (.External
        (.EF_external
          "__builtin_debug"
          (mksignature
            [.Xint]
            .Xvoid
            { cc_vararg := (some 1), cc_unproto := false, cc_structret := false })))))

def global56 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 25171890867130302),
    (.Gvar { gvar_info := (), gvar_init := [], gvar_readonly := false, gvar_volatile := false }))

def global57 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 5460367881807),
    (.Gfun
      (.External
        (.EF_external
          "fprintf"
          (mksignature
            [.Xptr, .Xptr]
            .Xint
            { cc_vararg := (some 2), cc_unproto := false, cc_structret := false })))))

def global58 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 24455246),
    (.Gfun
      (.External
        (.EF_external
          "exit"
          (mksignature
            [.Xint]
            .Xvoid
            { cc_vararg := none, cc_unproto := false, cc_structret := false })))))

def global59 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 26025026242339472),
    (.Gvar
      {
        gvar_info := (),
        gvar_init :=
          [
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 0))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13826747565314421532))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4603375528459645724))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13828524202941968968))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 0))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4605152166087193160))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13829303682744072581))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13823168210777488892))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4599796173922713084))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4605931645889296773))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13829709398833052265))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13826397356768737028))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 0))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4603025319913961220))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4606337361978276457))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13829946195113451550))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13827502901093058915))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13821137219365533128))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4597765182510757320))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4604130864238283107))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4606574158258675742))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13830096060480774702))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13828226375542350290))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13824354713062735199))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 0))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4600982676207959391))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4604854338687574482))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4606724023625998894))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13830196778479832164))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13828722990101689376))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13826280831530992820))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13819148986646033228))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4595776949791257420))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4602908794676217012))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4605350953246913568))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4606824741625056356))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13830267668587815173))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13829077555166904986))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13827072015111552393))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13822884887159941736))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 0))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4599512850305165928))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4603699978256776585))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4605705518312129178))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4606895631733039365))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13830319426557899482))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13829339054511796983))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13827666833757299092))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13824851014114699992))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 13817903820485812850))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4594531783631037042))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4601478977259924184))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4604294796902523284))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4605967017657021175))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4606947389703123674)))],
        gvar_readonly := true,
        gvar_volatile := false }))

def global60 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 107641204981888049808),
    (.Gfun
      (.Internal
        {
          fn_sig :=
            (mksignature
              [.Xint, .Xint]
              .Xfloat
              { cc_vararg := none, cc_unproto := false, cc_structret := false }),
          fn_stacksize := 0,
          fn_code :=
            (codeOfList
              [
                (
                  (Positive.ofNat 8),
                  [
                    (.Lop (.selected (.Olea (.Aindexed (-1)))) [.AX] .DX),
                    (.Lbranch (Positive.ofNat 7))]),
                (
                  (Positive.ofNat 4),
                  [(.Lop (.selected .Ocast32signed) [.AX] .CX), (.Lbranch (Positive.ofNat 3))]),
                ((Positive.ofNat 2), [(.Lbranch (Positive.ofNat 1))]),
                ((Positive.ofNat 10), [(.Lop .Omove [.SI] .AX), (.Lbranch (Positive.ofNat 9))]),
                (
                  (Positive.ofNat 6),
                  [
                    (.Lop (.selected (.Oshrximm (Integers.Int.repr 1))) [.AX] .AX),
                    (.Lbranch (Positive.ofNat 5))]),
                ((Positive.ofNat 1), [.Lreturn]),
                (
                  (Positive.ofNat 9),
                  [
                    (.Lop
                      (.selected
                        (.Oleal
                          (.Aglobal (Positive.ofNat 26025026242339472) (Integers.Ptrofs.repr 0))))
                      []
                      .SI),
                    (.Lbranch (Positive.ofNat 8))]),
                (
                  (Positive.ofNat 5),
                  [
                    (.Lop (.selected (.Olea (.Aindexed2 0))) [.AX, .DI] .AX),
                    (.Lbranch (Positive.ofNat 4))]),
                (
                  (Positive.ofNat 3),
                  [
                    (.Lload .Mfloat64 (.Aindexed2scaled 8 0) [.SI, .CX] .X0),
                    (.Lbranch (Positive.ofNat 2))]),
                (
                  (Positive.ofNat 7),
                  [(.Lop (.selected .Omul) [.AX, .DX] .AX), (.Lbranch (Positive.ofNat 6))])]),
          fn_entrypoint := (Positive.ofNat 10) })))

def global61 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 26025507278676624),
    (.Gvar
      {
        gvar_info := (),
        gvar_init :=
          [
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4611686018427387904))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4607182418800017408))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4607182418800017408))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4603179219131243638))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4606181618882823965))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4603179219131243638))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4599938015721666155))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4604049220898137291))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4604049220898137291))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4599938015721666155))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4597704210940560265))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4602293827526345043))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4603299315121306848))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4602293827526345043))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4597704210940560265))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4595340635650841579))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4600170522661702691))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4602100808003438055))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4602100808003438055))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4600170522661702691))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4595340635650841579))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4593833207853641058))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4598710344305444426))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4600550058610600766))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4601200903213297567))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4600550058610600766))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4598710344305444426))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4593833207853641058))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4591958705436230497))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4597180141441723269))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4599322856451823120))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4600205150124610371))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4600205150124610371))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4599322856451823120))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4597180141441723269))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4591958705436230497))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4590520857545404122))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4595676556204059612))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4598366364858742014))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4599298364636976404))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4599620683262412910))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4599298364636976404))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4598366364858742014))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4595676556204059612))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4590520857545404122))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4589468597325323285))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4594552572613292020))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4597061438375246896))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4598522297904897016))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4598995311071123185))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4598995311071123185))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4598522297904897016))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4597061438375246896))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4594552572613292020))),
            (.Init_float64 (Floats.Float.ofBits (Integers.Int64.repr 4589468597325323285)))],
        gvar_readonly := true,
        gvar_volatile := false }))

def global62 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 6882081821762725733008),
    (.Gfun
      (.Internal
        {
          fn_sig :=
            (mksignature
              [.Xint, .Xint]
              .Xfloat
              { cc_vararg := none, cc_unproto := false, cc_structret := false }),
          fn_stacksize := 0,
          fn_code :=
            (codeOfList
              [
                (
                  (Positive.ofNat 8),
                  [
                    (.Lop (.selected (.Olea (.Aindexed (-1)))) [.AX] .DX),
                    (.Lbranch (Positive.ofNat 7))]),
                (
                  (Positive.ofNat 4),
                  [(.Lop (.selected .Ocast32signed) [.AX] .CX), (.Lbranch (Positive.ofNat 3))]),
                ((Positive.ofNat 2), [(.Lbranch (Positive.ofNat 1))]),
                ((Positive.ofNat 10), [(.Lop .Omove [.SI] .AX), (.Lbranch (Positive.ofNat 9))]),
                (
                  (Positive.ofNat 6),
                  [
                    (.Lop (.selected (.Oshrximm (Integers.Int.repr 1))) [.AX] .AX),
                    (.Lbranch (Positive.ofNat 5))]),
                ((Positive.ofNat 1), [.Lreturn]),
                (
                  (Positive.ofNat 9),
                  [
                    (.Lop
                      (.selected
                        (.Oleal
                          (.Aglobal (Positive.ofNat 26025507278676624) (Integers.Ptrofs.repr 0))))
                      []
                      .SI),
                    (.Lbranch (Positive.ofNat 8))]),
                (
                  (Positive.ofNat 5),
                  [
                    (.Lop (.selected (.Olea (.Aindexed2 0))) [.AX, .DI] .AX),
                    (.Lbranch (Positive.ofNat 4))]),
                (
                  (Positive.ofNat 3),
                  [
                    (.Lload .Mfloat64 (.Aindexed2scaled 8 0) [.SI, .CX] .X0),
                    (.Lbranch (Positive.ofNat 2))]),
                (
                  (Positive.ofNat 7),
                  [(.Lop (.selected .Omul) [.AX, .DX] .AX), (.Lbranch (Positive.ofNat 6))])]),
          fn_entrypoint := (Positive.ofNat 10) })))

def global63 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 95349600521002224177099432592),
    (.Gfun
      (.Internal
        {
          fn_sig :=
            (mksignature
              [.Xint]
              .Xint
              { cc_vararg := none, cc_unproto := false, cc_structret := false }),
          fn_stacksize := 0,
          fn_code :=
            (codeOfList
              [
                (
                  (Positive.ofNat 16),
                  [
                    (.Lcond
                      (.Ccompimm .Ceq (Integers.Int.repr 1))
                      [.DI]
                      (Positive.ofNat 2)
                      (Positive.ofNat 15))]),
                (
                  (Positive.ofNat 8),
                  [
                    (.Lop .Omove [.DI] .DX),
                    (.Lop .Omove [.AX] .DI),
                    (.Lcall
                      (mksignature
                        [.Xptr, .Xptr, .Xint]
                        .Xint
                        { cc_vararg := (some 2), cc_unproto := false, cc_structret := false })
                      (.inr (Positive.ofNat 5460367881807))),
                    (.Lbranch (Positive.ofNat 7))]),
                (
                  (Positive.ofNat 4),
                  [
                    (.Lop (.selected (.Ointconst (Integers.Int.repr 3))) [] .BX),
                    (.Lbranch (Positive.ofNat 1))]),
                (
                  (Positive.ofNat 12),
                  [
                    (.Lcond
                      (.Ccompimm .Ceq (Integers.Int.repr 25))
                      [.DI]
                      (Positive.ofNat 11)
                      (Positive.ofNat 10))]),
                (
                  (Positive.ofNat 2),
                  [
                    (.Lop (.selected (.Ointconst (Integers.Int.repr 1))) [] .BX),
                    (.Lbranch (Positive.ofNat 1))]),
                ((Positive.ofNat 18), [(.Lbranch (Positive.ofNat 17))]),
                (
                  (Positive.ofNat 10),
                  [
                    (.Lload
                      .Mint64
                      (.Aglobal (Positive.ofNat 25171890867130302) (Integers.Ptrofs.repr 0))
                      []
                      .AX),
                    (.Lbranch (Positive.ofNat 9))]),
                (
                  (Positive.ofNat 6),
                  [
                    (.Lcall
                      (mksignature
                        [.Xint]
                        .Xvoid
                        { cc_vararg := none, cc_unproto := false, cc_structret := false })
                      (.inr (Positive.ofNat 24455246))),
                    (.Lbranch (Positive.ofNat 1))]),
                (
                  (Positive.ofNat 14),
                  [
                    (.Lcond
                      (.Ccompimm .Ceq (Integers.Int.repr 9))
                      [.DI]
                      (Positive.ofNat 4)
                      (Positive.ofNat 13))]),
                ((Positive.ofNat 1), [(.Lop .Omove [.BX] .AX), .Lreturn]),
                ((Positive.ofNat 17), [(.Lbranch (Positive.ofNat 16))]),
                (
                  (Positive.ofNat 9),
                  [
                    (.Lop
                      (.selected
                        (.Oleal
                          (.Aglobal
                            (Positive.ofNat 311562378882557268053950)
                            (Integers.Ptrofs.repr 0))))
                      []
                      .SI),
                    (.Lbranch (Positive.ofNat 8))]),
                (
                  (Positive.ofNat 5),
                  [
                    (.Lop (.selected (.Ointconst (Integers.Int.repr 4))) [] .BX),
                    (.Lbranch (Positive.ofNat 1))]),
                (
                  (Positive.ofNat 13),
                  [
                    (.Lcond
                      (.Ccompimm .Ceq (Integers.Int.repr 16))
                      [.DI]
                      (Positive.ofNat 5)
                      (Positive.ofNat 12))]),
                (
                  (Positive.ofNat 3),
                  [
                    (.Lop (.selected (.Ointconst (Integers.Int.repr 2))) [] .BX),
                    (.Lbranch (Positive.ofNat 1))]),
                (
                  (Positive.ofNat 11),
                  [
                    (.Lop (.selected (.Ointconst (Integers.Int.repr 5))) [] .BX),
                    (.Lbranch (Positive.ofNat 1))]),
                (
                  (Positive.ofNat 7),
                  [
                    (.Lop (.selected (.Ointconst (Integers.Int.repr 4294967295))) [] .DI),
                    (.Lbranch (Positive.ofNat 6))]),
                (
                  (Positive.ofNat 15),
                  [
                    (.Lcond
                      (.Ccompimm .Ceq (Integers.Int.repr 4))
                      [.DI]
                      (Positive.ofNat 3)
                      (Positive.ofNat 14))])]),
          fn_entrypoint := (Positive.ofNat 18) })))

def global64 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 440898375604754713797264),
    (.Gfun
      (.Internal
        {
          fn_sig :=
            (mksignature
              [.Xptr, .Xint, .Xint]
              .Xvoid
              { cc_vararg := none, cc_unproto := false, cc_structret := false }),
          fn_stacksize := 0,
          fn_code :=
            (codeOfList
              [
                ((Positive.ofNat 8), [(.Lop .Omove [.AX] .BX), (.Lbranch (Positive.ofNat 7))]),
                (
                  (Positive.ofNat 4),
                  [(.Lstore .Mfloat64 (.Aindexed 0) [.R12] .X0), (.Lbranch (Positive.ofNat 3))]),
                (
                  (Positive.ofNat 2),
                  [(.Lstore .Mfloat64 (.Aindexed 8) [.R12] .X0), (.Lbranch (Positive.ofNat 1))]),
                (
                  (Positive.ofNat 10),
                  [
                    (.Lop .Omove [.DI] .R12),
                    (.Lop .Omove [.DX] .DI),
                    (.Lop .Omove [.SI] .BP),
                    (.Lbranch (Positive.ofNat 9))]),
                (
                  (Positive.ofNat 6),
                  [
                    (.Lop .Omove [.BP] .AX),
                    (.Lop .Omove [.BX] .CX),
                    (.Lop (.selected .Odiv) [.AX, .CX] .AX),
                    (.Lop .Omove [.AX] .BP),
                    (.Lbranch (Positive.ofNat 5))]),
                ((Positive.ofNat 1), [.Lreturn]),
                (
                  (Positive.ofNat 9),
                  [
                    (.Lcall
                      (mksignature
                        [.Xint]
                        .Xint
                        { cc_vararg := none, cc_unproto := false, cc_structret := false })
                      (.inr (Positive.ofNat 95349600521002224177099432592))),
                    (.Lbranch (Positive.ofNat 8))]),
                (
                  (Positive.ofNat 5),
                  [
                    (.Lop .Omove [.BX] .SI),
                    (.Lcall
                      (mksignature
                        [.Xint, .Xint]
                        .Xfloat
                        { cc_vararg := none, cc_unproto := false, cc_structret := false })
                      (.inr (Positive.ofNat 107641204981888049808))),
                    (.Lbranch (Positive.ofNat 4))]),
                (
                  (Positive.ofNat 3),
                  [
                    (.Lop .Omove [.BX] .SI),
                    (.Lop .Omove [.BP] .DI),
                    (.Lcall
                      (mksignature
                        [.Xint, .Xint]
                        .Xfloat
                        { cc_vararg := none, cc_unproto := false, cc_structret := false })
                      (.inr (Positive.ofNat 107641204981888049808))),
                    (.Lbranch (Positive.ofNat 2))]),
                (
                  (Positive.ofNat 7),
                  [
                    (.Lop .Omove [.BP] .AX),
                    (.Lop .Omove [.BX] .CX),
                    (.Lop (.selected .Omod) [.AX, .CX] .DX),
                    (.Lop .Omove [.DX] .DI),
                    (.Lbranch (Positive.ofNat 6))])]),
          fn_entrypoint := (Positive.ofNat 10) })))

def global65 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 28189007141939065864184464),
    (.Gfun
      (.Internal
        {
          fn_sig :=
            (mksignature
              [.Xint, .Xint]
              .Xfloat
              { cc_vararg := none, cc_unproto := false, cc_structret := false }),
          fn_stacksize := 0,
          fn_code :=
            (codeOfList
              [
                (
                  (Positive.ofNat 8),
                  [
                    (.Lop .Omove [.SI] .DI),
                    (.Lcall
                      (mksignature
                        [.Xint]
                        .Xint
                        { cc_vararg := none, cc_unproto := false, cc_structret := false })
                      (.inr (Positive.ofNat 95349600521002224177099432592))),
                    (.Lop .Omove [.AX] .BX),
                    (.Lbranch (Positive.ofNat 7))]),
                (
                  (Positive.ofNat 4),
                  [
                    (.Lop .Omove [.BX] .SI),
                    (.Lcall
                      (mksignature
                        [.Xint, .Xint]
                        .Xfloat
                        { cc_vararg := none, cc_unproto := false, cc_structret := false })
                      (.inr (Positive.ofNat 6882081821762725733008))),
                    (.Lsetstack .X0 .Local 0 .Tfloat),
                    (.Lbranch (Positive.ofNat 3))]),
                (
                  (Positive.ofNat 2),
                  [
                    (.Lgetstack .Local 0 .Tfloat .X1),
                    (.Lop (.selected .Omulf) [.X1, .X0] .X1),
                    (.Lop .Omove [.X1] .X0),
                    (.Lbranch (Positive.ofNat 1))]),
                (
                  (Positive.ofNat 6),
                  [
                    (.Lop .Omove [.BP] .AX),
                    (.Lop .Omove [.BX] .CX),
                    (.Lop (.selected .Omod) [.AX, .CX] .DX),
                    (.Lop .Omove [.DX] .DI),
                    (.Lbranch (Positive.ofNat 5))]),
                ((Positive.ofNat 1), [.Lreturn]),
                ((Positive.ofNat 9), [(.Lop .Omove [.DI] .BP), (.Lbranch (Positive.ofNat 8))]),
                (
                  (Positive.ofNat 5),
                  [
                    (.Lop .Omove [.BP] .AX),
                    (.Lop .Omove [.BX] .CX),
                    (.Lop (.selected .Odiv) [.AX, .CX] .AX),
                    (.Lop .Omove [.AX] .BP),
                    (.Lbranch (Positive.ofNat 4))]),
                (
                  (Positive.ofNat 3),
                  [
                    (.Lop .Omove [.BX] .SI),
                    (.Lop .Omove [.BP] .DI),
                    (.Lcall
                      (mksignature
                        [.Xint, .Xint]
                        .Xfloat
                        { cc_vararg := none, cc_unproto := false, cc_structret := false })
                      (.inr (Positive.ofNat 6882081821762725733008))),
                    (.Lbranch (Positive.ofNat 2))]),
                ((Positive.ofNat 7), [(.Lbranch (Positive.ofNat 6))])]),
          fn_entrypoint := (Positive.ofNat 9) })))

def global66 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 6889037118840596924305),
    (.Gfun
      (.Internal
        {
          fn_sig :=
            (mksignature
              [.Xptr, .Xint, .Xint]
              .Xvoid
              { cc_vararg := none, cc_unproto := false, cc_structret := false }),
          fn_stacksize := 0,
          fn_code :=
            (codeOfList
              [
                (
                  (Positive.ofNat 16),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 4602678819172646912))))
                      []
                      .X3),
                    (.Lbranch (Positive.ofNat 15))]),
                (
                  (Positive.ofNat 8),
                  [(.Lstore .Mfloat64 (.Aindexed 0) [.DI] .X5), (.Lbranch (Positive.ofNat 7))]),
                (
                  (Positive.ofNat 4),
                  [(.Lstore .Mfloat64 (.Aindexed 0) [.DI] .X2), (.Lbranch (Positive.ofNat 3))]),
                (
                  (Positive.ofNat 20),
                  [
                    (.Lcond
                      (.Ccompimm .Ceq (Integers.Int.repr 1))
                      [.SI]
                      (Positive.ofNat 9)
                      (Positive.ofNat 19))]),
                (
                  (Positive.ofNat 12),
                  [
                    (.Lcall
                      (mksignature
                        [.Xptr, .Xptr]
                        .Xint
                        { cc_vararg := (some 2), cc_unproto := false, cc_structret := false })
                      (.inr (Positive.ofNat 5460367881807))),
                    (.Lbranch (Positive.ofNat 11))]),
                (
                  (Positive.ofNat 2),
                  [(.Lstore .Mfloat64 (.Aindexed 8) [.DI] .X6), (.Lbranch (Positive.ofNat 1))]),
                (
                  (Positive.ofNat 18),
                  [
                    (.Lop
                      (.selected (.Ofloatconst (Floats.Float.ofBits (Integers.Int64.repr 0))))
                      []
                      .X1),
                    (.Lbranch (Positive.ofNat 17))]),
                (
                  (Positive.ofNat 10),
                  [
                    (.Lcall
                      (mksignature
                        [.Xint]
                        .Xvoid
                        { cc_vararg := none, cc_unproto := false, cc_structret := false })
                      (.inr (Positive.ofNat 24455246))),
                    (.Lbranch (Positive.ofNat 1))]),
                (
                  (Positive.ofNat 6),
                  [(.Lstore .Mfloat64 (.Aindexed 8) [.DI] .X4), (.Lbranch (Positive.ofNat 1))]),
                ((Positive.ofNat 22), [(.Lbranch (Positive.ofNat 21))]),
                (
                  (Positive.ofNat 14),
                  [
                    (.Lload
                      .Mint64
                      (.Aglobal (Positive.ofNat 25171890867130302) (Integers.Ptrofs.repr 0))
                      []
                      .DI),
                    (.Lbranch (Positive.ofNat 13))]),
                ((Positive.ofNat 1), [.Lreturn]),
                (
                  (Positive.ofNat 17),
                  [(.Lstore .Mfloat64 (.Aindexed 0) [.DI] .X1), (.Lbranch (Positive.ofNat 16))]),
                (
                  (Positive.ofNat 9),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 4602678819172646912))))
                      []
                      .X5),
                    (.Lbranch (Positive.ofNat 8))]),
                (
                  (Positive.ofNat 5),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 4602678819172646912))))
                      []
                      .X2),
                    (.Lbranch (Positive.ofNat 4))]),
                (
                  (Positive.ofNat 21),
                  [
                    (.Lcond
                      (.Ccompimm .Ceq (Integers.Int.repr 0))
                      [.SI]
                      (Positive.ofNat 5)
                      (Positive.ofNat 20))]),
                (
                  (Positive.ofNat 13),
                  [
                    (.Lop
                      (.selected
                        (.Oleal
                          (.Aglobal
                            (Positive.ofNat 316284745365426913267646)
                            (Integers.Ptrofs.repr 0))))
                      []
                      .SI),
                    (.Lbranch (Positive.ofNat 12))]),
                (
                  (Positive.ofNat 3),
                  [
                    (.Lop
                      (.selected (.Ofloatconst (Floats.Float.ofBits (Integers.Int64.repr 0))))
                      []
                      .X6),
                    (.Lbranch (Positive.ofNat 2))]),
                (
                  (Positive.ofNat 19),
                  [
                    (.Lcond
                      (.Ccompimm .Ceq (Integers.Int.repr 2))
                      [.SI]
                      (Positive.ofNat 18)
                      (Positive.ofNat 14))]),
                (
                  (Positive.ofNat 11),
                  [
                    (.Lop (.selected (.Ointconst (Integers.Int.repr 4294967295))) [] .DI),
                    (.Lbranch (Positive.ofNat 10))]),
                (
                  (Positive.ofNat 7),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 4602678819172646912))))
                      []
                      .X4),
                    (.Lbranch (Positive.ofNat 6))]),
                ((Positive.ofNat 23), [(.Lbranch (Positive.ofNat 22))]),
                (
                  (Positive.ofNat 15),
                  [(.Lstore .Mfloat64 (.Aindexed 8) [.DI] .X3), (.Lbranch (Positive.ofNat 1))])]),
          fn_entrypoint := (Positive.ofNat 23) })))

def global67 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 440453236592814208649105),
    (.Gfun
      (.Internal
        {
          fn_sig :=
            (mksignature
              [.Xint, .Xint]
              .Xfloat
              { cc_vararg := none, cc_unproto := false, cc_structret := false }),
          fn_stacksize := 0,
          fn_code :=
            (codeOfList
              [
                (
                  (Positive.ofNat 4),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 4607182418800017408))))
                      []
                      .X0),
                    (.Lbranch (Positive.ofNat 3))]),
                (
                  (Positive.ofNat 2),
                  [(.Lop (.selected .Odivf) [.X0, .X1] .X0), (.Lbranch (Positive.ofNat 1))]),
                ((Positive.ofNat 1), [.Lreturn]),
                ((Positive.ofNat 5), [(.Lbranch (Positive.ofNat 4))]),
                (
                  (Positive.ofNat 3),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 4618441417868443648))))
                      []
                      .X1),
                    (.Lbranch (Positive.ofNat 2))])]),
          fn_entrypoint := (Positive.ofNat 5) })))

def global68 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 378380),
    (.Gfun
      (.Internal
        {
          fn_sig :=
            (mksignature
              [.Xfloat]
              .Xfloat
              { cc_vararg := none, cc_unproto := false, cc_structret := false }),
          fn_stacksize := 0,
          fn_code :=
            (codeOfList
              [
                (
                  (Positive.ofNat 16),
                  [(.Lop (.selected .Oaddf) [.X1, .X9] .X1), (.Lbranch (Positive.ofNat 15))]),
                (
                  (Positive.ofNat 8),
                  [(.Lop (.selected .Oaddf) [.X2, .X9] .X2), (.Lbranch (Positive.ofNat 7))]),
                (
                  (Positive.ofNat 24),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 4586165620538955093))))
                      []
                      .X7),
                    (.Lbranch (Positive.ofNat 23))]),
                (
                  (Positive.ofNat 4),
                  [(.Lop (.selected .Oaddf) [.X3, .X10] .X3), (.Lbranch (Positive.ofNat 3))]),
                (
                  (Positive.ofNat 20),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 4477122120089393304))))
                      []
                      .X8),
                    (.Lbranch (Positive.ofNat 19))]),
                (
                  (Positive.ofNat 12),
                  [(.Lop (.selected .Oaddf) [.X4, .X11] .X4), (.Lbranch (Positive.ofNat 11))]),
                ((Positive.ofNat 28), [(.Lop .Omove [.X0] .X5), (.Lbranch (Positive.ofNat 27))]),
                (
                  (Positive.ofNat 2),
                  [(.Lop (.selected .Oaddf) [.X0, .X5] .X0), (.Lbranch (Positive.ofNat 1))]),
                (
                  (Positive.ofNat 18),
                  [
                    (.Lop
                      (.selected (.Ofloatconst (Floats.Float.ofBits (Integers.Int64.repr 0))))
                      []
                      .X15),
                    (.Lbranch (Positive.ofNat 17))]),
                (
                  (Positive.ofNat 10),
                  [(.Lop (.selected .Oaddf) [.X6, .X12] .X6), (.Lbranch (Positive.ofNat 9))]),
                (
                  (Positive.ofNat 26),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 4607182418800017408))))
                      []
                      .X0),
                    (.Lbranch (Positive.ofNat 25))]),
                (
                  (Positive.ofNat 6),
                  [(.Lop (.selected .Oaddf) [.X7, .X13] .X7), (.Lbranch (Positive.ofNat 5))]),
                (
                  (Positive.ofNat 22),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 4537941361671905306))))
                      []
                      .X6),
                    (.Lbranch (Positive.ofNat 21))]),
                (
                  (Positive.ofNat 14),
                  [(.Lop (.selected .Oaddf) [.X8, .X14] .X8), (.Lbranch (Positive.ofNat 13))]),
                ((Positive.ofNat 1), [.Lreturn]),
                (
                  (Positive.ofNat 17),
                  [
                    (.Lop .Omove [.X5] .X9),
                    (.Lop (.selected .Omulf) [.X9, .X15] .X9),
                    (.Lbranch (Positive.ofNat 16))]),
                (
                  (Positive.ofNat 9),
                  [
                    (.Lop .Omove [.X5] .X9),
                    (.Lop (.selected .Omulf) [.X9, .X6] .X9),
                    (.Lbranch (Positive.ofNat 8))]),
                (
                  (Positive.ofNat 25),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 13826050856027422720))))
                      []
                      .X3),
                    (.Lbranch (Positive.ofNat 24))]),
                (
                  (Positive.ofNat 5),
                  [
                    (.Lop .Omove [.X5] .X10),
                    (.Lop (.selected .Omulf) [.X10, .X7] .X10),
                    (.Lbranch (Positive.ofNat 4))]),
                (
                  (Positive.ofNat 21),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 13732177094651715420))))
                      []
                      .X4),
                    (.Lbranch (Positive.ofNat 20))]),
                (
                  (Positive.ofNat 13),
                  [
                    (.Lop .Omove [.X5] .X11),
                    (.Lop (.selected .Omulf) [.X11, .X8] .X11),
                    (.Lbranch (Positive.ofNat 12))]),
                (
                  (Positive.ofNat 3),
                  [(.Lop (.selected .Omulf) [.X5, .X3] .X5), (.Lbranch (Positive.ofNat 2))]),
                (
                  (Positive.ofNat 19),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 13666517717442657437))))
                      []
                      .X1),
                    (.Lbranch (Positive.ofNat 18))]),
                (
                  (Positive.ofNat 11),
                  [
                    (.Lop .Omove [.X5] .X12),
                    (.Lop (.selected .Omulf) [.X12, .X4] .X12),
                    (.Lbranch (Positive.ofNat 10))]),
                (
                  (Positive.ofNat 27),
                  [(.Lop (.selected .Omulf) [.X5, .X5] .X5), (.Lbranch (Positive.ofNat 26))]),
                (
                  (Positive.ofNat 7),
                  [
                    (.Lop .Omove [.X5] .X13),
                    (.Lop (.selected .Omulf) [.X13, .X2] .X13),
                    (.Lbranch (Positive.ofNat 6))]),
                (
                  (Positive.ofNat 23),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 13787419979223755799))))
                      []
                      .X2),
                    (.Lbranch (Positive.ofNat 22))]),
                (
                  (Positive.ofNat 15),
                  [
                    (.Lop .Omove [.X5] .X14),
                    (.Lop (.selected .Omulf) [.X14, .X1] .X14),
                    (.Lbranch (Positive.ofNat 14))])]),
          fn_entrypoint := (Positive.ofNat 28) })))

def global69 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 22083307990275538),
    (.Gfun
      (.Internal
        {
          fn_sig :=
            (mksignature
              [.Xptr, .Xint]
              .Xfloat
              { cc_vararg := none, cc_unproto := false, cc_structret := false }),
          fn_stacksize := 0,
          fn_code :=
            (codeOfList
              [
                (
                  (Positive.ofNat 8),
                  [
                    (.Lop .Omove [.BX] .SI),
                    (.Lop .Omove [.BP] .DI),
                    (.Lcall
                      (mksignature
                        [.Xint, .Xint]
                        .Xfloat
                        { cc_vararg := none, cc_unproto := false, cc_structret := false })
                      (.inr (Positive.ofNat 107641204981888049808))),
                    (.Lbranch (Positive.ofNat 7))]),
                (
                  (Positive.ofNat 4),
                  [
                    (.Lop (.selected (.Olea (.Aindexed 1))) [.BP] .BP),
                    (.Lbranch (Positive.ofNat 3))]),
                (
                  (Positive.ofNat 12),
                  [
                    (.Lop (.selected (.Ointconst (Integers.Int.repr 0))) [] .BP),
                    (.Lbranch (Positive.ofNat 11))]),
                (
                  (Positive.ofNat 2),
                  [(.Lgetstack .Local 0 .Tfloat .X0), (.Lbranch (Positive.ofNat 1))]),
                (
                  (Positive.ofNat 10),
                  [(.Lcond (.Ccomp .Clt) [.BP, .BX] (Positive.ofNat 9) (Positive.ofNat 2))]),
                (
                  (Positive.ofNat 6),
                  [
                    (.Lgetstack .Local 2 .Tfloat .X2),
                    (.Lop (.selected .Omulf) [.X2, .X0] .X2),
                    (.Lbranch (Positive.ofNat 5))]),
                (
                  (Positive.ofNat 14),
                  [
                    (.Lop .Omove [.SI] .BX),
                    (.Lop .Omove [.DI] .R12),
                    (.Lbranch (Positive.ofNat 13))]),
                ((Positive.ofNat 1), [.Lreturn]),
                (
                  (Positive.ofNat 9),
                  [
                    (.Lop .Omove [.BX] .SI),
                    (.Lop .Omove [.BP] .DI),
                    (.Lcall
                      (mksignature
                        [.Xint, .Xint]
                        .Xfloat
                        { cc_vararg := none, cc_unproto := false, cc_structret := false })
                      (.inr (Positive.ofNat 6882081821762725733008))),
                    (.Lsetstack .X0 .Local 2 .Tfloat),
                    (.Lbranch (Positive.ofNat 8))]),
                (
                  (Positive.ofNat 5),
                  [
                    (.Lgetstack .Local 0 .Tfloat .X1),
                    (.Lop (.selected .Oaddf) [.X1, .X2] .X1),
                    (.Lsetstack .X1 .Local 0 .Tfloat),
                    (.Lbranch (Positive.ofNat 4))]),
                (
                  (Positive.ofNat 13),
                  [
                    (.Lop
                      (.selected (.Ofloatconst (Floats.Float.ofBits (Integers.Int64.repr 0))))
                      []
                      .X0),
                    (.Lsetstack .X0 .Local 0 .Tfloat),
                    (.Lbranch (Positive.ofNat 12))]),
                ((Positive.ofNat 3), [(.Lbranch (Positive.ofNat 10))]),
                ((Positive.ofNat 11), [(.Lbranch (Positive.ofNat 10))]),
                (
                  (Positive.ofNat 7),
                  [
                    (.Lcall
                      (mksignature
                        [.Xfloat]
                        .Xfloat
                        { cc_vararg := none, cc_unproto := false, cc_structret := false })
                      (.inl .R12)),
                    (.Lbranch (Positive.ofNat 6))])]),
          fn_entrypoint := (Positive.ofNat 14) })))

def global70 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 6011066106781),
    (.Gfun
      (.Internal
        {
          fn_sig :=
            (mksignature
              [.Xfloat]
              .Xfloat
              { cc_vararg := none, cc_unproto := false, cc_structret := false }),
          fn_stacksize := 0,
          fn_code :=
            (codeOfList
              [
                (
                  (Positive.ofNat 8),
                  [(.Lsetstack .X0 .Local 0 .Tfloat), (.Lbranch (Positive.ofNat 7))]),
                (
                  (Positive.ofNat 4),
                  [
                    (.Lgetstack .Local 0 .Tfloat .X1),
                    (.Lop (.selected .Osubf) [.X2, .X1] .X2),
                    (.Lbranch (Positive.ofNat 3))]),
                (
                  (Positive.ofNat 2),
                  [(.Lop (.selected .Omulf) [.X3, .X0] .X3), (.Lbranch (Positive.ofNat 1))]),
                (
                  (Positive.ofNat 6),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 4602678819172646912))))
                      []
                      .X3),
                    (.Lbranch (Positive.ofNat 5))]),
                ((Positive.ofNat 1), [(.Lop .Omove [.X3] .X0), .Lreturn]),
                (
                  (Positive.ofNat 5),
                  [
                    (.Lop
                      (.selected
                        (.Ofloatconst
                          (Floats.Float.ofBits (Integers.Int64.repr 4607182418800017408))))
                      []
                      .X2),
                    (.Lbranch (Positive.ofNat 4))]),
                (
                  (Positive.ofNat 3),
                  [(.Lop (.selected .Omulf) [.X3, .X2] .X3), (.Lbranch (Positive.ofNat 2))]),
                (
                  (Positive.ofNat 7),
                  [
                    (.Lgetstack .Local 0 .Tfloat .X0),
                    (.Lcall
                      (mksignature
                        [.Xfloat]
                        .Xfloat
                        { cc_vararg := none, cc_unproto := false, cc_structret := false })
                      (.inr (Positive.ofNat 378380))),
                    (.Lbranch (Positive.ofNat 6))])]),
          fn_entrypoint := (Positive.ofNat 8) })))

def global71 : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 6930287380122293369677211620818),
    (.Gfun
      (.Internal
        {
          fn_sig :=
            (mksignature
              []
              .Xfloat
              { cc_vararg := none, cc_unproto := false, cc_structret := false }),
          fn_stacksize := 0,
          fn_code :=
            (codeOfList
              [
                (
                  (Positive.ofNat 4),
                  [
                    (.Lop (.selected (.Ointconst (Integers.Int.repr 2))) [] .SI),
                    (.Lbranch (Positive.ofNat 3))]),
                ((Positive.ofNat 2), [(.Lbranch (Positive.ofNat 1))]),
                ((Positive.ofNat 6), [(.Lbranch (Positive.ofNat 5))]),
                ((Positive.ofNat 1), [.Lreturn]),
                (
                  (Positive.ofNat 5),
                  [
                    (.Lop
                      (.selected
                        (.Oleal
                          (.Aglobal (Positive.ofNat 6011066106781) (Integers.Ptrofs.repr 0))))
                      []
                      .DI),
                    (.Lbranch (Positive.ofNat 4))]),
                (
                  (Positive.ofNat 3),
                  [
                    (.Lcall
                      (mksignature
                        [.Xptr, .Xint]
                        .Xfloat
                        { cc_vararg := none, cc_unproto := false, cc_structret := false })
                      (.inr (Positive.ofNat 22083307990275538))),
                    (.Lbranch (Positive.ofNat 2))])]),
          fn_entrypoint := (Positive.ofNat 6) })))

def mainDefinition (n : Nat) : Ident × GlobDef Fundef Unit :=
  (
    (Positive.ofNat 22880918),
    (.Gfun
      (.Internal
        {
          fn_sig :=
            (mksignature
              []
              .Xint
              { cc_vararg := none, cc_unproto := false, cc_structret := false }),
          fn_stacksize := 0,
          fn_code :=
            (codeOfList
              [
                (
                  (Positive.ofNat 4),
                  [
                    (.Lcall
                      (mksignature
                        [.Xptr, .Xint]
                        .Xfloat
                        { cc_vararg := none, cc_unproto := false, cc_structret := false })
                      (.inr (Positive.ofNat 22083307990275538))),
                    (.Lbranch (Positive.ofNat 3))]),
                (
                  (Positive.ofNat 2),
                  [
                    (.Lop (.selected (.Ointconst (Integers.Int.repr 0))) [] .AX),
                    (.Lbranch (Positive.ofNat 1))]),
                (
                  (Positive.ofNat 6),
                  [
                    (.Lop
                      (.selected
                        (.Oleal
                          (.Aglobal (Positive.ofNat 6011066106781) (Integers.Ptrofs.repr 0))))
                      []
                      .DI),
                    (.Lbranch (Positive.ofNat 5))]),
                ((Positive.ofNat 1), [.Lreturn]),
                (
                  (Positive.ofNat 5),
                  [
                    (.Lop (.selected (.Ointconst (Integers.Int.repr (n : Int)))) [] .SI),
                    (.Lbranch (Positive.ofNat 4))]),
                (
                  (Positive.ofNat 3),
                  [
                    (.Lbuiltin
                      (.EF_annot (Positive.ofNat 1) "quadrature-result" [.Tfloat])
                      [(.BA (.R .X0))]
                      .BR_none),
                    (.Lbranch (Positive.ofNat 2))]),
                ((Positive.ofNat 7), [(.Lbranch (Positive.ofNat 6))])]),
          fn_entrypoint := (Positive.ofNat 7) })))

def program (n : Nat) : Program where
  prog_defs := [
                 global0,
                 global1,
                 global2,
                 global3,
                 global4,
                 global5,
                 global6,
                 global7,
                 global8,
                 global9,
                 global10,
                 global11,
                 global12,
                 global13,
                 global14,
                 global15,
                 global16,
                 global17,
                 global18,
                 global19,
                 global20,
                 global21,
                 global22,
                 global23,
                 global24,
                 global25,
                 global26,
                 global27,
                 global28,
                 global29,
                 global30,
                 global31,
                 global32,
                 global33,
                 global34,
                 global35,
                 global36,
                 global37,
                 global38,
                 global39,
                 global40,
                 global41,
                 global42,
                 global43,
                 global44,
                 global45,
                 global46,
                 global47,
                 global48,
                 global49,
                 global50,
                 global51,
                 global52,
                 global53,
                 global54,
                 global55,
                 global56,
                 global57,
                 global58,
                 global59,
                 global60,
                 global61,
                 global62,
                 global63,
                 global64,
                 global65,
                 global66,
                 global67,
                 global68,
                 global69,
                 global70,
                 global71,
                 mainDefinition n]
  prog_public := [
                   (Positive.ofNat 22880918),
                   (Positive.ofNat 6930287380122293369677211620818),
                   (Positive.ofNat 6011066106781),
                   (Positive.ofNat 22083307990275538),
                   (Positive.ofNat 378380),
                   (Positive.ofNat 440453236592814208649105),
                   (Positive.ofNat 6889037118840596924305),
                   (Positive.ofNat 28189007141939065864184464),
                   (Positive.ofNat 440898375604754713797264),
                   (Positive.ofNat 95349600521002224177099432592),
                   (Positive.ofNat 6882081821762725733008),
                   (Positive.ofNat 107641204981888049808),
                   (Positive.ofNat 24455246),
                   (Positive.ofNat 5460367881807),
                   (Positive.ofNat 25171890867130302),
                   (Positive.ofNat 1556544987914242128768188350),
                   (Positive.ofNat 26380780904058706319687614),
                   (Positive.ofNat 29365316521232322094743486),
                   (Positive.ofNat 93434355428136193320705114046),
                   (Positive.ofNat 95575967517583508903697104830),
                   (Positive.ofNat 1459911795176933946679672766),
                   (Positive.ofNat 1493374484074548252663922622),
                   (Positive.ofNat 1650619765975400890330824638),
                   (Positive.ofNat 25823464413339279525724094),
                   (Positive.ofNat 436022201432066856894398),
                   (Positive.ofNat 115364889162671663917173358526),
                   (Positive.ofNat 104119558379386447252596066449494687678),
                   (Positive.ofNat 95770792528416831227446214590),
                   (Positive.ofNat 7795776575233686167852206833598),
                   (Positive.ofNat 99560774972908693690150076350),
                   (Positive.ofNat 473718132770801822480211367215038),
                   (Positive.ofNat 112849401203679898087896694718),
                   (Positive.ofNat 7244945951003588654475720662375441416126),
                   (Positive.ofNat 1806245498686479628810895294),
                   (Positive.ofNat 402467573961989182504894),
                   (Positive.ofNat 26908785589146098326477794481020231027834814),
                   (Positive.ofNat 28236981067711216130506686),
                   (Positive.ofNat 1807166734850128206852833214),
                   (Positive.ofNat 1536597419048538577246404542),
                   (Positive.ofNat 27857996169481367213096894),
                   (Positive.ofNat 1650653412836591336552972222),
                   (Positive.ofNat 25857111274529725747871678),
                   (Positive.ofNat 469669062622513079041982),
                   (Positive.ofNat 1650652822540780977847320510),
                   (Positive.ofNat 25856520978719367042219966),
                   (Positive.ofNat 469078766812154373390270),
                   (Positive.ofNat 5547696061875752272513199554494),
                   (Positive.ofNat 5233259291897265682688822001598),
                   (Positive.ofNat 1724685877248640965123030974),
                   (Positive.ofNat 5395429437043650498700607274942),
                   (Positive.ofNat 1689272971222408066064352383141466046),
                   (Positive.ofNat 1689272968746527987493591833343217598),
                   (Positive.ofNat 462252962922391389178819298512830),
                   (Positive.ofNat 462807560059991239541974106165182),
                   (Positive.ofNat 432383945654513733906053229236158),
                   (Positive.ofNat 25111404447590333614692388749496254),
                   (Positive.ofNat 25111401971710255043931838951247806),
                   (Positive.ofNat 30921601745573908812114934347386814),
                   (Positive.ofNat 30921599269693830241354384549138366),
                   (Positive.ofNat 25760996152044786918621855598301118),
                   (Positive.ofNat 25760993676164708347861305800052670),
                   (Positive.ofNat 25111959044727933465055543557148606),
                   (Positive.ofNat 25111956568847854894294993758900158),
                   (Positive.ofNat 30628753411940519968904522621833150),
                   (Positive.ofNat 29979716304623666515338210580680638),
                   (Positive.ofNat 427163956635663619511819329762952789151678),
                   (Positive.ofNat 90521582509840790022117316103474565054),
                   (Positive.ofNat 22100011719470881481773947964936126),
                   (Positive.ofNat 21435762804951289275389675485319102)]
  prog_main := (Positive.ofNat 22880918)

end Quadrature.LTL.Imported
