opam-version: "2.0"
compiler: [
  "base-bigarray.base"
  "base-threads.base"
  "base-unix.base"
  "ocaml.4.13.1"
  "ocaml-config.2"
  "ocaml-option-flambda.1"
  "ocaml-variants.4.13.1+options"
]
roots: [
  "coq.9.0.1"
  "coq-bignums.9.0.0+rocq9.0"
  "coq-compcert.3.17"
  "coq-coquelicot.3.4.5"
  "coq-interval.4.11.4"
  "coq-mathcomp-algebra.2.5.0"
  "coq-mathcomp-algebra-tactics.1.2.7"
  "coq-mathcomp-analysis.1.15.0"
  "coq-mathcomp-finmap.2.2.2"
  "coq-mathcomp-reals-stdlib.1.15.0"
  "coq-mathcomp-ssreflect.2.5.0"
  "coq-vcfloat.2.4.1"
  "coq-vst.2.16"
  "coq-vst-lib.2.15.1"
  "dune.3.17.2"
  "num.1.5-1"
  "ocaml-option-flambda.1"
  "ocaml-variants.4.13.1+options"
  "ocamlfind.1.9.6"
  "opam-depext.1.2.3"
  "zarith.1.14"
]
installed: [
  "atd.3.0.1"
  "atdgen.3.0.1"
  "atdgen-runtime.3.0.1"
  "atdts.3.0.1"
  "base.v0.15.1"
  "base-bigarray.base"
  "base-threads.base"
  "base-unix.base"
  "biniou.1.2.2"
  "camlp-streams.5.0.1"
  "cmdliner.2.1.0"
  "conf-g++.1.0"
  "conf-gmp.5"
  "conf-linux-libc-dev.0"
  "conf-pkg-config.4"
  "coq.9.0.1"
  "coq-bignums.9.0.0+rocq9.0"
  "coq-compcert.3.17"
  "coq-coquelicot.3.4.5"
  "coq-core.9.0.1"
  "coq-elpi.3.5.1"
  "coq-flocq.4.2.2"
  "coq-hierarchy-builder.1.10.3"
  "coq-interval.4.11.4"
  "coq-mathcomp-algebra.2.5.0"
  "coq-mathcomp-algebra-tactics.1.2.7"
  "coq-mathcomp-analysis.1.15.0"
  "coq-mathcomp-bigenough.1.0.3"
  "coq-mathcomp-classical.1.15.0"
  "coq-mathcomp-field.2.5.0"
  "coq-mathcomp-fingroup.2.5.0"
  "coq-mathcomp-finmap.2.2.2"
  "coq-mathcomp-reals.1.15.0"
  "coq-mathcomp-reals-stdlib.1.15.0"
  "coq-mathcomp-solvable.2.5.0"
  "coq-mathcomp-ssreflect.2.5.0"
  "coq-mathcomp-zify.1.7.0+2.4+9.0"
  "coq-menhirlib.20260209"
  "coq-stdlib.9.0.0"
  "coq-vcfloat.2.4.1"
  "coq-vst.2.16"
  "coq-vst-lib.2.15.1"
  "coq-vst-zlist.2.13"
  "coqide-server.9.0.1"
  "cppo.1.8.0"
  "csexp.1.5.2"
  "dune.3.17.2"
  "dune-configurator.3.18.2"
  "easy-format.1.3.4"
  "elpi.3.7.3"
  "menhir.20260209"
  "menhirCST.20260209"
  "menhirGLR.20260209"
  "menhirLib.20260209"
  "menhirSdk.20260209"
  "num.1.5-1"
  "ocaml.4.13.1"
  "ocaml-compiler-libs.v0.12.4"
  "ocaml-config.2"
  "ocaml-option-flambda.1"
  "ocaml-variants.4.13.1+options"
  "ocamlfind.1.9.6"
  "opam-depext.1.2.3"
  "parsexp.v0.15.0"
  "ppx_compare.v0.15.0"
  "ppx_derivers.1.2.1"
  "ppx_deriving.6.0.3"
  "ppx_deriving_yojson.3.9.1"
  "ppx_hash.v0.15.0"
  "ppx_import.1.12.0"
  "ppx_optcomp.v0.15.0"
  "ppx_sexp_conv.v0.15.1"
  "ppxlib.0.35.0"
  "re.1.14.0"
  "rocq-bignums.9.0.0+rocq9.0"
  "rocq-core.9.0.1"
  "rocq-elpi.3.5.1"
  "rocq-hierarchy-builder.1.10.3"
  "rocq-mathcomp-algebra.2.5.0"
  "rocq-mathcomp-boot.2.5.0"
  "rocq-mathcomp-field.2.5.0"
  "rocq-mathcomp-fingroup.2.5.0"
  "rocq-mathcomp-finmap.2.2.2"
  "rocq-mathcomp-order.2.5.0"
  "rocq-mathcomp-solvable.2.5.0"
  "rocq-mathcomp-ssreflect.2.5.0"
  "rocq-mathcomp-zify.1.7.0+2.4+9.0"
  "rocq-runtime.9.0.1"
  "rocq-stdlib.9.0.0"
  "sexplib.v0.15.1"
  "sexplib0.v0.15.1"
  "stdio.v0.15.0"
  "stdlib-shims.0.3.0"
  "yojson.3.0.0"
  "zarith.1.14"
]
pinned: ["dune.3.17.2" "num.1.5-1" "ocamlfind.1.9.6" "zarith.1.14"]
