import Quadrature.Legendre.RootCertificates

/-!
# Certified Legendre roots for orders five through ten

Generated by `scripts/generate-legendre-root-data.py`, which proposes the brackets by
rational bisection. For each order `n` from five to ten the file lists the monic Legendre
polynomial of degree `n` as a sparse rational polynomial, `n` certified root brackets of
width at most `2⁻⁹⁹` in ascending order, and six lemmas: validity of each bracket,
disjointness and order, containment in `(-1, 1)`, monicity, degree, and vanishing of the
moments below `n`. Validity, order, containment and moments are checked by kernel evaluation
(`decide +kernel`), monicity and degree by `norm_num`. For order five these are
`five_valid`, `five_ordered`, `five_interior`, `five_monic`, `five_degree` and
`five_moments`, and they feed `RootCertificates.rule` to give `fiveGaussian : Rule 5`, with
`five_nodes_mem` placing each node in its bracket and `five_nodal_eq` identifying the nodal
polynomial with `monicPolynomial 5`. Orders six to ten follow the same pattern, so the
individual lemmas carry no docstrings.
-/

namespace Quadrature.Legendre.RootData

open Polynomial
open PDE.Symbolic.Polynomial
open PDE.Symbolic.Polynomial.RealRoot
open RootCertificates

/-- Monic degree-5 polynomial, identified by its checked vanishing moments. -/
def fivePolynomial : Sparse.Univariate :=
  [(1, fun _ => 5),
   (-10 / 9, fun _ => 3),
   (5 / 21, fun _ => 1)]

/-- Disjoint brackets in ascending node order, each of width at most `2⁻⁹⁹`. -/
def fiveBrackets : Fin 5 → RootBracket :=
  ![
    ⟨⟨-1148719425618871857555263390794 / 1267650600228229401496703205376,
      -1148719425618871857555263390793 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨-682590944159949762131801328079 / 1267650600228229401496703205376,
      -682590944159949762131801328078 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨-1 / 1267650600228229401496703205376,
      1 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨682590944159949762131801328078 / 1267650600228229401496703205376,
      682590944159949762131801328079 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨1148719425618871857555263390793 / 1267650600228229401496703205376,
      1148719425618871857555263390794 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩]

-- Kernel evaluation of the `valid` check for each of the five brackets of `fivePolynomial`.
set_option maxRecDepth 10000 in
set_option maxHeartbeats 8000000 in
theorem five_valid (i : Fin 5) :
    (fiveBrackets i).valid fivePolynomial = true := by
  fin_cases i <;> decide +kernel

theorem five_ordered : ∀ i j : Fin 5, i < j →
    (fiveBrackets i).interval.hi < (fiveBrackets j).interval.lo := by
  decide +kernel

theorem five_interior : ∀ i : Fin 5,
    -1 < (fiveBrackets i).interval.lo ∧ (fiveBrackets i).interval.hi < 1 := by
  decide +kernel

theorem five_monic : (realPolynomial fivePolynomial).Monic := by
  norm_num [realPolynomial, fivePolynomial]
  monicity!

theorem five_degree : (realPolynomial fivePolynomial).natDegree = 5 := by
  norm_num [realPolynomial, fivePolynomial]
  compute_degree!

theorem five_moments (k : ℕ) (hk : k < 5) :
    shiftedMoment fivePolynomial k = 0 := by
  interval_cases k <;> decide +kernel

/-- Positive Gaussian rule with the certified roots in stored-table order. -/
noncomputable def fiveGaussian : Rule 5 :=
  rule (by decide) fivePolynomial fiveBrackets five_valid
    five_ordered five_interior five_monic five_degree five_moments

theorem five_nodes_mem (i : Fin 5) :
    (fiveBrackets i).interval.memReal (fiveGaussian.nodes i) :=
  nodes_mem fivePolynomial fiveBrackets five_valid i

theorem five_nodal_eq :
    Lagrange.nodal Finset.univ fiveGaussian.nodes = monicPolynomial 5 :=
  fiveGaussian.nodal_eq_integralOrthogonalPolynomial (by norm_num)
    (by intro x hx; norm_num)

/-- Monic degree-6 polynomial, identified by its checked vanishing moments. -/
def sixPolynomial : Sparse.Univariate :=
  [(1, fun _ => 6),
   (-15 / 11, fun _ => 4),
   (5 / 11, fun _ => 2),
   (-5 / 231, fun _ => 0)]

/-- Disjoint brackets in ascending node order, each of width at most `2⁻⁹⁹`. -/
def sixBrackets : Fin 6 → RootBracket :=
  ![
    ⟨⟨-1182045539374151149087987729175 / 1267650600228229401496703205376,
      -1182045539374151149087987729174 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨-838182475630499513038779271810 / 1267650600228229401496703205376,
      -838182475630499513038779271809 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨-302485754464336125168999167004 / 1267650600228229401496703205376,
      -302485754464336125168999167003 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨302485754464336125168999167003 / 1267650600228229401496703205376,
      302485754464336125168999167004 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨838182475630499513038779271809 / 1267650600228229401496703205376,
      838182475630499513038779271810 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨1182045539374151149087987729174 / 1267650600228229401496703205376,
      1182045539374151149087987729175 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩]

-- Kernel evaluation of the `valid` check for each of the six brackets of `sixPolynomial`.
set_option maxRecDepth 10000 in
set_option maxHeartbeats 8000000 in
theorem six_valid (i : Fin 6) :
    (sixBrackets i).valid sixPolynomial = true := by
  fin_cases i <;> decide +kernel

theorem six_ordered : ∀ i j : Fin 6, i < j →
    (sixBrackets i).interval.hi < (sixBrackets j).interval.lo := by
  decide +kernel

theorem six_interior : ∀ i : Fin 6,
    -1 < (sixBrackets i).interval.lo ∧ (sixBrackets i).interval.hi < 1 := by
  decide +kernel

theorem six_monic : (realPolynomial sixPolynomial).Monic := by
  norm_num [realPolynomial, sixPolynomial]
  monicity!

theorem six_degree : (realPolynomial sixPolynomial).natDegree = 6 := by
  norm_num [realPolynomial, sixPolynomial]
  compute_degree!

theorem six_moments (k : ℕ) (hk : k < 6) :
    shiftedMoment sixPolynomial k = 0 := by
  interval_cases k <;> decide +kernel

/-- Positive Gaussian rule with the certified roots in stored-table order. -/
noncomputable def sixGaussian : Rule 6 :=
  rule (by decide) sixPolynomial sixBrackets six_valid
    six_ordered six_interior six_monic six_degree six_moments

theorem six_nodes_mem (i : Fin 6) :
    (sixBrackets i).interval.memReal (sixGaussian.nodes i) :=
  nodes_mem sixPolynomial sixBrackets six_valid i

theorem six_nodal_eq :
    Lagrange.nodal Finset.univ sixGaussian.nodes = monicPolynomial 6 :=
  sixGaussian.nodal_eq_integralOrthogonalPolynomial (by norm_num)
    (by intro x hx; norm_num)

/-- Monic degree-7 polynomial, identified by its checked vanishing moments. -/
def sevenPolynomial : Sparse.Univariate :=
  [(1, fun _ => 7),
   (-21 / 13, fun _ => 5),
   (105 / 143, fun _ => 3),
   (-35 / 429, fun _ => 1)]

/-- Disjoint brackets in ascending node order, each of width at most `2⁻⁹⁹`. -/
def sevenBrackets : Fin 7 → RootBracket :=
  ![
    ⟨⟨-1203137214762659580060512295746 / 1267650600228229401496703205376,
      -1203137214762659580060512295745 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨-940002452513022940010582633915 / 1267650600228229401496703205376,
      -940002452513022940010582633914 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨-514469849743274141066662030151 / 1267650600228229401496703205376,
      -514469849743274141066662030150 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨-1 / 1267650600228229401496703205376,
      1 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨514469849743274141066662030150 / 1267650600228229401496703205376,
      514469849743274141066662030151 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨940002452513022940010582633914 / 1267650600228229401496703205376,
      940002452513022940010582633915 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨1203137214762659580060512295745 / 1267650600228229401496703205376,
      1203137214762659580060512295746 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩]

-- Kernel evaluation of the `valid` check for each of the seven brackets of `sevenPolynomial`.
set_option maxRecDepth 10000 in
set_option maxHeartbeats 8000000 in
theorem seven_valid (i : Fin 7) :
    (sevenBrackets i).valid sevenPolynomial = true := by
  fin_cases i <;> decide +kernel

theorem seven_ordered : ∀ i j : Fin 7, i < j →
    (sevenBrackets i).interval.hi < (sevenBrackets j).interval.lo := by
  decide +kernel

theorem seven_interior : ∀ i : Fin 7,
    -1 < (sevenBrackets i).interval.lo ∧ (sevenBrackets i).interval.hi < 1 := by
  decide +kernel

theorem seven_monic : (realPolynomial sevenPolynomial).Monic := by
  norm_num [realPolynomial, sevenPolynomial]
  monicity!

theorem seven_degree : (realPolynomial sevenPolynomial).natDegree = 7 := by
  norm_num [realPolynomial, sevenPolynomial]
  compute_degree!

theorem seven_moments (k : ℕ) (hk : k < 7) :
    shiftedMoment sevenPolynomial k = 0 := by
  interval_cases k <;> decide +kernel

/-- Positive Gaussian rule with the certified roots in stored-table order. -/
noncomputable def sevenGaussian : Rule 7 :=
  rule (by decide) sevenPolynomial sevenBrackets seven_valid
    seven_ordered seven_interior seven_monic seven_degree seven_moments

theorem seven_nodes_mem (i : Fin 7) :
    (sevenBrackets i).interval.memReal (sevenGaussian.nodes i) :=
  nodes_mem sevenPolynomial sevenBrackets seven_valid i

theorem seven_nodal_eq :
    Lagrange.nodal Finset.univ sevenGaussian.nodes = monicPolynomial 7 :=
  sevenGaussian.nodal_eq_integralOrthogonalPolynomial (by norm_num)
    (by intro x hx; norm_num)

/-- Monic degree-8 polynomial, identified by its checked vanishing moments. -/
def eightPolynomial : Sparse.Univariate :=
  [(1, fun _ => 8),
   (-28 / 15, fun _ => 6),
   (14 / 13, fun _ => 4),
   (-28 / 143, fun _ => 2),
   (7 / 1287, fun _ => 0)]

/-- Disjoint brackets in ascending node order, each of width at most `2⁻⁹⁹`. -/
def eightBrackets : Fin 8 → RootBracket :=
  ![
    ⟨⟨-1217312012982182081827192647124 / 1267650600228229401496703205376,
      -1217312012982182081827192647123 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨-1009894738275093097951875955468 / 1267650600228229401496703205376,
      -1009894738275093097951875955467 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨-666191474869822336051572253435 / 1267650600228229401496703205376,
      -666191474869822336051572253434 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨-232531034662261151291953770541 / 1267650600228229401496703205376,
      -232531034662261151291953770540 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨232531034662261151291953770540 / 1267650600228229401496703205376,
      232531034662261151291953770541 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨666191474869822336051572253434 / 1267650600228229401496703205376,
      666191474869822336051572253435 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨1009894738275093097951875955467 / 1267650600228229401496703205376,
      1009894738275093097951875955468 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨1217312012982182081827192647123 / 1267650600228229401496703205376,
      1217312012982182081827192647124 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩]

-- Kernel evaluation of the `valid` check for each of the eight brackets of `eightPolynomial`.
set_option maxRecDepth 10000 in
set_option maxHeartbeats 8000000 in
theorem eight_valid (i : Fin 8) :
    (eightBrackets i).valid eightPolynomial = true := by
  fin_cases i <;> decide +kernel

theorem eight_ordered : ∀ i j : Fin 8, i < j →
    (eightBrackets i).interval.hi < (eightBrackets j).interval.lo := by
  decide +kernel

theorem eight_interior : ∀ i : Fin 8,
    -1 < (eightBrackets i).interval.lo ∧ (eightBrackets i).interval.hi < 1 := by
  decide +kernel

theorem eight_monic : (realPolynomial eightPolynomial).Monic := by
  norm_num [realPolynomial, eightPolynomial]
  monicity!

theorem eight_degree : (realPolynomial eightPolynomial).natDegree = 8 := by
  norm_num [realPolynomial, eightPolynomial]
  compute_degree!

theorem eight_moments (k : ℕ) (hk : k < 8) :
    shiftedMoment eightPolynomial k = 0 := by
  interval_cases k <;> decide +kernel

/-- Positive Gaussian rule with the certified roots in stored-table order. -/
noncomputable def eightGaussian : Rule 8 :=
  rule (by decide) eightPolynomial eightBrackets eight_valid
    eight_ordered eight_interior eight_monic eight_degree eight_moments

theorem eight_nodes_mem (i : Fin 8) :
    (eightBrackets i).interval.memReal (eightGaussian.nodes i) :=
  nodes_mem eightPolynomial eightBrackets eight_valid i

theorem eight_nodal_eq :
    Lagrange.nodal Finset.univ eightGaussian.nodes = monicPolynomial 8 :=
  eightGaussian.nodal_eq_integralOrthogonalPolynomial (by norm_num)
    (by intro x hx; norm_num)

/-- Monic degree-9 polynomial, identified by its checked vanishing moments. -/
def ninePolynomial : Sparse.Univariate :=
  [(1, fun _ => 9),
   (-36 / 17, fun _ => 7),
   (126 / 85, fun _ => 5),
   (-84 / 221, fun _ => 3),
   (63 / 2431, fun _ => 1)]

/-- Disjoint brackets in ascending node order, each of width at most `2⁻⁹⁹`. -/
def nineBrackets : Fin 9 → RootBracket :=
  ![
    ⟨⟨-1227288908728948549371452406653 / 1267650600228229401496703205376,
      -1227288908728948549371452406652 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨-1059795335012081139882932879986 / 1267650600228229401496703205376,
      -1059795335012081139882932879985 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨-777540664825752432483045640826 / 1267650600228229401496703205376,
      -777540664825752432483045640825 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨-411040046803896595937768545138 / 1267650600228229401496703205376,
      -411040046803896595937768545137 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨-1 / 1267650600228229401496703205376,
      1 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨411040046803896595937768545137 / 1267650600228229401496703205376,
      411040046803896595937768545138 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨777540664825752432483045640825 / 1267650600228229401496703205376,
      777540664825752432483045640826 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨1059795335012081139882932879985 / 1267650600228229401496703205376,
      1059795335012081139882932879986 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨1227288908728948549371452406652 / 1267650600228229401496703205376,
      1227288908728948549371452406653 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩]

-- Kernel evaluation of the `valid` check for each of the nine brackets of `ninePolynomial`.
set_option maxRecDepth 10000 in
set_option maxHeartbeats 8000000 in
theorem nine_valid (i : Fin 9) :
    (nineBrackets i).valid ninePolynomial = true := by
  fin_cases i <;> decide +kernel

theorem nine_ordered : ∀ i j : Fin 9, i < j →
    (nineBrackets i).interval.hi < (nineBrackets j).interval.lo := by
  decide +kernel

theorem nine_interior : ∀ i : Fin 9,
    -1 < (nineBrackets i).interval.lo ∧ (nineBrackets i).interval.hi < 1 := by
  decide +kernel

theorem nine_monic : (realPolynomial ninePolynomial).Monic := by
  norm_num [realPolynomial, ninePolynomial]
  monicity!

theorem nine_degree : (realPolynomial ninePolynomial).natDegree = 9 := by
  norm_num [realPolynomial, ninePolynomial]
  compute_degree!

theorem nine_moments (k : ℕ) (hk : k < 9) :
    shiftedMoment ninePolynomial k = 0 := by
  interval_cases k <;> decide +kernel

/-- Positive Gaussian rule with the certified roots in stored-table order. -/
noncomputable def nineGaussian : Rule 9 :=
  rule (by decide) ninePolynomial nineBrackets nine_valid
    nine_ordered nine_interior nine_monic nine_degree nine_moments

theorem nine_nodes_mem (i : Fin 9) :
    (nineBrackets i).interval.memReal (nineGaussian.nodes i) :=
  nodes_mem ninePolynomial nineBrackets nine_valid i

theorem nine_nodal_eq :
    Lagrange.nodal Finset.univ nineGaussian.nodes = monicPolynomial 9 :=
  nineGaussian.nodal_eq_integralOrthogonalPolynomial (by norm_num)
    (by intro x hx; norm_num)

/-- Monic degree-10 polynomial, identified by its checked vanishing moments. -/
def tenPolynomial : Sparse.Univariate :=
  [(1, fun _ => 10),
   (-45 / 19, fun _ => 8),
   (630 / 323, fun _ => 6),
   (-210 / 323, fun _ => 4),
   (315 / 4199, fun _ => 2),
   (-63 / 46189, fun _ => 0)]

/-- Disjoint brackets in ascending node order, each of width at most `2⁻⁹⁹`. -/
def tenBrackets : Fin 10 → RootBracket :=
  ![
    ⟨⟨-1234573195440983945377069141036 / 1267650600228229401496703205376,
      -1234573195440983945377069141035 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨-1096598096018744122856398841609 / 1267650600228229401496703205376,
      -1096598096018744122856398841608 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨-861253947055060507121608664441 / 1267650600228229401496703205376,
      -861253947055060507121608664440 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨-549393931504090250378549836810 / 1267650600228229401496703205376,
      -549393931504090250378549836809 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨-188720645168645694740871213862 / 1267650600228229401496703205376,
      -188720645168645694740871213861 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨188720645168645694740871213861 / 1267650600228229401496703205376,
      188720645168645694740871213862 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨549393931504090250378549836809 / 1267650600228229401496703205376,
      549393931504090250378549836810 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨861253947055060507121608664440 / 1267650600228229401496703205376,
      861253947055060507121608664441 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩,
    ⟨⟨1096598096018744122856398841608 / 1267650600228229401496703205376,
      1096598096018744122856398841609 / 1267650600228229401496703205376,
      by norm_num⟩, .decreasing⟩,
    ⟨⟨1234573195440983945377069141035 / 1267650600228229401496703205376,
      1234573195440983945377069141036 / 1267650600228229401496703205376,
      by norm_num⟩, .increasing⟩]

-- Kernel evaluation of the `valid` check for each of the ten brackets of `tenPolynomial`.
set_option maxRecDepth 10000 in
set_option maxHeartbeats 8000000 in
theorem ten_valid (i : Fin 10) :
    (tenBrackets i).valid tenPolynomial = true := by
  fin_cases i <;> decide +kernel

theorem ten_ordered : ∀ i j : Fin 10, i < j →
    (tenBrackets i).interval.hi < (tenBrackets j).interval.lo := by
  decide +kernel

theorem ten_interior : ∀ i : Fin 10,
    -1 < (tenBrackets i).interval.lo ∧ (tenBrackets i).interval.hi < 1 := by
  decide +kernel

theorem ten_monic : (realPolynomial tenPolynomial).Monic := by
  norm_num [realPolynomial, tenPolynomial]
  monicity!

theorem ten_degree : (realPolynomial tenPolynomial).natDegree = 10 := by
  norm_num [realPolynomial, tenPolynomial]
  compute_degree!

theorem ten_moments (k : ℕ) (hk : k < 10) :
    shiftedMoment tenPolynomial k = 0 := by
  interval_cases k <;> decide +kernel

/-- Positive Gaussian rule with the certified roots in stored-table order. -/
noncomputable def tenGaussian : Rule 10 :=
  rule (by decide) tenPolynomial tenBrackets ten_valid
    ten_ordered ten_interior ten_monic ten_degree ten_moments

theorem ten_nodes_mem (i : Fin 10) :
    (tenBrackets i).interval.memReal (tenGaussian.nodes i) :=
  nodes_mem tenPolynomial tenBrackets ten_valid i

theorem ten_nodal_eq :
    Lagrange.nodal Finset.univ tenGaussian.nodes = monicPolynomial 10 :=
  tenGaussian.nodal_eq_integralOrthogonalPolynomial (by norm_num)
    (by intro x hx; norm_num)

end Quadrature.Legendre.RootData
