import Quadrature.Clight.StoredAccuracy
import Quadrature.Compiler.Asm.Imported
import Quadrature.Compiler.Asm.ProgramExecution

/-!
# Finite executions of the ten imported assembly programs

Certified executions of the ten programs `Imported.program n` (n = 1..10 nodes),
generated by `scripts/import-asm.py` from CompCert's assembly output for the
internal-cosine quadrature application. Read `execution_checked` first: kernel evaluation
of `executeProgram` follows `PC` through calls and saved return addresses in concrete
memory frames, emits one binary64 annotation, and exits 0. The programs are the formal
assembly before instruction expansion and native encoding.

Vocabulary and scope: `Quadrature.Compiler.Execution.Run`.
-/

namespace Quadrature.Asm.StoredPrograms

open CC Quadrature.Binary64
open FloatLib.Floats.Formats.BinaryInterchange

/-- The trace of one `quadrature-result` annotation carrying the binary64 `value`. -/
def resultTrace (value : Value) : Trace :=
  [.Event_annot "quadrature-result" [.EVfloat value]]

/-- These assembly runs take 153 semantic transitions per node and 37 fixed transitions. -/
def stepCount (n : Nat) : Nat := 153 * n + 37

/-- Whether every instruction of every internal function of `program` has an execution rule. -/
def instructionsSupported (program : Program) : Bool :=
  program.prog_defs.all fun definition =>
    match definition.2 with
    | .Gfun (.Internal function) => function.fn_code.all Instruction.supported
    | _ => true

-- Kernel evaluation of `instructionsSupported` on each of the ten programs.
set_option maxRecDepth 100000 in
/-- For n = 1..10, every instruction of every internal function of the n-node program has an
execution rule, by kernel evaluation. -/
theorem instructions_supported (n : Nat) (hlo : 1 ≤ n) (hhi : n ≤ 10) :
    instructionsSupported (Imported.program n) = true := by
  interval_cases n <;> decide +kernel

-- Kernel evaluation of `executeProgram` on each of the ten programs for `stepCount n` steps.
set_option maxRecDepth 100000 in
set_option maxHeartbeats 16000000 in
/-- Kernel evaluation checks the initialized program and every concrete frame access. -/
theorem execution_checked (n : Nat) (hlo : 1 ≤ n) (hhi : n ≤ 10) :
    executeProgram annotatedExternalCall
      (Imported.program n) (stepCount n) =
      some (resultTrace (Model.ofNatBits (Clight.StoredPolynomial.resultBits n)),
        Integers.Int.zero) := by
  interval_cases n <;> decide +kernel

/-- A complete semantic execution exists with ordinary assembly calls and returns. -/
theorem execution [ExternalCalls] (n : Nat) (hlo : 1 ≤ n) (hhi : n ≤ 10) :
    ∃ start finish, InitialState (Imported.program n) start ∧
      Steps (Imported.program n).globalenv start
        (resultTrace (Clight.StoredPolynomial.result n)) finish ∧
      FinalState finish Integers.Int.zero := by
  rw [Clight.StoredPolynomial.result_value n hlo hhi]
  exact execute_program_sound annotated_external_executor_sound (execution_checked n hlo hhi)

/-- The value emitted by this execution satisfies the fixed-integrand accuracy bound. -/
theorem execution_accuracy [ExternalCalls] (n : Nat) (hlo : 1 ≤ n) (hhi : n ≤ 10) :
    ∃ value : Value, ∃ start finish,
      InitialState (Imported.program n) start ∧
      Steps (Imported.program n).globalenv
        start (resultTrace value) finish ∧
      FinalState finish Integers.Int.zero ∧
      Model.isFinite value = true ∧
      |Model.toReal value - ∫ x in (-1 : ℝ)..1, Example.integrand x| ≤
        Clight.StoredPolynomial.errorBound n := by
  obtain ⟨start, finish, hinit, hrun, hfinal⟩ := execution n hlo hhi
  exact ⟨Clight.StoredPolynomial.result n, start, finish, hinit, hrun, hfinal,
    Clight.StoredPolynomial.integral_accuracy n hlo hhi⟩

end Quadrature.Asm.StoredPrograms
