import Quadrature.Compiler.Cminor.Syntax

/-!
# Formal x86 assembly syntax

Assembly syntax after CompCert's `x86/Asm.v`, generated by `scripts/generate-asm-syntax.py`
from that file. Read `Instruction` first: the complete instruction vocabulary, including
pseudo-instructions and forms introduced only during assembly expansion. `Asm.Instructions`
gives execution rules for the fragment the ten programs use.

Vocabulary and scope: `Quadrature.Compiler.Execution.Run`.
-/

namespace Quadrature.Asm

open CC

/-- Code labels are positive numbers, as in CompCert. -/
abbrev Label := Positive

/-- The sixteen 64-bit integer registers. -/
inductive IReg where
  | RAX | RBX | RCX | RDX | RSI | RDI | RBP | RSP
  | R8 | R9 | R10 | R11 | R12 | R13 | R14 | R15
  deriving DecidableEq

/-- The sixteen SSE floating-point registers. -/
inductive FReg where
  | XMM0 | XMM1 | XMM2 | XMM3 | XMM4 | XMM5 | XMM6 | XMM7
  | XMM8 | XMM9 | XMM10 | XMM11 | XMM12 | XMM13 | XMM14 | XMM15
  deriving DecidableEq

/-- The condition flags: zero, carry, parity, sign, and overflow. -/
inductive CRBit where
  | ZF | CF | PF | SF | OF
  deriving DecidableEq

/-- The twelve conditions tested by `Pjcc`, `Pcmov`, and `Psetcc`. -/
inductive TestCond where
  | Cond_e | Cond_ne | Cond_b | Cond_be | Cond_ae | Cond_a | Cond_l | Cond_le
  | Cond_ge | Cond_g | Cond_p | Cond_np
  deriving DecidableEq

/-- All processor registers: the program counter, integer and float registers, the x87 top
of stack, the flags, and the pseudo-register `RA` holding the return address. -/
inductive PReg where
  | PC
  | IR (register : IReg)
  | FR (register : FReg)
  | ST0
  | CR (bit : CRBit)
  | RA
  deriving DecidableEq

/-- An x86 addressing mode: optional base, optional scaled index, and a constant or symbol
displacement. -/
inductive AddrMode where
  | Addrmode (base : Option IReg) (ofs : Option (IReg × Int))
      (const : Sum Int (Ident × Integers.Ptrofs))
  deriving DecidableEq

/-- Builtin arguments over processor registers, constants, and stack or global accesses. -/
inductive BuiltinArg where
  | BA (register : PReg)
  | BA_int (value : Integers.Int)
  | BA_long (value : Integers.Int64)
  | BA_float (value : Floats.Float)
  | BA_single (value : Floats.Float32)
  | BA_loadstack (chunk : Chunk) (offset : Integers.Ptrofs)
  | BA_addrstack (offset : Integers.Ptrofs)
  | BA_loadglobal (chunk : Chunk) (name : Ident) (offset : Integers.Ptrofs)
  | BA_addrglobal (name : Ident) (offset : Integers.Ptrofs)
  | BA_splitlong (hi lo : BuiltinArg)
  | BA_addptr (left right : BuiltinArg)
  deriving DecidableEq

/-- Builtin result registers, or a split pair for 64-bit results. -/
inductive BuiltinRes where
  | BR (register : PReg)
  | BR_none
  | BR_splitlong (hi lo : BuiltinRes)
  deriving DecidableEq

/-- The full x86 instruction vocabulary of `x86/Asm.v`, with pseudo-instructions such as
`Pallocframe`, `Pfreeframe`, `Plabel`, and `Pbuiltin`. -/
inductive Instruction where
  | Pmov_rr (rd : IReg) (r1 : IReg)
  | Pmovl_ri (rd : IReg) (n : Integers.Int)
  | Pmovq_ri (rd : IReg) (n : Integers.Int64)
  | Pmov_rs (rd : IReg) (id : Ident)
  | Pmovl_rm (rd : IReg) (a : AddrMode)
  | Pmovq_rm (rd : IReg) (a : AddrMode)
  | Pmovl_mr (a : AddrMode) (rs : IReg)
  | Pmovq_mr (a : AddrMode) (rs : IReg)
  | Pmovsd_ff (rd : FReg) (r1 : FReg)
  | Pmovsd_fi (rd : FReg) (n : Floats.Float)
  | Pmovsd_fm (rd : FReg) (a : AddrMode)
  | Pmovsd_mf (a : AddrMode) (r1 : FReg)
  | Pmovss_fi (rd : FReg) (n : Floats.Float32)
  | Pmovss_fm (rd : FReg) (a : AddrMode)
  | Pmovss_mf (a : AddrMode) (r1 : FReg)
  | Pfldl_m (a : AddrMode)
  | Pfstpl_m (a : AddrMode)
  | Pflds_m (a : AddrMode)
  | Pfstps_m (a : AddrMode)
  | Pmovb_mr (a : AddrMode) (rs : IReg)
  | Pmovw_mr (a : AddrMode) (rs : IReg)
  | Pmovzb_rr (rd : IReg) (rs : IReg)
  | Pmovzb_rm (rd : IReg) (a : AddrMode)
  | Pmovsb_rr (rd : IReg) (rs : IReg)
  | Pmovsb_rm (rd : IReg) (a : AddrMode)
  | Pmovzw_rr (rd : IReg) (rs : IReg)
  | Pmovzw_rm (rd : IReg) (a : AddrMode)
  | Pmovsw_rr (rd : IReg) (rs : IReg)
  | Pmovsw_rm (rd : IReg) (a : AddrMode)
  | Pmovzl_rr (rd : IReg) (rs : IReg)
  | Pmovsl_rr (rd : IReg) (rs : IReg)
  | Pmovls_rr (rd : IReg)
  | Pcvtsd2ss_ff (rd : FReg) (r1 : FReg)
  | Pcvtss2sd_ff (rd : FReg) (r1 : FReg)
  | Pcvttsd2si_rf (rd : IReg) (r1 : FReg)
  | Pcvtsi2sd_fr (rd : FReg) (r1 : IReg)
  | Pcvttss2si_rf (rd : IReg) (r1 : FReg)
  | Pcvtsi2ss_fr (rd : FReg) (r1 : IReg)
  | Pcvttsd2sl_rf (rd : IReg) (r1 : FReg)
  | Pcvtsl2sd_fr (rd : FReg) (r1 : IReg)
  | Pcvttss2sl_rf (rd : IReg) (r1 : FReg)
  | Pcvtsl2ss_fr (rd : FReg) (r1 : IReg)
  | Pleal (rd : IReg) (a : AddrMode)
  | Pleaq (rd : IReg) (a : AddrMode)
  | Pnegl (rd : IReg)
  | Pnegq (rd : IReg)
  | Paddl_ri (rd : IReg) (n : Integers.Int)
  | Paddq_ri (rd : IReg) (n : Integers.Int64)
  | Psubl_rr (rd : IReg) (r1 : IReg)
  | Psubq_rr (rd : IReg) (r1 : IReg)
  | Pimull_rr (rd : IReg) (r1 : IReg)
  | Pimulq_rr (rd : IReg) (r1 : IReg)
  | Pimull_ri (rd : IReg) (n : Integers.Int)
  | Pimulq_ri (rd : IReg) (n : Integers.Int64)
  | Pimull_r (r1 : IReg)
  | Pimulq_r (r1 : IReg)
  | Pmull_r (r1 : IReg)
  | Pmulq_r (r1 : IReg)
  | Pcltd
  | Pcqto
  | Pdivl (r1 : IReg)
  | Pdivq (r1 : IReg)
  | Pidivl (r1 : IReg)
  | Pidivq (r1 : IReg)
  | Pandl_rr (rd : IReg) (r1 : IReg)
  | Pandq_rr (rd : IReg) (r1 : IReg)
  | Pandl_ri (rd : IReg) (n : Integers.Int)
  | Pandq_ri (rd : IReg) (n : Integers.Int64)
  | Porl_rr (rd : IReg) (r1 : IReg)
  | Porq_rr (rd : IReg) (r1 : IReg)
  | Porl_ri (rd : IReg) (n : Integers.Int)
  | Porq_ri (rd : IReg) (n : Integers.Int64)
  | Pxorl_r (rd : IReg)
  | Pxorq_r (rd : IReg)
  | Pxorl_rr (rd : IReg) (r1 : IReg)
  | Pxorq_rr (rd : IReg) (r1 : IReg)
  | Pxorl_ri (rd : IReg) (n : Integers.Int)
  | Pxorq_ri (rd : IReg) (n : Integers.Int64)
  | Pnotl (rd : IReg)
  | Pnotq (rd : IReg)
  | Psall_rcl (rd : IReg)
  | Psalq_rcl (rd : IReg)
  | Psall_ri (rd : IReg) (n : Integers.Int)
  | Psalq_ri (rd : IReg) (n : Integers.Int)
  | Pshrl_rcl (rd : IReg)
  | Pshrq_rcl (rd : IReg)
  | Pshrl_ri (rd : IReg) (n : Integers.Int)
  | Pshrq_ri (rd : IReg) (n : Integers.Int)
  | Psarl_rcl (rd : IReg)
  | Psarq_rcl (rd : IReg)
  | Psarl_ri (rd : IReg) (n : Integers.Int)
  | Psarq_ri (rd : IReg) (n : Integers.Int)
  | Pshld_ri (rd : IReg) (r1 : IReg) (n : Integers.Int)
  | Prorl_ri (rd : IReg) (n : Integers.Int)
  | Prorq_ri (rd : IReg) (n : Integers.Int)
  | Pcmpl_rr (r1 : IReg) (r2 : IReg)
  | Pcmpq_rr (r1 : IReg) (r2 : IReg)
  | Pcmpl_ri (r1 : IReg) (n : Integers.Int)
  | Pcmpq_ri (r1 : IReg) (n : Integers.Int64)
  | Ptestl_rr (r1 : IReg) (r2 : IReg)
  | Ptestq_rr (r1 : IReg) (r2 : IReg)
  | Ptestl_ri (r1 : IReg) (n : Integers.Int)
  | Ptestq_ri (r1 : IReg) (n : Integers.Int64)
  | Pcmov (c : TestCond) (rd : IReg) (r1 : IReg)
  | Psetcc (c : TestCond) (rd : IReg)
  | Paddd_ff (rd : FReg) (r1 : FReg)
  | Psubd_ff (rd : FReg) (r1 : FReg)
  | Pmuld_ff (rd : FReg) (r1 : FReg)
  | Pdivd_ff (rd : FReg) (r1 : FReg)
  | Pnegd (rd : FReg)
  | Pabsd (rd : FReg)
  | Pcomisd_ff (r1 : FReg) (r2 : FReg)
  | Pxorpd_f (rd : FReg)
  | Padds_ff (rd : FReg) (r1 : FReg)
  | Psubs_ff (rd : FReg) (r1 : FReg)
  | Pmuls_ff (rd : FReg) (r1 : FReg)
  | Pdivs_ff (rd : FReg) (r1 : FReg)
  | Pnegs (rd : FReg)
  | Pabss (rd : FReg)
  | Pcomiss_ff (r1 : FReg) (r2 : FReg)
  | Pxorps_f (rd : FReg)
  | Pjmp_l (l : Label)
  | Pjmp_s (symb : Ident) (sg : Signature)
  | Pjmp_r (r : IReg) (sg : Signature)
  | Pjcc (c : TestCond) (l : Label)
  | Pjcc2 (c1 : TestCond) (c2 : TestCond) (l : Label)
  | Pjmptbl (r : IReg) (tbl : List Label)
  | Pcall_s (symb : Ident) (sg : Signature)
  | Pcall_r (r : IReg) (sg : Signature)
  | Pret
  | Pmov_rm_a (rd : IReg) (a : AddrMode)
  | Pmov_mr_a (a : AddrMode) (rs : IReg)
  | Pmovsd_fm_a (rd : FReg) (a : AddrMode)
  | Pmovsd_mf_a (a : AddrMode) (r1 : FReg)
  | Plabel (l : Label)
  | Pallocframe (sz : Int) (ofs_ra : Integers.Ptrofs) (ofs_link : Integers.Ptrofs)
  | Pfreeframe (sz : Int) (ofs_ra : Integers.Ptrofs) (ofs_link : Integers.Ptrofs)
  | Pbuiltin (ef : ExtFun) (args : List BuiltinArg) (res : BuiltinRes)
  | Padcl_ri (rd : IReg) (n : Integers.Int)
  | Padcl_rr (rd : IReg) (r2 : IReg)
  | Paddl_mi (a : AddrMode) (n : Integers.Int)
  | Paddl_rr (rd : IReg) (r2 : IReg)
  | Pbsfl (rd : IReg) (r1 : IReg)
  | Pbsfq (rd : IReg) (r1 : IReg)
  | Pbsrl (rd : IReg) (r1 : IReg)
  | Pbsrq (rd : IReg) (r1 : IReg)
  | Pbswap64 (rd : IReg)
  | Pbswap32 (rd : IReg)
  | Pbswap16 (rd : IReg)
  | Pcfi_adjust (n : Integers.Int)
  | Pfmadd132 (rd : FReg) (r2 : FReg) (r3 : FReg)
  | Pfmadd213 (rd : FReg) (r2 : FReg) (r3 : FReg)
  | Pfmadd231 (rd : FReg) (r2 : FReg) (r3 : FReg)
  | Pfmsub132 (rd : FReg) (r2 : FReg) (r3 : FReg)
  | Pfmsub213 (rd : FReg) (r2 : FReg) (r3 : FReg)
  | Pfmsub231 (rd : FReg) (r2 : FReg) (r3 : FReg)
  | Pfnmadd132 (rd : FReg) (r2 : FReg) (r3 : FReg)
  | Pfnmadd213 (rd : FReg) (r2 : FReg) (r3 : FReg)
  | Pfnmadd231 (rd : FReg) (r2 : FReg) (r3 : FReg)
  | Pfnmsub132 (rd : FReg) (r2 : FReg) (r3 : FReg)
  | Pfnmsub213 (rd : FReg) (r2 : FReg) (r3 : FReg)
  | Pfnmsub231 (rd : FReg) (r2 : FReg) (r3 : FReg)
  | Pmaxsd (rd : FReg) (r2 : FReg)
  | Pminsd (rd : FReg) (r2 : FReg)
  | Pmovb_rm (rd : IReg) (a : AddrMode)
  | Pmovq_rf (rd : IReg) (r1 : FReg)
  | Pmovsq_mr (a : AddrMode) (rs : FReg)
  | Pmovsq_rm (rd : FReg) (a : AddrMode)
  | Pmovsb
  | Pmovsw
  | Pmovw_rm (rd : IReg) (ad : AddrMode)
  | Pnop
  | Prep_movsl
  | Psbbl_rr (rd : IReg) (r2 : IReg)
  | Psqrtsd (rd : FReg) (r1 : FReg)
  | Psubl_ri (rd : IReg) (n : Integers.Int)
  | Psubq_ri (rd : IReg) (n : Integers.Int64)
  deriving DecidableEq

/-- A function body is a list of instructions, addressed by position. -/
abbrev Code := List Instruction

/-- An internal assembly function: signature and body. Frame layout lives in the
`Pallocframe` and `Pfreeframe` instructions. -/
structure Function where
  fn_sig : Signature
  fn_code : Code
  deriving DecidableEq

/-- A function definition is internal assembly code or an external function. -/
inductive Fundef where
  | Internal (function : Function)
  | External (function : ExtFun)
  deriving DecidableEq

/-- An assembly program: global definitions, public symbols, and the entry symbol. -/
structure Program where
  prog_defs : List (Ident × GlobDef Fundef Unit)
  prog_public : List Ident
  prog_main : Ident

/-- Global environments mapping symbols and blocks to assembly function definitions. -/
abbrev Genv := CC.Genv Fundef Unit

/-- The global environment holding every definition of `program`. -/
def Program.globalenv (program : Program) : Genv :=
  CC.Genv.addGlobals (CC.Genv.emptyGenv program.prog_public) program.prog_defs

/-- Allocates every global of `program` in the empty memory, `none` if an allocation fails. -/
def Program.initMem (program : Program) : Option Mem :=
  CC.Genv.allocGlobals program.globalenv Mem.empty program.prog_defs

end Quadrature.Asm
