import Mathlib.Tactic.IntervalCases
import Quadrature.Compiler.Mach.Imported
import Quadrature.Compiler.Mach.ReturnAddresses

/-!
# Imported return addresses for the ten Mach programs

The return-address table of the ten programs, generated by
`scripts/import-mach-return-addresses.py` from CompCert's Asmgen predictor. Read
`relation` first, membership in `table n`. Offsets count assembly instructions, not bytes.
`table_consistent` checks each table by kernel evaluation, so `predict_iff` makes lookup
and membership agree. `Asm.Generation.Imported.table_valid` proves every entry is a return
address of the Lean Asmgen translation, and `table_address_iff` that the two oracles agree
at every static call of the ten programs.

Vocabulary and scope: `Quadrature.Compiler.Execution.Run`.
-/

namespace Quadrature.Mach.ImportedAddresses

/-- The sixteen (global index, skip, offset) rows, shared by all ten programs. -/
def rows : List AddressRow :=
  [⟨63, 8, 10⟩,
    ⟨63, 24, 27⟩,
    ⟨64, 31, 34⟩,
    ⟨64, 35, 38⟩,
    ⟨64, 40, 43⟩,
    ⟨65, 6, 7⟩,
    ⟨65, 11, 12⟩,
    ⟨65, 41, 45⟩,
    ⟨66, 15, 17⟩,
    ⟨66, 24, 26⟩,
    ⟨69, 8, 9⟩,
    ⟨69, 38, 41⟩,
    ⟨69, 53, 56⟩,
    ⟨70, 24, 26⟩,
    ⟨71, 13, 15⟩,
    ⟨72, 3, 4⟩]

/-- The entries of `rows` in the n-node program. -/
def table (n : Nat) : List AddressEntry := addressTable (Imported.program n) rows

/-- The executable predictor for the n-node program: lookup in `table n`. -/
def predict (n : Nat) : ReturnAddressExecutor := lookupAddress (table n)

/-- The return-address oracle for the n-node program: membership in `table n`. -/
def relation (n : Nat) : ReturnAddress := tableAddress (table n)

/-- Every offset predicted for the n-node program is in its table. -/
theorem predict_sound (n : Nat) :
    ReturnAddressExecutorSound (predict n) (relation n) :=
  lookup_address_sound (table n)

-- Kernel evaluation of `consistentAddresses` on the sixteen-entry table of each program.
set_option maxRecDepth 100000 in
/-- For n = 1..10, every entry of `table n` is found by lookup, by kernel evaluation. -/
theorem table_consistent (n : Nat) (hlo : 1 ≤ n) (hhi : n ≤ 10) :
    consistentAddresses (table n) = true := by
  interval_cases n <;> decide +kernel

/-- For n = 1..10, prediction and table membership agree. -/
theorem predict_iff (n : Nat) (hlo : 1 ≤ n) (hhi : n ≤ 10)
    {function : Function} {code : Code} {offset : CC.Integers.Ptrofs} :
    predict n function code = some offset ↔ relation n function code offset :=
  lookup_address_iff (table_consistent n hlo hhi)

end Quadrature.Mach.ImportedAddresses
