import Quadrature.Clight.StoredAccuracy
import Quadrature.Compiler.Mach.ImportedReturnAddresses
import Quadrature.Compiler.Mach.ProgramExecution

/-!
# Finite executions of the ten imported Mach programs

Certified executions of the ten programs `Imported.program n` (n = 1..10 nodes),
generated by `scripts/import-mach.py` from CompCert's Mach output for the internal-cosine
quadrature application. Read `execution_checked` first: kernel evaluation of
`executeProgram` with the imported table's predictor runs each program, emits one binary64
annotation, and exits 0. The runs include frame allocation, byte-addressed stack accesses,
saved-pointer checks, and freeing. `execution` states the result for the table oracle
`ImportedAddresses.relation`, and `GeneratedReturnPrograms` restates it for the Lean
Asmgen translation's oracle.

Vocabulary and scope: `Quadrature.Compiler.Execution.Run`.
-/

namespace Quadrature.Mach.StoredPrograms

open CC Quadrature.Binary64
open FloatLib.Floats.Formats.BinaryInterchange

/-- The trace of one `quadrature-result` annotation carrying the binary64 `value`. -/
def resultTrace (value : Value) : Trace :=
  [.Event_annot "quadrature-result" [.EVfloat value]]

/-- These Mach runs take 146 semantic transitions per node and 35 fixed transitions. -/
def stepCount (n : Nat) : Nat := 146 * n + 35

-- Kernel evaluation of `executeProgram` on each of the ten programs for `stepCount n` steps.
set_option maxRecDepth 100000 in
set_option maxHeartbeats 16000000 in
/-- Kernel evaluation checks the initialized program and every concrete frame access. -/
theorem execution_checked (n : Nat) (hlo : 1 ≤ n) (hhi : n ≤ 10) :
    executeProgram (ImportedAddresses.predict n) annotatedExternalCall
      (Imported.program n) (stepCount n) =
      some (resultTrace (Model.ofNatBits (Clight.StoredPolynomial.resultBits n)),
        Integers.Int.zero) := by
  interval_cases n <;> decide +kernel

/-- A complete semantic execution exists using the imported table's address relation. -/
theorem execution [ExternalCalls] (n : Nat) (hlo : 1 ≤ n) (hhi : n ≤ 10) :
    ∃ start finish, InitialState (Imported.program n) start ∧
      Steps (ImportedAddresses.relation n) (Imported.program n).globalenv start
        (resultTrace (Clight.StoredPolynomial.result n)) finish ∧
      FinalState finish Integers.Int.zero := by
  rw [Clight.StoredPolynomial.result_value n hlo hhi]
  exact execute_program_sound (ImportedAddresses.predict_sound n)
    annotated_external_executor_sound (execution_checked n hlo hhi)

/-- The value emitted by this execution satisfies the fixed-integrand accuracy bound. -/
theorem execution_accuracy [ExternalCalls] (n : Nat) (hlo : 1 ≤ n) (hhi : n ≤ 10) :
    ∃ value : Value, ∃ start finish,
      InitialState (Imported.program n) start ∧
      Steps (ImportedAddresses.relation n) (Imported.program n).globalenv
        start (resultTrace value) finish ∧
      FinalState finish Integers.Int.zero ∧
      Model.isFinite value = true ∧
      |Model.toReal value - ∫ x in (-1 : ℝ)..1, Example.integrand x| ≤
        Clight.StoredPolynomial.errorBound n := by
  obtain ⟨start, finish, hinit, hrun, hfinal⟩ := execution n hlo hhi
  exact ⟨Clight.StoredPolynomial.result n, start, finish, hinit, hrun, hfinal,
    Clight.StoredPolynomial.integral_accuracy n hlo hhi⟩

end Quadrature.Mach.StoredPrograms
