#!/usr/bin/env python3
"""Propose rational Legendre root brackets for orders 5 to 10, leaving every claim to Lean.

Inputs: the stored binary64 node bits read from Quadrature/Clight/TableData.lean, near which the
exact bisection starts. Output: Quadrature/Legendre/RootData.lean.
Requires only the standard library. The generated file's bracket signs, strict derivative signs,
disjointness, degree, monicity, and orthogonality moments are all checked by `lake build`.
"""

from fractions import Fraction
from pathlib import Path
import re
import struct


ROOT = Path(__file__).resolve().parents[1]
DENOMINATOR = 2**100
NAMES = {5: "five", 6: "six", 7: "seven", 8: "eight", 9: "nine", 10: "ten"}


def legendre_coefficients(n: int) -> list[Fraction]:
    """Ascending coefficients, normalized to be monic."""
    previous = [Fraction(1)]
    current = [Fraction(0), Fraction(1)]
    for k in range(1, n):
        following = [Fraction(0)] * (k + 2)
        for degree, coefficient in enumerate(current):
            following[degree + 1] += Fraction(2 * k + 1, k + 1) * coefficient
        for degree, coefficient in enumerate(previous):
            following[degree] -= Fraction(k, k + 1) * coefficient
        previous, current = current, following
    return [coefficient / current[-1] for coefficient in current]


def evaluate(coefficients: list[Fraction], x: Fraction) -> Fraction:
    result = Fraction(0)
    for coefficient in reversed(coefficients):
        result = coefficient + x * result
    return result


def isolate(coefficients: list[Fraction], bits: int) -> tuple[int, int]:
    stored = Fraction(struct.unpack(">d", bits.to_bytes(8, "big"))[0])
    center = stored * DENOMINATOR
    center = center.numerator // center.denominator
    if evaluate(coefficients, Fraction(center, DENOMINATOR)) == 0:
        return center - 1, center + 1
    lower, upper = center - 2**80, center + 2**80
    low_value = evaluate(coefficients, Fraction(lower, DENOMINATOR))
    high_value = evaluate(coefficients, Fraction(upper, DENOMINATOR))
    if low_value * high_value >= 0:
        raise ValueError("Initial interval does not have opposite endpoint signs")
    while upper - lower > 1:
        middle = (lower + upper) // 2
        value = evaluate(coefficients, Fraction(middle, DENOMINATOR))
        if value == 0:
            return middle - 1, middle + 1
        if (value > 0) == (low_value > 0):
            lower, low_value = middle, value
        else:
            upper = middle
    return lower, upper


def rational(value: Fraction) -> str:
    if value.denominator == 1:
        return str(value.numerator)
    return f"{value.numerator} / {value.denominator}"


def generate() -> str:
    table = (ROOT / "Quadrature/Clight/TableData.lean").read_text()
    node_section = table.split("def nodeBits", 1)[1].split("def weightBits", 1)[0]
    bits = [int(value, 16) for value in re.findall(r"0x[0-9a-f]+", node_section)]
    lines = [
        "import Quadrature.Legendre.RootCertificates",
        "",
        "/-!",
        "# Certified Legendre roots for orders five through ten",
        "",
        "Generated by `scripts/generate-legendre-root-data.py`, which proposes the brackets by",
        "rational bisection. For each order `n` from five to ten the file lists the monic Legendre",
        "polynomial of degree `n` as a sparse rational polynomial, `n` certified root brackets of",
        "width at most `2⁻⁹⁹` in ascending order, and six lemmas: validity of each bracket,",
        "disjointness and order, containment in `(-1, 1)`, monicity, degree, and vanishing of the",
        "moments below `n`. Validity, order, containment and moments are checked by kernel evaluation",
        "(`decide +kernel`), monicity and degree by `norm_num`. For order five these are",
        "`five_valid`, `five_ordered`, `five_interior`, `five_monic`, `five_degree` and",
        "`five_moments`, and they feed `RootCertificates.rule` to give `fiveGaussian : Rule 5`, with",
        "`five_nodes_mem` placing each node in its bracket and `five_nodal_eq` identifying the nodal",
        "polynomial with `monicPolynomial 5`. Orders six to ten follow the same pattern, so the",
        "individual lemmas carry no docstrings.",
        "-/",
        "",
        "namespace Quadrature.Legendre.RootData",
        "",
        "open Polynomial",
        "open PDE.Symbolic.Polynomial",
        "open PDE.Symbolic.Polynomial.RealRoot",
        "open RootCertificates",
        "",
    ]
    for n, name in NAMES.items():
        coefficients = legendre_coefficients(n)
        start = n * (n - 1) // 2
        lines += [
            f"/-- Monic degree-{n} polynomial, identified by its checked vanishing moments. -/",
            f"def {name}Polynomial : Sparse.Univariate :=",
        ]
        terms = [
            f"({rational(coefficients[k])}, fun _ => {k})"
            for k in range(n, -1, -1)
            if coefficients[k]
        ]
        lines.append("  [" + ",\n   ".join(terms) + "]")
        lines += [
            "",
            f"/-- Disjoint brackets in ascending node order, each of width at most `2⁻⁹⁹`. -/",
            f"def {name}Brackets : Fin {n} → RootBracket :=",
            "  ![",
        ]
        for i in range(n):
            lower, upper = isolate(coefficients, bits[start + i])
            direction = "increasing" if (n - 1 - i) % 2 == 0 else "decreasing"
            lines += [
                f"    ⟨⟨{lower} / {DENOMINATOR},",
                f"      {upper} / {DENOMINATOR},",
                f"      by norm_num⟩, .{direction}⟩"
                + ("," if i + 1 < n else "]"),
            ]
        lines += [
            "",
            f"-- Kernel evaluation of the `valid` check for each of the {name} brackets of "
            f"`{name}Polynomial`.",
            "set_option maxRecDepth 10000 in",
            "set_option maxHeartbeats 8000000 in",
            f"theorem {name}_valid (i : Fin {n}) :",
            f"    ({name}Brackets i).valid {name}Polynomial = true := by",
            "  fin_cases i <;> decide +kernel",
            "",
            f"theorem {name}_ordered : ∀ i j : Fin {n}, i < j →",
            f"    ({name}Brackets i).interval.hi < ({name}Brackets j).interval.lo := by",
            "  decide +kernel",
            "",
            f"theorem {name}_interior : ∀ i : Fin {n},",
            f"    -1 < ({name}Brackets i).interval.lo ∧ ({name}Brackets i).interval.hi < 1 := by",
            "  decide +kernel",
            "",
            f"theorem {name}_monic : (realPolynomial {name}Polynomial).Monic := by",
            f"  norm_num [realPolynomial, {name}Polynomial]",
            "  monicity!",
            "",
            f"theorem {name}_degree : (realPolynomial {name}Polynomial).natDegree = {n} := by",
            f"  norm_num [realPolynomial, {name}Polynomial]",
            "  compute_degree!",
            "",
            f"theorem {name}_moments (k : ℕ) (hk : k < {n}) :",
            f"    shiftedMoment {name}Polynomial k = 0 := by",
            "  interval_cases k <;> decide +kernel",
            "",
            f"/-- Positive Gaussian rule with the certified roots in stored-table order. -/",
            f"noncomputable def {name}Gaussian : Rule {n} :=",
            f"  rule (by decide) {name}Polynomial {name}Brackets {name}_valid",
            f"    {name}_ordered {name}_interior {name}_monic {name}_degree {name}_moments",
            "",
            f"theorem {name}_nodes_mem (i : Fin {n}) :",
            f"    ({name}Brackets i).interval.memReal ({name}Gaussian.nodes i) :=",
            f"  nodes_mem {name}Polynomial {name}Brackets {name}_valid i",
            "",
            f"theorem {name}_nodal_eq :",
            f"    Lagrange.nodal Finset.univ {name}Gaussian.nodes = monicPolynomial {n} :=",
            f"  {name}Gaussian.nodal_eq_integralOrthogonalPolynomial (by norm_num)",
            "    (by intro x hx; norm_num)",
            "",
        ]
    lines += ["end Quadrature.Legendre.RootData", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    destination = ROOT / "Quadrature/Legendre/RootData.lean"
    destination.write_text(generate())
    print(f"Wrote {destination}")
