#!/usr/bin/env python3
"""Generate the complete assembly syntax vocabulary from the pinned CompCert x86/Asm.v.

Inputs: --asm-source, the Asm.v file, hash-checked against SOURCE_SHA256. Outputs, under
--output-directory: Quadrature/Compiler/Asm/Syntax.lean, compcert/ExportAsm.v, and scripts/asm-schema.json.
Requires the pinned Asm.v only. The source hash and the exhaustive constructor parser reject any
other version.
"""

import argparse
import hashlib
import json
from pathlib import Path
import re


SOURCE_SHA256 = "1fcda5fb6cca8767457477ba59ecf83c99b0259ccbd28cdccc8bc7d57ed0be05"
TYPES = {
    # Rocq type: (Lean type, renderer kind, Rocq serializer).
    "ireg": ("IReg", "auto", "ireg"),
    "freg": ("FReg", "auto", "freg"),
    "addrmode": ("AddrMode", "auto", "address"),
    "testcond": ("TestCond", "auto", "condition"),
    "int": ("Integers.Int", "int", "int"),
    "int64": ("Integers.Int64", "long", "long"),
    "float": ("Floats.Float", "float", "float"),
    "float32": ("Floats.Float32", "single", "single"),
    "ident": ("Ident", "id", "identifier"),
    "label": ("Label", "id", "identifier"),
    "signature": ("Signature", "auto", "signature"),
    "Z": ("Int", "z", "number"),
    "ptrofs": ("Integers.Ptrofs", "offset", "offset"),
    "list label": ("List Label", "list:id", "items identifier"),
    "external_function": ("ExtFun", "auto", "external"),
    "list (builtin_arg preg)": ("List BuiltinArg", "list:auto", "items builtinarg"),
    "builtin_res preg": ("BuiltinRes", "auto", "builtinres"),
}


def constructors(source, name):
    match = re.search(rf"Inductive {name}:\s*Type\s*:=\s*(.*?)\.", source, re.S)
    if not match:
        raise ValueError(f"missing inductive {name}")
    body = re.sub(r"\(\*.*?\*\)", "", match[1], flags=re.S)
    if not body.lstrip().startswith("|"):
        raise ValueError(f"unexpected constructor syntax in {name}")
    result = []
    for entry in body.split("|")[1:]:
        match = re.match(r"\s*(\w+)", entry)
        tag = match[1]
        remaining = entry[match.end():]
        fields = []
        while remaining.strip():
            binder = re.match(r"\s*\(([^():]+):\s*((?:[^()]|\([^()]*\))*)\)", remaining)
            if not binder:
                raise ValueError(f"unparsed fields of {tag}: {remaining}")
            typ = " ".join(binder[2].split())
            for field in binder[1].split():
                fields.append((field, typ))
            remaining = remaining[binder.end():]
        result.append((tag, fields))
    if len({tag for tag, _ in result}) != len(result):
        raise ValueError(f"duplicate constructor in {name}")
    return result


def generate(source_path, output_root):
    raw = source_path.read_bytes()
    if hashlib.sha256(raw).hexdigest() != SOURCE_SHA256:
        raise ValueError("Asm.v does not match the pinned source hash")
    source = raw.decode()
    enums = [(name, lean, constructors(source, name)) for name, lean in [
        ("ireg", "IReg"), ("freg", "FReg"), ("crbit", "CRBit"),
        ("testcond", "TestCond"),
    ]]
    instructions = constructors(source, "instruction")
    lean = [
        "import Quadrature.Compiler.Cminor.Syntax\n",
        "/-!\n# Formal x86 assembly syntax\n\n"
        "Assembly syntax after CompCert's `x86/Asm.v`, generated by "
        "`scripts/generate-asm-syntax.py`\n"
        "from that file. Read `Instruction` first: the complete instruction vocabulary, including\n"
        "pseudo-instructions and forms introduced only during assembly expansion. `Asm.Instructions`\n"
        "gives execution rules for the fragment the ten programs use.\n\n"
        "Vocabulary and scope: `Quadrature.Compiler.Execution.Run`.\n-/\n",
        "namespace Quadrature.Asm\n\nopen CC\n\n"
        "/-- Code labels are positive numbers, as in CompCert. -/\n"
        "abbrev Label := Positive\n",
    ]
    export = [
        "From Coq Require Import List String ZArith.\n"
        "From compcert Require Import AST Maps Integers Floats Asm.\n"
        "From CminorImport Require Import ExportCminor.\n\n"
        "Import ListNotations ExportCminor.\nLocal Open Scope string_scope.\n\n"
        "(** Generated from every constructor of the pinned x86/Asm.v. *)\n"
    ]
    atoms = []
    enum_docstrings = {
        "IReg": "The sixteen 64-bit integer registers.",
        "FReg": "The sixteen SSE floating-point registers.",
        "CRBit": "The condition flags: zero, carry, parity, sign, and overflow.",
        "TestCond": "The twelve conditions tested by `Pjcc`, `Pcmov`, and `Psetcc`.",
    }
    for rocq_name, lean_name, entries in enums:
        if any(fields for _, fields in entries):
            raise ValueError(f"unexpected non-enum {rocq_name}")
        tags = [tag for tag, _ in entries]
        atoms.extend(tags)
        lean.append(
            f"/-- {enum_docstrings[lean_name]} -/\n"
            f"inductive {lean_name} where\n"
            + "\n".join("  | " + " | ".join(tags[i:i + 8]) for i in range(0, len(tags), 8))
            + "\n  deriving DecidableEq\n"
        )
        serializer = "condition" if rocq_name == "testcond" else rocq_name
        export.append(
            f"Definition {serializer} (r : Asm.{rocq_name}) : string :=\n  match r with\n"
            + "".join(f'  | {tag} => "{tag}"\n' for tag in tags) + "  end.\n"
        )
    lean.append("""/-- All processor registers: the program counter, integer and float registers, the x87 top
of stack, the flags, and the pseudo-register `RA` holding the return address. -/
inductive PReg where
  | PC
  | IR (register : IReg)
  | FR (register : FReg)
  | ST0
  | CR (bit : CRBit)
  | RA
  deriving DecidableEq

/-- An x86 addressing mode: optional base, optional scaled index, and a constant or symbol
displacement. -/
inductive AddrMode where
  | Addrmode (base : Option IReg) (ofs : Option (IReg × Int))
      (const : Sum Int (Ident × Integers.Ptrofs))
  deriving DecidableEq

/-- Builtin arguments over processor registers, constants, and stack or global accesses. -/
inductive BuiltinArg where
  | BA (register : PReg)
  | BA_int (value : Integers.Int)
  | BA_long (value : Integers.Int64)
  | BA_float (value : Floats.Float)
  | BA_single (value : Floats.Float32)
  | BA_loadstack (chunk : Chunk) (offset : Integers.Ptrofs)
  | BA_addrstack (offset : Integers.Ptrofs)
  | BA_loadglobal (chunk : Chunk) (name : Ident) (offset : Integers.Ptrofs)
  | BA_addrglobal (name : Ident) (offset : Integers.Ptrofs)
  | BA_splitlong (hi lo : BuiltinArg)
  | BA_addptr (left right : BuiltinArg)
  deriving DecidableEq

/-- Builtin result registers, or a split pair for 64-bit results. -/
inductive BuiltinRes where
  | BR (register : PReg)
  | BR_none
  | BR_splitlong (hi lo : BuiltinRes)
  deriving DecidableEq
""")
    export.append("""Definition preg (r : Asm.preg) : string :=
  match r with
  | PC => "PC" | IR r => node "IR" [ireg r]
  | FR r => node "FR" [freg r] | ST0 => "ST0"
  | CR b => node "CR" [crbit b] | RA => "RA"
  end.

Definition optional {A} (render : A -> string) (value : option A) : string :=
  match value with None => "none" | Some x => node "some" [render x] end.

Definition index (p : Asm.ireg * Z) : string :=
  node "pair" [ireg (fst p); number (snd p)].

Definition displacement (d : Z + ident * ptrofs) : string :=
  match d with
  | inl z => node "inl" [number z]
  | inr p => node "inr" [node "pair" [identifier (fst p); offset (snd p)]]
  end.

Definition address (a : Asm.addrmode) : string :=
  match a with
  | Addrmode base ofs const =>
      node "Addrmode" [optional ireg base; optional index ofs; displacement const]
  end.

Fixpoint builtinarg (a : builtin_arg Asm.preg) : string :=
  match a with
  | BA r => node "BA" [preg r]
  | BA_int n => node "BA_int" [int n]
  | BA_long n => node "BA_long" [long n]
  | BA_float f => node "BA_float" [float f]
  | BA_single f => node "BA_single" [single f]
  | BA_loadstack c ofs => node "BA_loadstack" [chunk c; offset ofs]
  | BA_addrstack ofs => node "BA_addrstack" [offset ofs]
  | BA_loadglobal c id ofs => node "BA_loadglobal" [chunk c; identifier id; offset ofs]
  | BA_addrglobal id ofs => node "BA_addrglobal" [identifier id; offset ofs]
  | BA_splitlong hi lo => node "BA_splitlong" [builtinarg hi; builtinarg lo]
  | BA_addptr a b => node "BA_addptr" [builtinarg a; builtinarg b]
  end.

Fixpoint builtinres (r : builtin_res Asm.preg) : string :=
  match r with
  | BR r => node "BR" [preg r]
  | BR_none => "BR_none"
  | BR_splitlong hi lo => node "BR_splitlong" [builtinres hi; builtinres lo]
  end.
""")
    schema = {}
    lean.append(
        "/-- The full x86 instruction vocabulary of `x86/Asm.v`, with pseudo-instructions such as\n"
        "`Pallocframe`, `Pfreeframe`, `Plabel`, and `Pbuiltin`. -/\n"
        "inductive Instruction where"
    )
    export.append("Definition instruction (i : Asm.instruction) : string :=\n  match i with")
    for tag, fields in instructions:
        lean.append("  | " + tag + "".join(
            f" ({name} : {TYPES[typ][0]})" for name, typ in fields))
        pattern = tag + "".join(" " + name for name, _ in fields)
        if fields:
            schema[tag] = [TYPES[typ][1] for _, typ in fields]
            rendered = "; ".join(f"{TYPES[typ][2]} {name}" for name, typ in fields)
            export.append(f'  | {pattern} => node "{tag}" [{rendered}]')
        else:
            atoms.append(tag)
            export.append(f'  | {tag} => "{tag}"')
    lean.append("""  deriving DecidableEq

/-- A function body is a list of instructions, addressed by position. -/
abbrev Code := List Instruction

/-- An internal assembly function: signature and body. Frame layout lives in the
`Pallocframe` and `Pfreeframe` instructions. -/
structure Function where
  fn_sig : Signature
  fn_code : Code
  deriving DecidableEq

/-- A function definition is internal assembly code or an external function. -/
inductive Fundef where
  | Internal (function : Function)
  | External (function : ExtFun)
  deriving DecidableEq

/-- An assembly program: global definitions, public symbols, and the entry symbol. -/
structure Program where
  prog_defs : List (Ident × GlobDef Fundef Unit)
  prog_public : List Ident
  prog_main : Ident

/-- Global environments mapping symbols and blocks to assembly function definitions. -/
abbrev Genv := CC.Genv Fundef Unit

/-- The global environment holding every definition of `program`. -/
def Program.globalenv (program : Program) : Genv :=
  CC.Genv.addGlobals (CC.Genv.emptyGenv program.prog_public) program.prog_defs

/-- Allocates every global of `program` in the empty memory, `none` if an allocation fails. -/
def Program.initMem (program : Program) : Option Mem :=
  CC.Genv.allocGlobals program.globalenv Mem.empty program.prog_defs

end Quadrature.Asm
""")
    export.append("""  end.

Definition function (f : Asm.function) : string :=
  node "function" [signature (fn_sig f); items instruction (fn_code f)].

Definition fundef (f : Asm.fundef) : string :=
  match f with
  | Internal f => node "Internal" [function f]
  | External ef => node "External" [external ef]
  end.

Definition global (g : globdef Asm.fundef unit) : string :=
  match g with
  | Gfun f => node "Gfun" [fundef f]
  | Gvar v => node "Gvar" [items initializer (gvar_init v);
      boolean (gvar_readonly v); boolean (gvar_volatile v)]
  end.

Definition definition (g : ident * globdef Asm.fundef unit) : string :=
  node "pair" [identifier (fst g); global (snd g)].

Definition program (p : Asm.program) : string :=
  node "program" [items definition (prog_defs p); items identifier (prog_public p);
    identifier (prog_main p)].
""")
    files = {
        "Quadrature/Compiler/Asm/Syntax.lean": "\n".join(lean),
        "compcert/ExportAsm.v": "\n".join(export),
        "scripts/asm-schema.json": json.dumps({
            "upstream_sha256": SOURCE_SHA256,
            "instruction_constructor_count": len(instructions),
            "schema": schema, "atoms": atoms,
        }, indent=2) + "\n",
    }
    for name, content in files.items():
        path = output_root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    return {"instruction_constructor_count": len(instructions),
            "generated_files": list(files)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--asm-source", type=Path, required=True)
    parser.add_argument("--output-directory", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(generate(args.asm_source, args.output_directory), indent=2))


if __name__ == "__main__":
    main()
