#!/usr/bin/env python3
"""Render the ten Mach programs after stack layout in Lean and emit a Rocq AST certificate.

Inputs: --export-directory holding order1.out to order10.out from compcert/ExportMach.v.
Outputs: --lean-output (checked against Quadrature/Compiler/Mach/Imported.lean) and --rocq-output.
Requires scripts/import-ltl.py, loaded by path, which in turn loads import-cminorsel.py and
import-cminor.py. The shared SCHEMA is renamed from the L forms to the M forms with "Lbranch"
dropped. reproduce-mach-import.py drives this script. The Rocq certificate checks the complete
AST after Stacking.transf_program.
"""

import argparse
from collections import Counter
import copy
import hashlib
import importlib.util
import json
from pathlib import Path


SPEC = importlib.util.spec_from_file_location(
    "ltl_rendering", Path(__file__).with_name("import-ltl.py")
)
LTL = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(LTL)
BASE = LTL.BASE
BASE.SCHEMA = {
    ("M" + key[1:] if key.startswith("L") else key): value
    for key, value in BASE.SCHEMA.items() if key != "Lbranch"
}
BASE.SCHEMA.update({
    "Mlabel": ["id"], "Mgoto": ["id"],
    "Mcond": ["auto", "list:auto", "id"],
    "Mgetstack": ["offset", "auto", "auto"],
    "Msetstack": ["auto", "offset", "auto"],
    "Mgetparam": ["offset", "auto", "auto"],
})
BASE.ATOMS = (BASE.ATOMS - {"Lreturn"}) | {"Mreturn"}


class Renderer(LTL.Renderer):
    def convert(self, value, kind="auto"):
        if kind == "auto" and isinstance(value, list) and value[0] == "function":
            _, signature, stacksize, link, retaddr, code = value
            return self.record([
                ("fn_sig", self.convert(signature)),
                ("fn_stacksize", self.convert(stacksize, "z")),
                ("fn_link_ofs", self.convert(link, "offset")),
                ("fn_retaddr_ofs", self.convert(retaddr, "offset")),
                ("fn_code", self.convert(code, "list:auto")),
            ])
        return super().convert(value, kind)


def generate(directory, lean_path, rocq_path):
    programs = {n: BASE.parse_export(directory / f"order{n}.out") for n in range(1, 11)}
    difference = BASE.differences(programs[1], programs[2])
    if len(difference) != 1 or difference[0][1:] != ("1", "2"):
        raise ValueError("expected exactly one order constant")
    order_path = difference[0][0]
    for n in range(2, 11):
        if BASE.differences(programs[1], programs[n]) != [(order_path, "1", str(n))]:
            raise ValueError(f"unexpected program-family difference at order {n}")
    family = copy.deepcopy(programs[1])
    cursor = family
    for index in order_path[:-1]:
        cursor = cursor[index]
    if cursor[0] != "Ointconst" or order_path[1] != 73:
        raise ValueError("the varying value must be main's integer order constant")
    cursor[order_path[-1]] = "$ORDER"
    lean, rocq = Renderer("lean"), Renderer("rocq")
    definitions = family[1][1:]
    assert len(definitions) == 73 and definitions[-1][1] == family[3]
    lean_parts = [
        "import Quadrature.Compiler.Mach.Syntax\n",
        "/-!\n# Actual Mach output for all ten applications\n\n"
        "Generated by `scripts/import-mach.py` from the pinned configured compiler.\n"
        "All 73 globals, code, byte offsets, frame metadata, and constant bits are retained.\n"
        "A separate Rocq certificate checks exact syntax against `Stacking.transf_program`;\n"
        "the rendering and a cross-kernel semantics interpretation remain unproved.\n-/\n",
        "namespace Quadrature.Mach.Imported\n\nopen CC\n",
    ]
    references = []
    for index, definition in enumerate(definitions):
        main = index == len(definitions) - 1
        name = "mainDefinition" if main else f"global{index}"
        binder = " (n : Nat)" if main else ""
        lean_parts.append(
            f"def {name}{binder} : Ident × GlobDef Fundef Unit :=\n  "
            + BASE.render(lean.convert(definition, "definition"), 2) + "\n"
        )
        references.append("mainDefinition n" if main else name)
    lean_parts.append(
        "def program (n : Nat) : Program where\n  prog_defs := "
        + BASE.render(lean.sequence(references), 15)
        + "\n  prog_public := " + BASE.render(lean.convert(family[2], "list:id"), 17)
        + "\n  prog_main := " + BASE.render(lean.convert(family[3], "id"), 15) + "\n"
    )
    lean_parts.append("end Quadrature.Mach.Imported\n")
    lean_path.parent.mkdir(parents=True, exist_ok=True)
    lean_path.write_text("\n".join(lean_parts))
    rocq_path.write_text(
        "From Coq Require Import List String ZArith Lia.\n"
        "From compcert Require Import AST Maps Integers Floats Mach Op Errors Locations Stacking.\n"
        "From CminorImport Require Import EqualityMach ImportedLinear MachAfterStacking\n"
        "  MachReturnAddresses.\n"
        "Import ListNotations.\nLocal Open Scope string_scope.\n"
        "\n"
        "Definition imported_program (n : nat) : Mach.program :=\n  "
        + BASE.render(rocq.convert(family), 2) + ".\n\n"
        "Definition compiled_mach n := Stacking.transf_program (ImportedLinear.imported_program n).\n"
        "Definition compiled_matches n : bool :=\n"
        "  match compiled_mach n with\n"
        "  | Errors.OK p => mach_program_eqb p (imported_program n)\n"
        "  | Errors.Error _ => false end.\n\n"
        "Lemma compiled_matches_sound n : compiled_matches n = true ->\n"
        "  compiled_mach n = Errors.OK (imported_program n).\n"
        "Proof.\n"
        "  unfold compiled_matches. destruct (compiled_mach n); intro H.\n"
        "  - exact (f_equal (@Errors.OK Mach.program) (mach_program_eqb_sound _ _ H)).\n"
        "  - discriminate.\n"
        "Qed.\n\n"
        "Theorem passes_produce_imported_program n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) : compiled_mach n = Errors.OK (imported_program n).\n"
        "Proof.\n"
        "  apply compiled_matches_sound.\n"
        "  assert (H : " + " \\/ ".join(f"n = {n}%nat" for n in range(1, 11))
        + ") by lia.\n"
        "  repeat destruct H as [H | H]; subst n; vm_compute; reflexivity.\n"
        "Qed.\n\n"
        "Definition translated n := match ImportedLinear.translated n with\n"
        "  | Errors.OK p => Stacking.transf_program p | Errors.Error e => Errors.Error e end.\n"
        "Theorem imported_program_is_compiler_output n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) : translated n = Errors.OK (imported_program n).\n"
        "Proof.\n"
        "  unfold translated. rewrite (ImportedLinear.imported_program_is_compiler_output\n"
        "    n hlo hhi). exact (passes_produce_imported_program n hlo hhi).\n"
        "Qed.\n\n"
        "Theorem compiler_uses_imported_program n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) :\n"
        "  ImportedPreallocation.remaining_backend n = after_mach (Errors.OK (imported_program n)).\n"
        "Proof.\n"
        "  rewrite (ImportedLinear.compiler_uses_imported_program n hlo hhi).\n"
        "  rewrite stacking_split. change (after_mach (compiled_mach n) =\n"
        "    after_mach (Errors.OK (imported_program n))).\n"
        "  rewrite (passes_produce_imported_program n hlo hhi). reflexivity.\n"
        "Qed.\n\n"
        "Theorem imported_return_addresses_known n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) : program_returns_known (imported_program n) = true.\n"
        "Proof.\n"
        "  assert (H : " + " \\/ ".join(f"n = {n}%nat" for n in range(1, 11))
        + ") by lia.\n"
        "  repeat destruct H as [H | H]; subst n; vm_compute; reflexivity.\n"
        "Qed.\n\n"
        "Theorem imported_call_return_addresses n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) name f\n"
        "    (IN : In (name, Gfun (Internal f)) (prog_defs (imported_program n))) :\n"
        "  forall c, In c (call_continuations (Mach.fn_code f)) ->\n"
        "  exists offset, predict_return_address f c = Some offset /\\\n"
        "    (forall other, Asmgenproof0.return_address_offset f c other <-> other = offset).\n"
        "Proof.\n"
        "  exact (program_returns_known_sound _\n"
        "    (imported_return_addresses_known n hlo hhi) name f IN).\n"
        "Qed.\n\n"
        "Print Assumptions imported_program_is_compiler_output.\n"
        "Print Assumptions compiler_uses_imported_program.\n"
        "Print Assumptions imported_call_return_addresses.\n"
    )
    inventory = Counter()

    def walk(value):
        if isinstance(value, list):
            inventory[value[0]] += 1
            for child in value[1:]:
                walk(child)
        elif isinstance(value, str) and not value.lstrip("-").isdecimal():
            inventory[value] += 1

    walk(programs[1])
    frames = []
    for index, definition in enumerate(programs[1][1][1:]):
        global_definition = definition[2]
        if global_definition[0] != "Gfun" or global_definition[1][0] != "Internal":
            continue
        function = global_definition[1][1]
        code = function[5][1:]
        frames.append({
            "definition_index": index,
            "identifier": definition[1],
            "stack_size_bytes": int(function[2]),
            "parent_link_offset_bytes": int(function[3]),
            "return_address_offset_bytes": int(function[4]),
            "instruction_count": len(code),
            "call_continuation_lengths": [
                len(code) - position - 1 for position, instruction in enumerate(code)
                if isinstance(instruction, list) and instruction[0] == "Mcall"
            ],
        })
    return {
        "globals": len(definitions), "orders": list(programs),
        "order_constant_path": order_path,
        "internal_function_frames_order_one": frames,
        "constructor_inventory_order_one": dict(sorted(inventory.items())),
        "exports_sha256": {
            f"order{n}.out": hashlib.sha256((directory/f"order{n}.out").read_bytes()).hexdigest()
            for n in programs
        },
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--export-directory", type=Path, required=True)
    parser.add_argument("--lean-output", type=Path, required=True)
    parser.add_argument("--rocq-output", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(generate(args.export_directory, args.lean_output, args.rocq_output), indent=2))


if __name__ == "__main__":
    main()
