#!/usr/bin/env python3
"""Render the ten imported assembly programs in Lean and certify their Rocq AST against Asmgen.

Inputs: --export-directory holding order1.out to order10.out from compcert/ExportAsm.v.
Outputs: --lean-output (checked against Quadrature/Compiler/Asm/Imported.lean) and --rocq-output.
Requires scripts/import-cminor.py, loaded here by path with its module-level SCHEMA and ATOMS
rewritten for the assembly vocabulary, and scripts/asm-schema.json from generate-asm-syntax.py.
reproduce-asm-import.py drives this script.
"""

import argparse
from collections import Counter
import copy
import hashlib
import importlib.util
import json
from pathlib import Path


SPEC = importlib.util.spec_from_file_location(
    "asm_base_rendering", Path(__file__).with_name("import-cminor.py")
)
BASE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(BASE)
VOCABULARY = json.loads(Path(__file__).with_name("asm-schema.json").read_text())
BASE.SCHEMA = {
    key: value for key, value in BASE.SCHEMA.items()
    if key.startswith(("EF_", "Init_")) or key in {"Internal", "External", "Gfun"}
}
BASE.SCHEMA.update(VOCABULARY["schema"])
BASE.SCHEMA.update({
    "IR": ["auto"], "FR": ["auto"], "CR": ["auto"],
    "Addrmode": ["option:auto", "option:index", "displacement"],
    "BA": ["auto"], "BA_int": ["int"], "BA_long": ["long"],
    "BA_float": ["float"], "BA_single": ["single"],
    "BA_loadstack": ["auto", "offset"], "BA_addrstack": ["offset"],
    "BA_loadglobal": ["auto", "id", "offset"], "BA_addrglobal": ["id", "offset"],
    "BA_splitlong": ["auto", "auto"], "BA_addptr": ["auto", "auto"],
    "BR": ["auto"], "BR_splitlong": ["auto", "auto"],
})
BASE.ATOMS = {
    value for value in BASE.ATOMS if value.startswith(("T", "X", "M", "EF_"))
} | set(VOCABULARY["atoms"]) | {"PC", "ST0", "RA", "BR_none"}


class Renderer(BASE.Renderer):
    def convert(self, value, kind="auto"):
        if kind == "z" and self.lean and isinstance(value, str) and value.startswith("-"):
            # Lean parses an unparenthesized negative argument as subtraction.
            return "(" + super().convert(value, kind) + ")"
        if kind in {"index", "symbol-offset"}:
            if not isinstance(value, list) or value[0] != "pair" or len(value) != 3:
                raise ValueError(f"malformed assembly pair: {value}")
            kinds = ("auto", "z") if kind == "index" else ("id", "offset")
            return BASE.Doc("(", [self.convert(x, k) for x, k in zip(value[1:], kinds)],
                            ", ", ")")
        if kind == "displacement":
            if not isinstance(value, list) or len(value) != 2 or value[0] not in {"inl", "inr"}:
                raise ValueError(f"malformed assembly displacement: {value}")
            tag = value[0]
            return BASE.app(("." + tag) if self.lean else (tag + " _"),
                            [self.convert(value[1], "z" if tag == "inl" else "symbol-offset")])
        if kind == "auto" and isinstance(value, list) and value[0] == "function":
            _, signature, code = value
            return self.record([
                ("fn_sig", self.convert(signature)),
                ("fn_code", self.convert(code, "list:auto")),
            ])
        return super().convert(value, kind)


def generate(directory, lean_path, rocq_path):
    programs = {n: BASE.parse_export(directory / f"order{n}.out") for n in range(1, 11)}
    difference = BASE.differences(programs[1], programs[2])
    if len(difference) != 1 or difference[0][1:] != ("1", "2"):
        raise ValueError("expected exactly one order constant")
    order_path = difference[0][0]
    for n in range(2, 11):
        if BASE.differences(programs[1], programs[n]) != [(order_path, "1", str(n))]:
            raise ValueError(f"unexpected program-family difference at order {n}")
    family = copy.deepcopy(programs[1])
    cursor = family
    for index in order_path[:-1]:
        cursor = cursor[index]
    if cursor[0] != "Pmovl_ri" or order_path[1] != 73 or order_path[-1] != 2:
        raise ValueError("the varying value must be main's immediate integer order")
    cursor[order_path[-1]] = "$ORDER"
    lean, rocq = Renderer("lean"), Renderer("rocq")
    definitions = family[1][1:]
    if len(definitions) != 73 or definitions[-1][1] != family[3]:
        raise ValueError("unexpected globals or entry point")
    lean_parts = [
        "import Quadrature.Compiler.Asm.Syntax\n",
        "/-!\n# Actual formal assembly for all ten applications\n\n"
        "Generated by `scripts/import-asm.py` from the pinned configured compiler.\n"
        "All 73 globals, complete instruction lists, signatures, addresses, and constant\n"
        "bits are retained. Rocq checks exact syntax against `Asmgen.transf_program`\n"
        "and the remaining compiler pipeline. This rendering is not an execution proof\n"
        "or a proved interpretation between Lean and Rocq.\n-/\n",
        "namespace Quadrature.Asm.Imported\n\nopen CC\n",
    ]
    references = []
    for index, definition in enumerate(definitions):
        main = index == len(definitions) - 1
        name = "mainDefinition" if main else f"global{index}"
        binder = " (n : Nat)" if main else ""
        lean_parts.append(
            f"def {name}{binder} : Ident × GlobDef Fundef Unit :=\n  "
            + BASE.render(lean.convert(definition, "definition"), 2) + "\n"
        )
        references.append("mainDefinition n" if main else name)
    lean_parts.append(
        "def program (n : Nat) : Program where\n  prog_defs := "
        + BASE.render(lean.sequence(references), 15)
        + "\n  prog_public := " + BASE.render(lean.convert(family[2], "list:id"), 17)
        + "\n  prog_main := " + BASE.render(lean.convert(family[3], "id"), 15) + "\n"
    )
    lean_parts.append("end Quadrature.Asm.Imported\n")
    lean_path.parent.mkdir(parents=True, exist_ok=True)
    lean_path.write_text("\n".join(lean_parts))
    rocq_path.write_text(
        "From Coq Require Import List String ZArith Lia.\n"
        "From compcert Require Import AST Maps Integers Floats Asm Asmgen Errors Compiler.\n"
        "From CminorImport Require Import EqualityAsm ImportedMach MachAfterStacking.\n"
        "Import ListNotations.\nLocal Open Scope string_scope.\n\n"
        "Definition imported_program (n : nat) : Asm.program :=\n  "
        + BASE.render(rocq.convert(family), 2) + ".\n\n"
        "Definition compiled_asm n := Asmgen.transf_program (ImportedMach.imported_program n).\n"
        "Definition compiled_matches n : bool :=\n"
        "  match compiled_asm n with\n"
        "  | Errors.OK p => asm_program_eqb p (imported_program n)\n"
        "  | Errors.Error _ => false end.\n\n"
        "Lemma compiled_matches_sound n : compiled_matches n = true ->\n"
        "  compiled_asm n = Errors.OK (imported_program n).\n"
        "Proof.\n"
        "  unfold compiled_matches. destruct (compiled_asm n); intro H.\n"
        "  - exact (f_equal (@Errors.OK Asm.program) (asm_program_eqb_sound _ _ H)).\n"
        "  - discriminate.\n"
        "Qed.\n\n"
        "Theorem assembly_generation_produces_imported_program n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) : compiled_asm n = Errors.OK (imported_program n).\n"
        "Proof.\n"
        "  apply compiled_matches_sound.\n"
        "  assert (H : " + " \\/ ".join(f"n = {n}%nat" for n in range(1, 11))
        + ") by lia.\n"
        "  repeat destruct H as [H | H]; subst n; vm_compute; reflexivity.\n"
        "Qed.\n\n"
        "Definition translated n := match ImportedMach.translated n with\n"
        "  | Errors.OK p => Asmgen.transf_program p | Errors.Error e => Errors.Error e end.\n"
        "Theorem imported_program_is_compiler_output n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) : translated n = Errors.OK (imported_program n).\n"
        "Proof.\n"
        "  unfold translated. rewrite (ImportedMach.imported_program_is_compiler_output\n"
        "    n hlo hhi). exact (assembly_generation_produces_imported_program n hlo hhi).\n"
        "Qed.\n\n"
        "Theorem compiler_produces_imported_program n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) :\n"
        "  ImportedPreallocation.remaining_backend n = Errors.OK (imported_program n).\n"
        "Proof.\n"
        "  rewrite (ImportedMach.compiler_uses_imported_program n hlo hhi).\n"
        "  unfold after_mach, Compiler.apply_partial, Compiler.apply_total, Compiler.time.\n"
        "  rewrite Compiler.print_identity.\n"
        "  exact (assembly_generation_produces_imported_program n hlo hhi).\n"
        "Qed.\n\n"
        "Print Assumptions assembly_generation_produces_imported_program.\n"
        "Print Assumptions imported_program_is_compiler_output.\n"
        "Print Assumptions compiler_produces_imported_program.\n"
    )
    inventory = Counter()

    def walk(value):
        if isinstance(value, list):
            inventory[value[0]] += 1
            for child in value[1:]:
                walk(child)
        elif isinstance(value, str) and not value.lstrip("-").isdecimal():
            inventory[value] += 1

    walk(programs[1])
    functions = []
    for index, definition in enumerate(programs[1][1][1:]):
        global_definition = definition[2]
        if global_definition[0] != "Gfun" or global_definition[1][0] != "Internal":
            continue
        function = global_definition[1][1]
        code = function[2][1:]
        functions.append({
            "definition_index": index, "identifier": definition[1],
            "instruction_count": len(code),
            "call_return_offsets": [
                position + 1 for position, instruction in enumerate(code)
                if isinstance(instruction, list) and instruction[0] in {"Pcall_s", "Pcall_r"}
            ],
        })
    return {
        "globals": len(definitions), "orders": list(programs),
        "order_constant_path": order_path,
        "internal_functions_order_one": functions,
        "constructor_inventory_order_one": dict(sorted(inventory.items())),
        "exports_sha256": {
            f"order{n}.out": hashlib.sha256((directory / f"order{n}.out").read_bytes()).hexdigest()
            for n in programs
        },
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--export-directory", type=Path, required=True)
    parser.add_argument("--lean-output", type=Path, required=True)
    parser.add_argument("--rocq-output", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(generate(args.export_directory, args.lean_output, args.rocq_output), indent=2))


if __name__ == "__main__":
    main()
