#!/usr/bin/env python3
"""Render the actual assembly return-address offsets as finite tables in Lean and Rocq.

Inputs: --export-directory holding addresses1.out to addresses10.out from
compcert/ExportMachReturnAddresses.v. Outputs: --lean-output (checked against
Quadrature/Compiler/Mach/ImportedReturnAddresses.lean) and --rocq-output.
Requires scripts/import-mach.py, loaded by path for its parser and renderers.
reproduce-mach-return-addresses.py drives this script. The Rocq certificate connects every table
entry to Asmgen's return-address relation and checks coverage of every static call.
"""

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path


SPEC = importlib.util.spec_from_file_location(
    "mach_rendering", Path(__file__).with_name("import-mach.py")
)
MACH = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MACH)


def generate(directory, lean_path, rocq_path):
    exports = {
        n: MACH.BASE.parse_export(directory / f"addresses{n}.out")
        for n in range(1, 11)
    }
    first = exports[1]
    if not isinstance(first, list) or first[0] != "list":
        raise ValueError("expected an address list")
    if any(table != first for table in exports.values()):
        raise ValueError("the ten programs do not share a return-address table")
    rows = []
    for row in first[1:]:
        if len(row) != 4 or row[0] != "row":
            raise ValueError(f"malformed address row: {row!r}")
        values = tuple(int(value) for value in row[1:])
        if any(value < 0 for value in values):
            raise ValueError(f"negative address-table field: {values}")
        rows.append(values)
    if len(rows) != 16 or len(set(rows)) != len(rows):
        raise ValueError("expected the sixteen distinct static calls")
    lean_rows = ",\n    ".join(f"⟨{i}, {skip}, {offset}⟩" for i, skip, offset in rows)
    lean_path.parent.mkdir(parents=True, exist_ok=True)
    lean_path.write_text(
        "import Mathlib.Tactic.IntervalCases\n"
        "import Quadrature.Compiler.Mach.Imported\n"
        "import Quadrature.Compiler.Mach.ReturnAddresses\n"
        "\n"
        "/-!\n# Imported return addresses for the ten Mach programs\n\n"
        "The return-address table of the ten programs, generated by\n"
        "`scripts/import-mach-return-addresses.py` from CompCert's Asmgen predictor. Read\n"
        "`relation` first, membership in `table n`. Offsets count assembly instructions, not bytes.\n"
        "`table_consistent` checks each table by kernel evaluation, so `predict_iff` makes lookup\n"
        "and membership agree. `Asm.Generation.Imported.table_valid` proves every entry is a return\n"
        "address of the Lean Asmgen translation, and `table_address_iff` that the two oracles agree\n"
        "at every static call of the ten programs.\n\n"
        "Vocabulary and scope: `Quadrature.Compiler.Execution.Run`.\n-/\n\n"
        "namespace Quadrature.Mach.ImportedAddresses\n\n"
        "/-- The sixteen (global index, skip, offset) rows, shared by all ten programs. -/\n"
        f"def rows : List AddressRow :=\n  [{lean_rows}]\n\n"
        "/-- The entries of `rows` in the n-node program. -/\n"
        "def table (n : Nat) : List AddressEntry := addressTable (Imported.program n) rows\n\n"
        "/-- The executable predictor for the n-node program: lookup in `table n`. -/\n"
        "def predict (n : Nat) : ReturnAddressExecutor := lookupAddress (table n)\n\n"
        "/-- The return-address oracle for the n-node program: membership in `table n`. -/\n"
        "def relation (n : Nat) : ReturnAddress := tableAddress (table n)\n\n"
        "/-- Every offset predicted for the n-node program is in its table. -/\n"
        "theorem predict_sound (n : Nat) :\n"
        "    ReturnAddressExecutorSound (predict n) (relation n) :=\n"
        "  lookup_address_sound (table n)\n\n"
        "-- Kernel evaluation of `consistentAddresses` on the sixteen-entry table of each program.\n"
        "set_option maxRecDepth 100000 in\n"
        "/-- For n = 1..10, every entry of `table n` is found by lookup, by kernel evaluation. -/\n"
        "theorem table_consistent (n : Nat) (hlo : 1 ≤ n) (hhi : n ≤ 10) :\n"
        "    consistentAddresses (table n) = true := by\n"
        "  interval_cases n <;> decide +kernel\n\n"
        "/-- For n = 1..10, prediction and table membership agree. -/\n"
        "theorem predict_iff (n : Nat) (hlo : 1 ≤ n) (hhi : n ≤ 10)\n"
        "    {function : Function} {code : Code} {offset : CC.Integers.Ptrofs} :\n"
        "    predict n function code = some offset ↔ relation n function code offset :=\n"
        "  lookup_address_iff (table_consistent n hlo hhi)\n\n"
        "end Quadrature.Mach.ImportedAddresses\n"
    )
    rocq_rows = ";\n    ".join(
        f"({i}%nat, {skip}%nat, {offset}%Z)" for i, skip, offset in rows
    )
    cases = " \\/ ".join(f"n = {n}%nat" for n in range(1, 11))
    computation = (
        f"  assert (H : {cases}) by lia.\n"
        "  repeat destruct H as [H | H]; subst n; vm_compute; reflexivity.\n"
    )
    rocq_path.write_text(
        "From Coq Require Import List ZArith Lia.\n"
        "From compcert Require Import AST Integers Mach.\n"
        "From CminorImport Require Import ImportedMach MachReturnAddresses\n"
        "  MachReturnAddressTable.\n"
        "Import ListNotations.\n\n"
        f"Definition rows : list address_row :=\n  [{rocq_rows}].\n\n"
        "Definition table n := address_table (ImportedMach.imported_program n) rows.\n\n"
        "Theorem table_valid n (hlo : (1 <= n)%nat) (hhi : (n <= 10)%nat) :\n"
        "  valid_table (table n) = true.\nProof.\n" + computation + "Qed.\n\n"
        "Theorem table_covers n (hlo : (1 <= n)%nat) (hhi : (n <= 10)%nat) :\n"
        "  covers_program (table n) (ImportedMach.imported_program n) = true.\n"
        "Proof.\n" + computation + "Qed.\n\n"
        "Theorem table_lookup_sound n (hlo : (1 <= n)%nat) (hhi : (n <= 10)%nat)\n"
        "    f c offset :\n"
        "  lookup_address (table n) f c = Some offset ->\n"
        "  Asmgenproof0.return_address_offset f c offset.\n"
        "Proof. exact (lookup_address_sound _ _ _ _ (table_valid n hlo hhi)). Qed.\n\n"
        "Theorem table_lookup_iff n (hlo : (1 <= n)%nat) (hhi : (n <= 10)%nat)\n"
        "    name f c offset\n"
        "    (FUNCTION : In (name, Gfun (Internal f))\n"
        "      (prog_defs (ImportedMach.imported_program n)))\n"
        "    (CALL : In c (call_continuations (Mach.fn_code f))) :\n"
        "  Asmgenproof0.return_address_offset f c offset <->\n"
        "    lookup_address (table n) f c = Some offset.\n"
        "Proof.\n"
        "  exact (lookup_address_iff _ _ _ _ _ _ (table_valid n hlo hhi)\n"
        "    (table_covers n hlo hhi) FUNCTION CALL).\n"
        "Qed.\n\n"
        "Print Assumptions table_valid.\n"
        "Print Assumptions table_covers.\n"
        "Print Assumptions table_lookup_sound.\n"
        "Print Assumptions table_lookup_iff.\n"
    )
    return {
        "orders": list(exports),
        "rows_per_program": len(rows),
        "rows": [
            {"global_index": i, "skip_mach_instructions": skip,
             "formal_assembly_offset": offset}
            for i, skip, offset in rows
        ],
        "all_orders_share_rows": True,
        "exports_sha256": {
            f"addresses{n}.out": hashlib.sha256(
                (directory / f"addresses{n}.out").read_bytes()
            ).hexdigest()
            for n in exports
        },
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--export-directory", type=Path, required=True)
    parser.add_argument("--lean-output", type=Path, required=True)
    parser.add_argument("--rocq-output", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(generate(args.export_directory, args.lean_output, args.rocq_output),
                     indent=2))


if __name__ == "__main__":
    main()
