#!/usr/bin/env python3
"""Render the ten RTL programs produced by RTLgen in Lean and emit a Rocq AST certificate.

Inputs: --export-directory holding order1.out to order10.out from compcert/ExportRTL.v.
Outputs: --lean-output (checked against Quadrature/Compiler/RTL/Imported.lean) and --rocq-output.
Requires scripts/import-cminorsel.py, loaded by path, which in turn loads import-cminor.py.
The shared SCHEMA and ATOMS are rewritten for RTL. reproduce-rtl-import.py drives this script.
The generated Rocq theorem checks exact AST equality, including the CFG trees.
"""

import argparse
from collections import Counter
import copy
import hashlib
import importlib.util
import json
from pathlib import Path


SPEC = importlib.util.spec_from_file_location(
    "selected_rendering", Path(__file__).with_name("import-cminorsel.py")
)
SELECTED = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(SELECTED)
BASE = SELECTED.BASE
BASE.SCHEMA = {
    key: value for key, value in BASE.SCHEMA.items()
    if not key.startswith(("Evar", "Eop", "Eload", "Econdition", "Elet", "Econs", "CE", "XE", "S"))
}
BASE.SCHEMA.update({
    "BA": ["id"], "inl": ["id"],
    "Inop": ["id"],
    "Iop": ["operation", "list:id", "id", "id"],
    "Iload": ["auto", "auto", "list:id", "id", "id"],
    "Istore": ["auto", "auto", "list:id", "id", "id"],
    "Icall": ["auto", "auto", "list:id", "id", "id"],
    "Itailcall": ["auto", "auto", "list:id"],
    "Ibuiltin": ["auto", "list:auto", "auto", "id"],
    "Icond": ["auto", "list:id", "id", "id"],
    "Ijumptable": ["id", "list:id"],
    "Ireturn": ["option:id"],
})
BASE.ATOMS = (BASE.ATOMS - {"Enil", "Sskip"}) | {"Omove"}


class Renderer(SELECTED.Renderer):
    def convert(self, value, kind="auto"):
        if kind == "operation":
            rendered = super().convert(value)
            if self.lean and value != "Omove":
                return BASE.app(".selected", [rendered])
            return rendered
        if kind == "auto" and isinstance(value, list) and value[0] == "function":
            _, signature, params, stacksize, code, entry = value
            bindings = self.convert(code, "list:definition")
            code = BASE.app(
                "codeOfList" if self.lean else
                "fold_right (fun entry code => PTree.set (fst entry) (snd entry) code)"
                " (PTree.empty _)", [bindings]
            )
            return self.record([
                ("fn_sig", self.convert(signature)),
                ("fn_params", self.convert(params, "list:id")),
                ("fn_stacksize", self.convert(stacksize, "z")),
                ("fn_code", code),
                ("fn_entrypoint", self.convert(entry, "id")),
            ])
        return super().convert(value, kind)


def generate(directory, lean_path, rocq_path):
    programs = {n: BASE.parse_export(directory / f"order{n}.out") for n in range(1, 11)}
    difference = BASE.differences(programs[1], programs[2])
    if len(difference) != 1 or difference[0][1:] != ("1", "2"):
        raise ValueError("expected exactly one order constant")
    order_path = difference[0][0]
    for n in range(2, 11):
        if BASE.differences(programs[1], programs[n]) != [(order_path, "1", str(n))]:
            raise ValueError(f"unexpected program-family difference at order {n}")
    family = copy.deepcopy(programs[1])
    cursor = family
    for index in order_path[:-1]:
        cursor = cursor[index]
    if cursor[0] != "Ointconst" or order_path[1] != 73:
        raise ValueError("the varying value must be main's integer order constant")
    cursor[order_path[-1]] = "$ORDER"
    lean, rocq = Renderer("lean"), Renderer("rocq")
    definitions = family[1][1:]
    assert len(definitions) == 73 and definitions[-1][1] == family[3]
    lean_parts = [
        "import Quadrature.Compiler.RTL.Syntax\n",
        "/-!\n# Actual RTL output for all ten applications\n\n"
        "Generated by `scripts/import-rtl.py` from the pinned configured compiler.\n"
        "All 73 globals, CFG nodes, register identifiers, and constant bits are retained.\n"
        "A separate Rocq certificate checks exact syntax against `RTLgen.transl_program`;\n"
        "the rendering and a cross-kernel semantics interpretation remain unproved.\n-/\n",
        "namespace Quadrature.RTL.Imported\n\nopen CC\n",
    ]
    references = []
    for index, definition in enumerate(definitions):
        main = index == len(definitions) - 1
        name = "mainDefinition" if main else f"global{index}"
        binder = " (n : Nat)" if main else ""
        lean_parts.append(
            f"def {name}{binder} : Ident × GlobDef Fundef Unit :=\n  "
            + BASE.render(lean.convert(definition, "definition"), 2) + "\n"
        )
        references.append("mainDefinition n" if main else name)
    lean_parts.append(
        "def program (n : Nat) : Program where\n  prog_defs := "
        + BASE.render(lean.sequence(references), 15)
        + "\n  prog_public := " + BASE.render(lean.convert(family[2], "list:id"), 17)
        + "\n  prog_main := " + BASE.render(lean.convert(family[3], "id"), 15) + "\n"
    )
    lean_parts.append("end Quadrature.RTL.Imported\n")
    lean_path.parent.mkdir(parents=True, exist_ok=True)
    lean_path.write_text("\n".join(lean_parts))
    rocq_path.write_text(
        "From Coq Require Import List String ZArith Lia.\n"
        "From compcert Require Import AST Maps Integers Floats RTL Op Errors\n"
        "  Selection SelectOp Compopts RTLgen.\n"
        "From QuadratureC Require Import StoredPolynomialCompilation.\n"
        "From CminorImport Require Import EqualityRTL.\n"
        "Import ListNotations.\nLocal Open Scope string_scope.\n"
        "Local Transparent SelectOp.symbol_is_relocatable Compopts.optim_for_size\n"
        "  Selection.compile_switch Selection.if_conversion_heuristic.\n\n"
        "Definition imported_program (n : nat) : RTL.program :=\n  "
        + BASE.render(rocq.convert(family), 2) + ".\n\n"
        "Definition selected n :=\n"
        "  match StoredPolynomialCompilation.second_translation n with\n"
        "  | Errors.OK p => Selection.sel_program p | Errors.Error e => Errors.Error e end.\n"
        "Definition translated n := match selected n with\n"
        "  | Errors.OK p => RTLgen.transl_program p | Errors.Error e => Errors.Error e end.\n\n"
        "Definition translated_matches n : bool :=\n"
        "  match translated n with\n"
        "  | Errors.OK p => rtl_program_eqb p (imported_program n)\n"
        "  | Errors.Error _ => false end.\n\n"
        "Lemma translated_matches_sound n : translated_matches n = true ->\n"
        "  translated n = Errors.OK (imported_program n).\n"
        "Proof.\n"
        "  unfold translated_matches. destruct (translated n); intro H.\n"
        "  - exact (f_equal (@Errors.OK RTL.program) (rtl_program_eqb_sound _ _ H)).\n"
        "  - discriminate.\n"
        "Qed.\n\n"
        "Theorem imported_program_is_compiler_output n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) : translated n = Errors.OK (imported_program n).\n"
        "Proof.\n"
        "  apply translated_matches_sound.\n"
        "  assert (H : " + " \\/ ".join(f"n = {n}%nat" for n in range(1, 11))
        + ") by lia.\n"
        "  repeat destruct H as [H | H]; subst n; vm_compute; reflexivity.\n"
        "Qed.\n\nPrint Assumptions imported_program_is_compiler_output.\n"
    )
    inventory = Counter()

    def walk(value):
        if isinstance(value, list):
            inventory[value[0]] += 1
            for child in value[1:]:
                walk(child)
        elif isinstance(value, str) and not value.lstrip("-").isdecimal():
            inventory[value] += 1

    walk(programs[1])
    return {
        "globals": len(definitions), "orders": list(programs),
        "order_constant_path": order_path,
        "constructor_inventory_order_one": dict(sorted(inventory.items())),
        "exports_sha256": {
            f"order{n}.out": hashlib.sha256((directory/f"order{n}.out").read_bytes()).hexdigest()
            for n in programs
        },
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--export-directory", type=Path, required=True)
    parser.add_argument("--lean-output", type=Path, required=True)
    parser.add_argument("--rocq-output", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(generate(args.export_directory, args.lean_output, args.rocq_output), indent=2))


if __name__ == "__main__":
    main()
