#!/usr/bin/env python3
"""Render the ten allocated LTL programs in Lean and emit a Rocq AST certificate.

Inputs: --export-directory holding order1.out to order10.out from compcert/ExportLTL.v.
Outputs: --lean-output (checked against Quadrature/Compiler/LTL/Imported.lean) and --rocq-output.
Requires scripts/import-cminorsel.py, loaded by path, which in turn loads import-cminor.py.
The shared SCHEMA and ATOMS are rewritten for LTL. reproduce-ltl-import.py drives this script.
The generated Rocq theorem checks exact AST equality, including the CFG trees.
"""

import argparse
from collections import Counter
import copy
import hashlib
import importlib.util
import json
from pathlib import Path


SPEC = importlib.util.spec_from_file_location(
    "selected_rendering", Path(__file__).with_name("import-cminorsel.py")
)
SELECTED = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(SELECTED)
BASE = SELECTED.BASE
BASE.SCHEMA = {
    key: value for key, value in BASE.SCHEMA.items()
    if not key.startswith(("Evar", "Eop", "Eload", "Econdition", "Elet", "Econs", "CE", "XE", "S"))
}
BASE.SCHEMA.update({
    "BA": ["auto"], "BR": ["auto"], "inl": ["auto"],
    "R": ["auto"], "S": ["auto", "z", "auto"],
    "Lop": ["operation", "list:auto", "auto"],
    "Lload": ["auto", "auto", "list:auto", "auto"],
    "Lgetstack": ["auto", "z", "auto", "auto"],
    "Lsetstack": ["auto", "auto", "z", "auto"],
    "Lstore": ["auto", "auto", "list:auto", "auto"],
    "Lcall": ["auto", "auto"], "Ltailcall": ["auto", "auto"],
    "Lbuiltin": ["auto", "list:auto", "auto"],
    "Lbranch": ["id"], "Lcond": ["auto", "list:auto", "id", "id"],
    "Ljumptable": ["auto", "list:id"],
})
BASE.ATOMS = (BASE.ATOMS - {"Enil", "Sskip"}) | set("""
Omove Lreturn Local Incoming Outgoing
AX BX CX DX SI DI BP R8 R9 R10 R11 R12 R13 R14 R15
X0 X1 X2 X3 X4 X5 X6 X7 X8 X9 X10 X11 X12 X13 X14 X15 FP0
""".split())


class Renderer(SELECTED.Renderer):
    def convert(self, value, kind="auto"):
        if kind == "binding":
            assert value[0] == "pair" and len(value) == 3
            return BASE.Doc("(", [self.convert(value[1], "id"),
                                   self.convert(value[2], "list:auto")], ", ", ")")
        if not self.lean and kind == "auto" and value == "Local":
            return "Locations.Local"
        if kind == "operation":
            rendered = super().convert(value)
            if self.lean and value != "Omove":
                return BASE.app(".selected", [rendered])
            return rendered
        if kind == "auto" and isinstance(value, list) and value[0] == "function":
            _, signature, stacksize, code, entry = value
            bindings = self.convert(code, "list:binding")
            code = BASE.app(
                "codeOfList" if self.lean else
                "fold_right (fun entry code => PTree.set (fst entry) (snd entry) code)"
                " (PTree.empty _)", [bindings]
            )
            return self.record([
                ("fn_sig", self.convert(signature)),
                ("fn_stacksize", self.convert(stacksize, "z")),
                ("fn_code", code),
                ("fn_entrypoint", self.convert(entry, "id")),
            ])
        return super().convert(value, kind)


def generate(directory, lean_path, rocq_path):
    programs = {n: BASE.parse_export(directory / f"order{n}.out") for n in range(1, 11)}
    difference = BASE.differences(programs[1], programs[2])
    if len(difference) != 1 or difference[0][1:] != ("1", "2"):
        raise ValueError("expected exactly one order constant")
    order_path = difference[0][0]
    for n in range(2, 11):
        if BASE.differences(programs[1], programs[n]) != [(order_path, "1", str(n))]:
            raise ValueError(f"unexpected program-family difference at order {n}")
    family = copy.deepcopy(programs[1])
    cursor = family
    for index in order_path[:-1]:
        cursor = cursor[index]
    if cursor[0] != "Ointconst" or order_path[1] != 73:
        raise ValueError("the varying value must be main's integer order constant")
    cursor[order_path[-1]] = "$ORDER"
    lean, rocq = Renderer("lean"), Renderer("rocq")
    definitions = family[1][1:]
    assert len(definitions) == 73 and definitions[-1][1] == family[3]
    lean_parts = [
        "import Quadrature.Compiler.LTL.Syntax\n",
        "/-!\n# Actual LTL output for all ten applications\n\n"
        "Generated by `scripts/import-ltl.py` from the pinned configured compiler.\n"
        "All 73 globals, CFG nodes, machine registers and stack slots, and constant bits are retained.\n"
        "A separate Rocq certificate checks exact syntax against `Allocation.transf_program`;\n"
        "the rendering and a cross-kernel semantics interpretation remain unproved.\n-/\n",
        "namespace Quadrature.LTL.Imported\n\nopen CC\n",
    ]
    references = []
    for index, definition in enumerate(definitions):
        main = index == len(definitions) - 1
        name = "mainDefinition" if main else f"global{index}"
        binder = " (n : Nat)" if main else ""
        lean_parts.append(
            f"def {name}{binder} : Ident × GlobDef Fundef Unit :=\n  "
            + BASE.render(lean.convert(definition, "definition"), 2) + "\n"
        )
        references.append("mainDefinition n" if main else name)
    lean_parts.append(
        "def program (n : Nat) : Program where\n  prog_defs := "
        + BASE.render(lean.sequence(references), 15)
        + "\n  prog_public := " + BASE.render(lean.convert(family[2], "list:id"), 17)
        + "\n  prog_main := " + BASE.render(lean.convert(family[3], "id"), 15) + "\n"
    )
    lean_parts.append("end Quadrature.LTL.Imported\n")
    lean_path.parent.mkdir(parents=True, exist_ok=True)
    lean_path.write_text("\n".join(lean_parts))
    rocq_path.write_text(
        "From Coq Require Import List String ZArith Lia.\n"
        "From compcert Require Import AST Maps Integers Floats LTL Op Errors Locations Allocation.\n"
        "From CminorImport Require Import EqualityLTL ImportedPreallocation LTLAfterAllocation.\n"
        "Import ListNotations.\nLocal Open Scope string_scope.\n"
        "Local Transparent Allocation.regalloc Allocation.choose_allocation\n"
        "  Allocation.allocation_candidates.\n\n"
        "Definition imported_program (n : nat) : LTL.program :=\n  "
        + BASE.render(rocq.convert(family), 2) + ".\n\n"
        "Definition allocated n :=\n"
        "  Allocation.transf_program (ImportedPreallocation.imported_program n).\n"
        "Definition allocated_matches n : bool :=\n"
        "  match allocated n with\n"
        "  | Errors.OK p => ltl_program_eqb p (imported_program n)\n"
        "  | Errors.Error _ => false end.\n\n"
        "Lemma allocated_matches_sound n : allocated_matches n = true ->\n"
        "  allocated n = Errors.OK (imported_program n).\n"
        "Proof.\n"
        "  unfold allocated_matches. destruct (allocated n); intro H.\n"
        "  - exact (f_equal (@Errors.OK LTL.program) (ltl_program_eqb_sound _ _ H)).\n"
        "  - discriminate.\n"
        "Qed.\n\n"
        "Theorem allocation_produces_imported_program n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) : allocated n = Errors.OK (imported_program n).\n"
        "Proof.\n"
        "  apply allocated_matches_sound.\n"
        "  assert (H : " + " \\/ ".join(f"n = {n}%nat" for n in range(1, 11))
        + ") by lia.\n"
        "  repeat destruct H as [H | H]; subst n; vm_compute; reflexivity.\n"
        "Qed.\n\n"
        "Definition translated n := match ImportedPreallocation.translated n with\n"
        "  | Errors.OK p => Allocation.transf_program p | Errors.Error e => Errors.Error e end.\n"
        "Theorem imported_program_is_compiler_output n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) : translated n = Errors.OK (imported_program n).\n"
        "Proof.\n"
        "  unfold translated. rewrite (ImportedPreallocation.imported_program_is_compiler_output\n"
        "    n hlo hhi). exact (allocation_produces_imported_program n hlo hhi).\n"
        "Qed.\n\n"
        "Theorem compiler_uses_imported_program n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) :\n"
        "  ImportedPreallocation.remaining_backend n = after_allocation (Errors.OK (imported_program n)).\n"
        "Proof.\n"
        "  rewrite (ImportedPreallocation.compiler_uses_imported_program n hlo hhi).\n"
        "  rewrite allocation_split. change (after_allocation (allocated n) =\n"
        "    after_allocation (Errors.OK (imported_program n))).\n"
        "  rewrite (allocation_produces_imported_program n hlo hhi). reflexivity.\n"
        "Qed.\n\n"
        "Print Assumptions imported_program_is_compiler_output.\n"
        "Print Assumptions compiler_uses_imported_program.\n"
    )
    inventory = Counter()

    def walk(value):
        if isinstance(value, list):
            inventory[value[0]] += 1
            for child in value[1:]:
                walk(child)
        elif isinstance(value, str) and not value.lstrip("-").isdecimal():
            inventory[value] += 1

    walk(programs[1])
    return {
        "globals": len(definitions), "orders": list(programs),
        "order_constant_path": order_path,
        "constructor_inventory_order_one": dict(sorted(inventory.items())),
        "exports_sha256": {
            f"order{n}.out": hashlib.sha256((directory/f"order{n}.out").read_bytes()).hexdigest()
            for n in programs
        },
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--export-directory", type=Path, required=True)
    parser.add_argument("--lean-output", type=Path, required=True)
    parser.add_argument("--rocq-output", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(generate(args.export_directory, args.lean_output, args.rocq_output), indent=2))


if __name__ == "__main__":
    main()
