#!/usr/bin/env python3
"""Render the ten instruction-selected programs in Lean and emit a Rocq AST certificate.

Inputs: --export-directory holding order1.out to order10.out from compcert/ExportCminorSel.v.
Outputs: --lean-output (checked against Quadrature/Compiler/CminorSel/Imported.lean) and --rocq-output.
Requires scripts/import-cminor.py, loaded by path with its SCHEMA and ATOMS rewritten for the
selected-expression fragment. reproduce-cminorsel-import.py drives this script. The Rocq
certificate checks the reconstructed syntax against Selection.sel_program, and constructors
outside the Lean fragment are rejected.
"""

import argparse
from collections import Counter
import copy
import hashlib
import importlib.util
import json
from pathlib import Path


SPEC = importlib.util.spec_from_file_location(
    "cminor_rendering", Path(__file__).with_name("import-cminor.py")
)
BASE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(BASE)
BASE.SCHEMA = {
    key: value for key, value in BASE.SCHEMA.items()
    if key.startswith(("EF_", "Init_")) or key in {"Internal", "External", "Gfun"}
}
BASE.SCHEMA.update({
    "Ccomp": ["auto"], "Ccompimm": ["auto", "int"],
    "Aindexed": ["z"], "Aindexed2": ["z"],
    "Ascaled": ["z", "z"], "Aindexed2scaled": ["z", "z"],
    "Aglobal": ["id", "offset"], "Abased": ["id", "offset"],
    "Abasedscaled": ["z", "id", "offset"], "Ainstack": ["offset"],
    "Ointconst": ["int"], "Ofloatconst": ["float"],
    "Oshrximm": ["int"], "Olea": ["auto"], "Oleal": ["auto"],
    "Evar": ["id"], "Eop": ["auto", "auto"],
    "Eload": ["auto", "auto", "auto"],
    "Econdition": ["auto", "auto", "auto"], "Elet": ["auto", "auto"],
    "Eletvar": ["nat"], "Econs": ["auto", "auto"],
    "CEcond": ["auto", "auto"], "CEcondition": ["auto", "auto", "auto"],
    "CElet": ["auto", "auto"],
    "XEexit": ["nat"], "XEjumptable": ["auto", "list:nat"],
    "XEcondition": ["auto", "auto", "auto"], "XElet": ["auto", "auto"],
    "BA": ["auto"], "BA_int": ["int"], "BA_long": ["long"],
    "BA_float": ["float"], "BA_single": ["single"],
    "BA_loadstack": ["auto", "offset"], "BA_addrstack": ["offset"],
    "BA_loadglobal": ["auto", "id", "offset"], "BA_addrglobal": ["id", "offset"],
    "BA_splitlong": ["auto", "auto"], "BA_addptr": ["auto", "auto"],
    "BR": ["id"], "BR_splitlong": ["auto", "auto"],
    "inl": ["auto"], "inr": ["id"],
    "Sassign": ["id", "auto"], "Sstore": ["auto", "auto", "auto", "auto"],
    "Scall": ["option:id", "auto", "auto", "auto"],
    "Stailcall": ["auto", "auto", "auto"],
    "Sbuiltin": ["auto", "auto", "list:auto"],
    "Sseq": ["auto", "auto"], "Sifthenelse": ["auto", "auto", "auto"],
    "Sloop": ["auto"], "Sblock": ["auto"], "Sexit": ["nat"], "Sswitch": ["auto"],
    "Sreturn": ["option:auto"], "Slabel": ["id", "auto"], "Sgoto": ["id"],
})
BASE.ATOMS = {
    value for value in BASE.ATOMS
    if not value.startswith("O")
} | {
    "Omul", "Odiv", "Omod", "Ocast32signed", "Oaddf", "Osubf", "Omulf", "Odivf",
    "Enil", "BR_none",
}


class Renderer(BASE.Renderer):
    def convert(self, value, kind="auto"):
        rendered = super().convert(value, kind)
        if self.lean and kind == "z" and isinstance(rendered, str) and rendered.startswith("-"):
            return f"({rendered})"
        return rendered


def generate(directory, lean_path, rocq_path):
    programs = {n: BASE.parse_export(directory / f"order{n}.out") for n in range(1, 11)}
    order_path = (1, 73, 2, 1, 1, 5, 1, 4, 2, 1, 1, 1)
    for n in range(2, 11):
        if BASE.differences(programs[1], programs[n]) != [(order_path, "1", str(n))]:
            raise ValueError(f"unexpected program-family difference at order {n}")
    family = copy.deepcopy(programs[1])
    cursor = family
    for index in order_path[:-1]:
        cursor = cursor[index]
    assert cursor[0] == "Ointconst"
    cursor[order_path[-1]] = "$ORDER"
    lean, rocq = Renderer("lean"), Renderer("rocq")
    definitions = family[1][1:]
    assert len(definitions) == 73 and definitions[-1][1] == family[3]
    lean_parts = [
        "import Quadrature.Compiler.CminorSel.Syntax\n",
        "/-!\n# Actual instruction-selection output for all ten applications\n\n"
        "Generated by `scripts/import-cminorsel.py` from the pinned configured compiler.\n"
        "All 73 globals, numeric identifiers, and constant bits are retained. A separate\n"
        "Rocq certificate checks its syntax against `Selection.sel_program`; the rendering\n"
        "and a cross-kernel semantics interpretation are not proved by that certificate.\n-/\n",
        "namespace Quadrature.CminorSel.Imported\n\nopen CC\n",
    ]
    references = []
    for index, definition in enumerate(definitions):
        main = index == len(definitions) - 1
        name = "mainDefinition" if main else f"global{index}"
        binder = " (n : Nat)" if main else ""
        lean_parts.append(
            f"def {name}{binder} : Ident × GlobDef Fundef Unit :=\n  "
            + BASE.render(lean.convert(definition, "definition"), 2) + "\n"
        )
        references.append("mainDefinition n" if main else name)
    lean_parts.append(
        "def program (n : Nat) : Program where\n  prog_defs := "
        + BASE.render(lean.sequence(references), 15)
        + "\n  prog_public := " + BASE.render(lean.convert(family[2], "list:id"), 17)
        + "\n  prog_main := " + BASE.render(lean.convert(family[3], "id"), 15) + "\n"
    )
    lean_parts.append("end Quadrature.CminorSel.Imported\n")
    lean_path.parent.mkdir(parents=True, exist_ok=True)
    lean_path.write_text("\n".join(lean_parts))
    rocq_path.write_text(
        "From Coq Require Import List String ZArith Lia.\n"
        "From compcert Require Import AST Integers Floats CminorSel Op Errors\n"
        "  Selection SelectOp Compopts.\n"
        "From QuadratureC Require Import StoredPolynomialCompilation.\n"
        "From CminorImport Require Import EqualityCminorSel.\n"
        "Import ListNotations.\nLocal Open Scope string_scope.\n"
        "Local Transparent SelectOp.symbol_is_relocatable Compopts.optim_for_size\n"
        "  Selection.compile_switch Selection.if_conversion_heuristic.\n\n"
        "Definition imported_program (n : nat) : CminorSel.program :=\n  "
        + BASE.render(rocq.convert(family), 2) + ".\n\n"
        "Definition selected n :=\n"
        "  match StoredPolynomialCompilation.second_translation n with\n"
        "  | OK p => Selection.sel_program p | Error e => Error e end.\n\n"
        "Definition selected_matches n : bool :=\n"
        "  match selected n with\n"
        "  | OK p => cs_program_eqb p (imported_program n)\n"
        "  | Error _ => false end.\n\n"
        "Lemma selected_matches_sound n : selected_matches n = true ->\n"
        "  selected n = OK (imported_program n).\n"
        "Proof.\n"
        "  unfold selected_matches. destruct (selected n); intro H.\n"
        "  - exact (f_equal (@OK CminorSel.program) (cs_program_eqb_sound _ _ H)).\n"
        "  - discriminate.\n"
        "Qed.\n\n"
        "Theorem imported_program_is_compiler_output n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) : selected n = OK (imported_program n).\n"
        "Proof.\n"
        "  apply selected_matches_sound.\n"
        "  assert (H : " + " \\/ ".join(f"n = {n}%nat" for n in range(1, 11))
        + ") by lia.\n"
        "  repeat destruct H as [H | H]; subst n; vm_compute; reflexivity.\n"
        "Qed.\n\nPrint Assumptions imported_program_is_compiler_output.\n"
    )
    inventory = Counter()

    def walk(value):
        if isinstance(value, list):
            inventory[value[0]] += 1
            for child in value[1:]:
                walk(child)
        elif isinstance(value, str) and not value.lstrip("-").isdecimal():
            inventory[value] += 1

    walk(programs[1])
    return {
        "globals": len(definitions), "orders": list(programs),
        "order_constant_path": order_path,
        "constructor_inventory_order_one": dict(sorted(inventory.items())),
        "exports_sha256": {
            f"order{n}.out": hashlib.sha256((directory/f"order{n}.out").read_bytes()).hexdigest()
            for n in programs
        },
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--export-directory", type=Path, required=True)
    parser.add_argument("--lean-output", type=Path, required=True)
    parser.add_argument("--rocq-output", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(generate(args.export_directory, args.lean_output, args.rocq_output), indent=2))


if __name__ == "__main__":
    main()
