#!/usr/bin/env python3
"""Retain every byte of the pinned ASCII C file quadrules.c as Lean character data.

Inputs: the source path (hash-checked against SOURCE_SHA256) and the optional --check flag.
Output: Quadrature/CSource/Frontend/SourceData.lean, or with --check a byte comparison against that file.
Requires the pinned quadrules.c from upstream revision REVISION.
"""

import argparse
import hashlib
from pathlib import Path

SOURCE_SHA256 = "fb774551d772092f9ecba6dca51952ec9baaf4c3cdc27962f65d69818b2aeb91"
REVISION = "e79a28dba247db9f934289bcf4e4debd5eebc884"


def render(source: bytes) -> str:
    if hashlib.sha256(source).hexdigest() != SOURCE_SHA256:
        raise ValueError("The input is not the pinned upstream quadrules.c")
    source.decode("ascii")
    rows = [
        "   " + ", ".join(str(byte) for byte in source[i : i + 18])
        for i in range(0, len(source), 18)
    ]
    body = ",\n".join(rows).lstrip()
    return (
        "/-!\n"
        "# Original C source as ASCII character data\n\n"
        "Generated by `scripts/import-c-source.py` from `quadrules.c` in Appel and\n"
        "Bindel's `simple_cfem` repository, revision\n"
        f"{REVISION} (file SHA-256\n"
        f"{SOURCE_SHA256}). `source`\n"
        "holds every byte of the file as a `Char`, including whitespace and the final\n"
        "newline. Character data avoids repeated UTF-8 decoding during kernel\n"
        "evaluation. It is the input of the table-literal checks in\n"
        "`Quadrature.CSource.Tables.Literals` and of the parser and elaborator certificates in\n"
        "`Quadrature.CSource.Frontend.ClightFunctions` and "
        "`Quadrature.CSource.Frontend.TypedFunctions`.\n"
        "-/\n\n"
        "namespace Quadrature.CSourceData\n\n"
        "/-- Every byte of the original C source `quadrules.c`, as a list of characters. -/\n"
        "def source : List Char :=\n"
        f"  ([{body}] : List Nat).map Char.ofNat\n\n"
        "end Quadrature.CSourceData\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    destination = Path(__file__).resolve().parents[1] / "Quadrature/CSource/Frontend/SourceData.lean"
    expected = render(args.source.read_bytes())
    if args.check:
        if destination.read_text() != expected:
            raise SystemExit(f"{destination} differs from the pinned source rendering")
        print("C character data matches every byte of the pinned source.")
    else:
        destination.write_text(expected)


if __name__ == "__main__":
    main()
