#!/usr/bin/env python3
"""Render the ten Linear programs before stack layout in Lean and emit a Rocq AST certificate.

Inputs: --export-directory holding order1.out to order10.out from compcert/ExportLinear.v.
Outputs: --lean-output (checked against Quadrature/Compiler/Linear/Imported.lean) and --rocq-output.
Requires scripts/import-ltl.py, loaded by path, which in turn loads import-cminorsel.py and
import-cminor.py. This module pops "Lbranch" from the shared SCHEMA dict and adds the Linear
label and jump forms. reproduce-linear-import.py drives this script. The Rocq certificate checks
the complete AST immediately before Stacking.transf_program.
"""

import argparse
from collections import Counter
import copy
import hashlib
import importlib.util
import json
from pathlib import Path


SPEC = importlib.util.spec_from_file_location(
    "ltl_rendering", Path(__file__).with_name("import-ltl.py")
)
LTL = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(LTL)
BASE = LTL.BASE
BASE.SCHEMA.pop("Lbranch")
BASE.SCHEMA.update({
    "Llabel": ["id"], "Lgoto": ["id"],
    "Lcond": ["auto", "list:auto", "id"],
})


class Renderer(LTL.Renderer):
    def convert(self, value, kind="auto"):
        if kind == "auto" and isinstance(value, list) and value[0] == "function":
            _, signature, stacksize, code = value
            return self.record([
                ("fn_sig", self.convert(signature)),
                ("fn_stacksize", self.convert(stacksize, "z")),
                ("fn_code", self.convert(code, "list:auto")),
            ])
        return super().convert(value, kind)


def generate(directory, lean_path, rocq_path):
    programs = {n: BASE.parse_export(directory / f"order{n}.out") for n in range(1, 11)}
    difference = BASE.differences(programs[1], programs[2])
    if len(difference) != 1 or difference[0][1:] != ("1", "2"):
        raise ValueError("expected exactly one order constant")
    order_path = difference[0][0]
    for n in range(2, 11):
        if BASE.differences(programs[1], programs[n]) != [(order_path, "1", str(n))]:
            raise ValueError(f"unexpected program-family difference at order {n}")
    family = copy.deepcopy(programs[1])
    cursor = family
    for index in order_path[:-1]:
        cursor = cursor[index]
    if cursor[0] != "Ointconst" or order_path[1] != 73:
        raise ValueError("the varying value must be main's integer order constant")
    cursor[order_path[-1]] = "$ORDER"
    lean, rocq = Renderer("lean"), Renderer("rocq")
    definitions = family[1][1:]
    assert len(definitions) == 73 and definitions[-1][1] == family[3]
    lean_parts = [
        "import Quadrature.Compiler.Linear.Syntax\n",
        "/-!\n# Actual Linear output for all ten applications\n\n"
        "Generated by `scripts/import-linear.py` from the pinned configured compiler.\n"
        "All 73 globals, instruction lists, labels, registers, slots, and constant bits are retained.\n"
        "A separate Rocq certificate checks exact syntax before `Stacking.transf_program`;\n"
        "the rendering and a cross-kernel semantics interpretation remain unproved.\n-/\n",
        "namespace Quadrature.Linear.Imported\n\nopen CC\n",
    ]
    references = []
    for index, definition in enumerate(definitions):
        main = index == len(definitions) - 1
        name = "mainDefinition" if main else f"global{index}"
        binder = " (n : Nat)" if main else ""
        lean_parts.append(
            f"def {name}{binder} : Ident × GlobDef Fundef Unit :=\n  "
            + BASE.render(lean.convert(definition, "definition"), 2) + "\n"
        )
        references.append("mainDefinition n" if main else name)
    lean_parts.append(
        "def program (n : Nat) : Program where\n  prog_defs := "
        + BASE.render(lean.sequence(references), 15)
        + "\n  prog_public := " + BASE.render(lean.convert(family[2], "list:id"), 17)
        + "\n  prog_main := " + BASE.render(lean.convert(family[3], "id"), 15) + "\n"
    )
    lean_parts.append("end Quadrature.Linear.Imported\n")
    lean_path.parent.mkdir(parents=True, exist_ok=True)
    lean_path.write_text("\n".join(lean_parts))
    rocq_path.write_text(
        "From Coq Require Import List String ZArith Lia.\n"
        "From compcert Require Import AST Maps Integers Floats Linear Op Errors Locations Linearize.\n"
        "From CminorImport Require Import EqualityLinear ImportedLTL LinearBeforeStacking.\n"
        "Import ListNotations.\nLocal Open Scope string_scope.\n"
        "Local Transparent Linearize.enumerate_aux.\n\n"
        "Definition imported_program (n : nat) : Linear.program :=\n  "
        + BASE.render(rocq.convert(family), 2) + ".\n\n"
        "Definition compiled_linear n := linear_prefix (ImportedLTL.imported_program n).\n"
        "Definition compiled_matches n : bool :=\n"
        "  match compiled_linear n with\n"
        "  | Errors.OK p => linear_program_eqb p (imported_program n)\n"
        "  | Errors.Error _ => false end.\n\n"
        "Lemma compiled_matches_sound n : compiled_matches n = true ->\n"
        "  compiled_linear n = Errors.OK (imported_program n).\n"
        "Proof.\n"
        "  unfold compiled_matches. destruct (compiled_linear n); intro H.\n"
        "  - exact (f_equal (@Errors.OK Linear.program) (linear_program_eqb_sound _ _ H)).\n"
        "  - discriminate.\n"
        "Qed.\n\n"
        "Theorem passes_produce_imported_program n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) : compiled_linear n = Errors.OK (imported_program n).\n"
        "Proof.\n"
        "  apply compiled_matches_sound.\n"
        "  assert (H : " + " \\/ ".join(f"n = {n}%nat" for n in range(1, 11))
        + ") by lia.\n"
        "  repeat destruct H as [H | H]; subst n; vm_compute; reflexivity.\n"
        "Qed.\n\n"
        "Definition translated n := match ImportedLTL.translated n with\n"
        "  | Errors.OK p => linear_prefix p | Errors.Error e => Errors.Error e end.\n"
        "Theorem imported_program_is_compiler_output n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) : translated n = Errors.OK (imported_program n).\n"
        "Proof.\n"
        "  unfold translated. rewrite (ImportedLTL.imported_program_is_compiler_output\n"
        "    n hlo hhi). exact (passes_produce_imported_program n hlo hhi).\n"
        "Qed.\n\n"
        "Theorem compiler_uses_imported_program n (hlo : (1 <= n)%nat)\n"
        "    (hhi : (n <= 10)%nat) :\n"
        "  ImportedPreallocation.remaining_backend n = after_linear (Errors.OK (imported_program n)).\n"
        "Proof.\n"
        "  rewrite (ImportedLTL.compiler_uses_imported_program n hlo hhi).\n"
        "  rewrite linear_split. change (after_linear (compiled_linear n) =\n"
        "    after_linear (Errors.OK (imported_program n))).\n"
        "  rewrite (passes_produce_imported_program n hlo hhi). reflexivity.\n"
        "Qed.\n\n"
        "Print Assumptions imported_program_is_compiler_output.\n"
        "Print Assumptions compiler_uses_imported_program.\n"
    )
    inventory = Counter()

    def walk(value):
        if isinstance(value, list):
            inventory[value[0]] += 1
            for child in value[1:]:
                walk(child)
        elif isinstance(value, str) and not value.lstrip("-").isdecimal():
            inventory[value] += 1

    walk(programs[1])
    return {
        "globals": len(definitions), "orders": list(programs),
        "order_constant_path": order_path,
        "constructor_inventory_order_one": dict(sorted(inventory.items())),
        "exports_sha256": {
            f"order{n}.out": hashlib.sha256((directory/f"order{n}.out").read_bytes()).hexdigest()
            for n in programs
        },
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--export-directory", type=Path, required=True)
    parser.add_argument("--lean-output", type=Path, required=True)
    parser.add_argument("--rocq-output", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(generate(args.export_directory, args.lean_output, args.rocq_output), indent=2))


if __name__ == "__main__":
    main()
