#!/usr/bin/env python3
"""Retain the two binary64 initializer arrays of the pinned generated quadrules.v.

Inputs: --clight-source (hash-checked against CLIGHT_SHA256) and the optional --check flag.
Output: --output, Quadrature/Clight/TableData.lean by default, or with --check a comparison
against it.
Requires the pinned quadrules.v. Lean checks the memory loads and the agreement with the
numerical tables.
"""

import argparse
import hashlib
from pathlib import Path
import re


CLIGHT_SHA256 = "7b19b9f1095cb7a36316633af3b959f79a1745be0b0e6c36103a1a38c000a1f7"
UPSTREAM_REVISION = "e79a28dba247db9f934289bcf4e4debd5eebc884"


def table(source: str, name: str) -> list[int]:
    declaration = re.search(
        rf"Definition {re.escape(name)} := \{{\|(.*?)\|\}}\.", source, re.S
    )
    if declaration is None:
        raise ValueError(f"Missing initializer: {name}")
    body = re.sub(r"\s+", "", declaration.group(1))
    if not body.startswith("gvar_info:=(tarraytdouble55);gvar_init:="):
        raise ValueError(f"Unexpected array type: {name}")
    if not body.endswith(";gvar_readonly:=true;gvar_volatile:=false"):
        raise ValueError(f"Unexpected permissions: {name}")
    literals = re.findall(
        r"Init_float64\(Float.of_bits\(Int64.repr(\d+|\(-\d+\))\)\)", body
    )
    values = [int(n.strip("()")) for n in literals]
    if len(values) != 55 or any(not -(2**63) <= n < 2**64 for n in values):
        raise ValueError(f"Unexpected entries: {name}")
    initializer = "(" + "::".join(
        f"Init_float64(Float.of_bits(Int64.repr{n}))" for n in literals
    ) + "::nil)"
    expected = (
        "gvar_info:=(tarraytdouble55);gvar_init:="
        + initializer
        + ";gvar_readonly:=true;gvar_volatile:=false"
    )
    if body != expected:
        raise ValueError(f"Unsupported initializer syntax: {name}")
    return [n % 2**64 for n in values]


def render(source: bytes) -> str:
    if hashlib.sha256(source).hexdigest() != CLIGHT_SHA256:
        raise ValueError("Clight source does not match the pinned revision")
    text = source.decode("utf-8")
    declarations = []
    docstrings = {
        "nodeBits": (
            "/-- The 55 node encodings of the ten stored rules, flattened in triangular order: entry "
            "`i` of\n"
            "the `n`-point rule is element `n(n-1)/2 + i`. -/\n"
        ),
        "weightBits": (
            "/-- The 55 weight encodings of the ten stored rules, in the same triangular order as\n"
            "`nodeBits`. -/\n"
        ),
    }
    for lean_name, source_name in [("nodeBits", "v_gauss_pts"), ("weightBits", "v_gauss_wts")]:
        values = table(text, source_name)
        rows = [", ".join(f"0x{n:016x}" for n in values[i:i + 4])
                for i in range(0, len(values), 4)]
        declarations.append(
            docstrings[lean_name] + f"def {lean_name} : List Nat :=\n  ["
            + ",\n   ".join(rows) + "]\n"
        )
    return (
        "/-!\n# Imported Clight table encodings\n\n"
        "Generated by `scripts/import-clight-tables.py` from the two read-only\n"
        "55-element binary64 initializers `gauss_pts` and `gauss_wts` in the clightgen\n"
        "output of the original C program (`quadrules.c` in Appel and Bindel's\n"
        f"`simple_cfem` repository, revision {UPSTREAM_REVISION},\n"
        "clightgen output SHA-256\n"
        f"{CLIGHT_SHA256}).\n\n"
        "`nodeBits` and `weightBits` list the 64-bit encodings of the nodes and weights\n"
        "in the triangular layout of the C tables. The rule with `n` nodes occupies\n"
        "positions `n(n-1)/2` through `n(n-1)/2 + n - 1`. So the one-node rule is entry\n"
        "0, the two-node rule entries 1 and 2, and the ten-node rule entries 45 to 54.\n"
        "Entry `tableOffset n i` of `Quadrature.Clight.Loop` is node or weight `i` of the\n"
        "`n`-node rule. This file holds data only. `Quadrature.CSource.Tables.Literals` checks it\n"
        "against the decimal literals of the C text.\n"
        "-/\n\n"
        "namespace Quadrature.Binary64.ClightTableData\n\n"
        + "\n".join(declarations)
        + "\nend Quadrature.Binary64.ClightTableData\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--clight-source", required=True, type=Path)
    parser.add_argument("--output", type=Path,
                        default=Path(__file__).resolve().parents[1]
                        / "Quadrature/Clight/TableData.lean")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = render(args.clight_source.read_bytes())
    if args.check:
        if args.output.read_text() != output:
            raise ValueError("Generated Lean table data differs from the pinned source")
        print("Both 55-entry Lean tables match the pinned Clight initializers.")
    else:
        args.output.write_text(output)
        print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
