/-!
# Imported Clight table encodings

Generated by `scripts/import-clight-tables.py` from the two read-only
55-element binary64 initializers `gauss_pts` and `gauss_wts` in the clightgen
output of the original C program (`quadrules.c` in Appel and Bindel's
`simple_cfem` repository, revision e79a28dba247db9f934289bcf4e4debd5eebc884,
clightgen output SHA-256
7b19b9f1095cb7a36316633af3b959f79a1745be0b0e6c36103a1a38c000a1f7).

`nodeBits` and `weightBits` list the 64-bit encodings of the nodes and weights
in the triangular layout of the C tables. The rule with `n` nodes occupies
positions `n(n-1)/2` through `n(n-1)/2 + n - 1`. So the one-node rule is entry
0, the two-node rule entries 1 and 2, and the ten-node rule entries 45 to 54.
Entry `tableOffset n i` of `Quadrature.Clight.Loop` is node or weight `i` of the
`n`-node rule. This file holds data only. `Quadrature.CSource.Tables.Literals` checks it
against the decimal literals of the C text.
-/

namespace Quadrature.Binary64.ClightTableData

/-- The 55 node encodings of the ten stored rules, flattened in triangular order: entry `i` of
the `n`-point rule is element `n(n-1)/2 + i`. -/
def nodeBits : List Nat :=
  [0x0000000000000000, 0xbfe279a74590331c, 0x3fe279a74590331c, 0xbfe8c97ef43f7248,
   0x0000000000000000, 0x3fe8c97ef43f7248, 0xbfeb8e6dbcf63985, 0xbfd5c23fd9dd3dfc,
   0x3fd5c23fd9dd3dfc, 0x3feb8e6dbcf63985, 0xbfecff6ce0533a69, 0xbfe13b23fd99b704,
   0x0000000000000000, 0x3fe13b23fd99b704, 0x3fecff6ce0533a69, 0xbfedd6ca4e80a01e,
   0xbfe528a09655c963, 0xbfce8b12d03675c8, 0x3fce8b12d03675c8, 0x3fe528a09655c963,
   0x3fedd6ca4e80a01e, 0xbfee5f178e7c622e, 0xbfe7ba9f9be3a1d2, 0xbfd9f95df119fd5f,
   0x0000000000000000, 0x3fd9f95df119fd5f, 0x3fe7ba9f9be3a1d2, 0x3fee5f178e7c622e,
   0xbfeebab1cb0acc64, 0xbfe97e4ab249f420, 0xbfe0d129583284b4, 0xbfc77ac94f3c734c,
   0x3fc77ac94f3c734c, 0x3fe0d129583284b4, 0x3fe97e4ab249f420, 0x3feebab1cb0acc64,
   0xbfeefb2b2ebf2105, 0xbfeac0c44f0d029a, 0xbfe3a0bd2077fd89, 0xbfd4c0916e48aa68,
   0x0000000000000000, 0x3fd4c0916e48aa68, 0x3fe3a0bd2077fd89, 0x3feac0c44f0d029a,
   0x3feefb2b2ebf2105, 0xbfef2a3e062af2da, 0xbfebae995e9cb2f7, 0xbfe5bdb9228de194,
   0xbfdbbcc009016ad8, 0xbfc30e507891e272, 0x3fc30e507891e272, 0x3fdbbcc009016ad8,
   0x3fe5bdb9228de194, 0x3febae995e9cb2f7, 0x3fef2a3e062af2da]

/-- The 55 weight encodings of the ten stored rules, in the same triangular order as
`nodeBits`. -/
def weightBits : List Nat :=
  [0x4000000000000000, 0x3ff0000000000000, 0x3ff0000000000000, 0x3fe1c71c71c71c76,
   0x3fec71c71c71c71d, 0x3fe1c71c71c71c76, 0x3fd64340f7e7b66b, 0x3fe4de5f840c24cb,
   0x3fe4de5f840c24cb, 0x3fd64340f7e7b66b, 0x3fce539ec36e0389, 0x3fdea1da25ae4153,
   0x3fe23456789abce0, 0x3fdea1da25ae4153, 0x3fce539ec36e0389, 0x3fc5edf601e2dbeb,
   0x3fd716b7b5794c23, 0x3fddf24d499545e7, 0x3fddf24d499545e7, 0x3fd716b7b5794c23,
   0x3fc5edf601e2dbeb, 0x3fc092f69f826d62, 0x3fd1e6b1713d864a, 0x3fd86fe74ee32b3e,
   0x3fdabfd7e03c2f9f, 0x3fd86fe74ee32b3e, 0x3fd1e6b1713d864a, 0x3fc092f69f826d62,
   0x3fb9ea1d04ca0361, 0x3fcc76fb531d2b85, 0x3fd413c50a255610, 0x3fd736360b199343,
   0x3fd736360b199343, 0x3fd413c50a255610, 0x3fcc76fb531d2b85, 0x3fb9ea1d04ca0361,
   0x3fb4ce65f803eeda, 0x3fc71f7a9b222bdc, 0x3fd0add87c8274fe, 0x3fd3fd7e9838d514,
   0x3fd522a43f65486e, 0x3fd3fd7e9838d514, 0x3fd0add87c8274fe, 0x3fc71f7a9b222bdc,
   0x3fb4ce65f803eeda, 0x3fb1115f8b62dc15, 0x3fc32138c878eff4, 0x3fcc0b059d00bc30,
   0x3fd13baa7a559bf8, 0x3fd2e9de7014d6f1, 0x3fd2e9de7014d6f1, 0x3fd13baa7a559bf8,
   0x3fcc0b059d00bc30, 0x3fc32138c878eff4, 0x3fb1115f8b62dc15]

end Quadrature.Binary64.ClightTableData
