import Mathlib.Data.Option.Basic

/-!
# Finite execution with traces, and the vocabulary of the compiler directories

`run next fuel s` applies the step function `next` exactly `fuel` times from `s` and
concatenates the event lists of the steps. The lemmas apply to any state and event
types. Each stage's `executeSteps` specializes this runner to its own `executeStep`.

`run_sound` lifts soundness of one step through any relation that is reflexive and
closed under prepending a step. `run_prefix` shows that every semantic execution from
the start of a checked terminating run is a prefix of it. `run_not_infinite` uses
agreement of the checker with every permitted step to exclude an infinite execution
from a state whose checked run reaches a terminal state.

## Vocabulary for the seven language directories in `Compiler/`

Checker, executor. `executeStep external ge s` runs one transition of the stage's
semantics from the state `s`. It returns `some (t, s')`, the emitted trace and the
successor, or `none` when it cannot decide the transition. A `none` result means
"unchecked", for example an external function that `external` cannot run. It does not
mean that no transition exists.

Trace, observation. A trace is the list of events emitted by a run. The observation
of a run is its event trace together with its exit status.

Annotation. `EF_annot "quadrature-result"` is CompCert's annotation builtin. It is the
only external call the ten programs make. `Cminor/Annotations.lean` executes it in
Lean as `annotatedExternalCall`, emitting one `Event_annot` carrying the numeric
arguments.

External-call relation. `externalCall ef ge args m t v m'` is CLean's version of
CompCert's `external_call` (`vendor/clean/CCLib/Events.lean`). It is the semantics of
every external function and builtin. Unknown functions are parameters, supplied
through the `ExternalCalls` class.

Sound versus Agrees. `ExternalExecutorSound external ge` says every `some` result of
`external` is permitted by `externalCall`. `ExternalExecutorAgrees external ge` says a
successful result of `external` is the only result `externalCall` permits, trace
included. Both live in `Execution/ExternalCalls.lean`.

Maximal execution. A finite `Steps` run whose final state admits no further `Step`.

Total correctness. Every execution of the program terminates, and every terminating
execution has the same observation.

Return-address relation and predictor. Mach's `Step` takes a parameter
`returnAddress : Function → Code → Ptrofs → Prop`, CompCert's `return_address_offset`
oracle for the assembly offset just after a call. Two instances are used: table
membership `Mach.ImportedAddresses.relation` (`Mach/ImportedReturnAddresses.lean`) and
the Lean Asmgen translation `Asm.Generation.returnAddress`. They are related in
`Asm/GeneratedReturnAddresses.lean`. A predictor is the executable function that
computes the offset, proved sound for its relation.

`stepCount n`. The exact number of checker steps of the n-node program at that stage.

Total-correctness theorem names. In each `StoredTotalCorrectness.lean`: `progress`
(every reachable state is final with exit status 0 or can step), `maximal_execution`
(every maximal execution emits the certified trace and exits 0), `not_infinite` (no
infinite execution starts at an initial state), `final_accuracy` (every terminating
execution emits a finite binary64 value within the integral-error bound). In each
`StoredPrograms.lean`: `execution_checked` (the checker's run on the n-node program,
by kernel evaluation).

## Scope

Every theorem in the seven language directories and in `Compiler/Correspondence/` is about the ten
programs `Imported.program n`, n = 1..10 nodes, generated by `scripts/import-*.py`
from CompCert's output for the internal-cosine quadrature application, in Lean
semantics adapted from CompCert's Rocq definitions. No theorem is about CompCert's
compiler or its proofs, and no Lean/Rocq correspondence is proved. Adjacent stages
are related program by program in `Compiler/Correspondence/`.
-/

namespace Quadrature.Execution

universe u v

variable {State : Type u} {Event : Type v}

/-- `run next fuel s` applies `next` exactly `fuel` times from `s`, concatenating the events. -/
def run (next : State → Option (List Event × State)) : Nat → State →
    Option (List Event × State)
  | 0, state => some ([], state)
  | fuel + 1, state => do
      let (first, middle) ← next state
      let (rest, finish) ← run next fuel middle
      pure (first ++ rest, finish)

/-- If every `some` result of `next` is a `Step`, a successful `run` is a `Steps` run, for any
`Steps` that is reflexive and closed under prepending a `Step`. -/
theorem run_sound {next : State → Option (List Event × State)}
    {Step Steps : State → List Event → State → Prop}
    (hstep : ∀ {start finish trace}, next start = some (trace, finish) →
      Step start trace finish)
    (hrefl : ∀ state, Steps state [] state)
    (hcons : ∀ {start middle finish first rest},
      Step start first middle → Steps middle rest finish → Steps start (first ++ rest) finish)
    {fuel : Nat} {start finish : State} {trace : List Event}
    (h : run next fuel start = some (trace, finish)) : Steps start trace finish := by
  induction fuel generalizing start trace with
  | zero =>
      cases h
      exact hrefl _
  | succ fuel ih =>
      simp only [run, bind, Option.bind_eq_some_iff] at h
      obtain ⟨⟨first, middle⟩, hfirst, ⟨rest, last⟩, hrest, h⟩ := h
      cases h
      exact hcons (hstep hfirst) (ih hrest)

/-- Every semantic execution from the start of a checked terminating run has a checked suffix.
The relation `Steps` need only admit the usual cases: an empty execution or a first step
followed by a suffix. -/
theorem run_prefix {next : State → Option (List Event × State)}
    {Step Steps : State → List Event → State → Prop}
    (hagrees : ∀ {start finish other trace otherTrace},
      next start = some (trace, finish) → Step start otherTrace other →
        trace = otherTrace ∧ finish = other)
    (hcases : ∀ {start finish trace}, Steps start trace finish →
      (trace = [] ∧ start = finish) ∨
        ∃ middle first rest, Step start first middle ∧ Steps middle rest finish ∧
          trace = first ++ rest)
    {fuel : Nat} {start finish state : State} {total trace : List Event}
    (hcheck : run next fuel start = some (total, finish))
    (hstop : ∀ emitted state, ¬ Step finish emitted state)
    (hprefix : Steps start trace state) :
    ∃ remainingFuel remaining, remainingFuel ≤ fuel ∧ trace ++ remaining = total ∧
      run next remainingFuel state = some (remaining, finish) := by
  induction fuel generalizing start total trace state with
  | zero =>
      simp only [run, Option.some.injEq, Prod.mk.injEq] at hcheck
      obtain ⟨rfl, rfl⟩ := hcheck
      rcases hcases hprefix with ⟨rfl, rfl⟩ | ⟨_, _, _, hstep, _, _⟩
      · exact ⟨0, [], Nat.le_refl _, rfl, rfl⟩
      · exact False.elim (hstop _ _ hstep)
  | succ fuel ih =>
      rcases hcases hprefix with ⟨rfl, rfl⟩ | ⟨middle, first, rest, hstep, hsuffix, rfl⟩
      · exact ⟨fuel + 1, total, Nat.le_refl _, rfl, hcheck⟩
      · simp only [run, bind, Option.bind_eq_some_iff] at hcheck
        obtain ⟨⟨checkedFirst, checkedMiddle⟩, hfirst, ⟨checkedRest, last⟩, hrest, h⟩ := hcheck
        cases h
        obtain ⟨rfl, rfl⟩ := hagrees hfirst hstep
        obtain ⟨remainingFuel, remaining, hle, htrace, hfinish⟩ := ih hrest hsuffix
        refine ⟨remainingFuel, remaining, Nat.le_trans hle (Nat.le_succ _), ?_, hfinish⟩
        simp only [List.append_assoc, htrace]

/-- If `next` agrees with every `Step` and a checked run from `start` reaches a stuck state, no
infinite sequence of `Step` transitions starts at `start`. -/
theorem run_not_infinite {next : State → Option (List Event × State)}
    {Step : State → List Event → State → Prop}
    (hagrees : ∀ {start finish other trace otherTrace},
      next start = some (trace, finish) → Step start otherTrace other → finish = other)
    {fuel : Nat} {start finish : State} {trace : List Event}
    (hcheck : run next fuel start = some (trace, finish))
    (hstop : ∀ emitted state, ¬ Step finish emitted state)
    (states : Nat → State) (traces : Nat → List Event) (hstart : states 0 = start)
    (hsteps : ∀ n, Step (states n) (traces n) (states (n + 1))) : False := by
  induction fuel generalizing start trace states traces with
  | zero =>
      simp only [run, Option.some.injEq, Prod.mk.injEq] at hcheck
      obtain ⟨rfl, rfl⟩ := hcheck
      exact hstop _ _ (hstart ▸ hsteps 0)
  | succ fuel ih =>
      simp only [run, bind, Option.bind_eq_some_iff] at hcheck
      obtain ⟨⟨first, middle⟩, hfirst, ⟨rest, last⟩, hrest, h⟩ := hcheck
      cases h
      have hnext := hagrees hfirst (hstart ▸ hsteps 0)
      exact ih hrest (fun n => states (n + 1)) (fun n => traces (n + 1))
        hnext.symm (fun n => hsteps (n + 1))

end Quadrature.Execution
