import Quadrature.Clight.StoredAccuracy
import Quadrature.Compiler.Linear.Imported
import Quadrature.Compiler.Linear.ProgramExecution

/-!
# Executions of the ten imported Linear programs

Certified executions of the ten programs `Imported.program n` (n = 1..10 nodes),
generated by `scripts/import-linear.py` from CompCert's Linear output for the
internal-cosine quadrature application. Read `execution_checked` first: kernel
evaluation of `executeProgram` on each program initializes all 73 globals, runs the
accessors, integrator, polynomial and caller, emits one binary64 annotation, and
exits 0. `execution_accuracy` adds the integral-error bound of
`Clight.StoredPolynomial` to the emitted value.

Vocabulary and scope: `Quadrature.Compiler.Execution.Run`.
-/

namespace Quadrature.Linear.StoredPrograms

open CC Quadrature.Binary64
open FloatLib.Floats.Formats.BinaryInterchange

/-- The trace of one `quadrature-result` annotation carrying the binary64 `value`. -/
def resultTrace (value : Value) : Trace :=
  [.Event_annot "quadrature-result" [.EVfloat value]]

/-- These Linear applications take 146 transitions per node and 29 fixed transitions. -/
def stepCount (n : Nat) : Nat := 146 * n + 29

-- Kernel evaluation of `executeProgram` on each of the ten programs for `stepCount n` steps.
set_option maxRecDepth 100000 in
set_option maxHeartbeats 16000000 in
/-- Kernel evaluation checks the initialized program, including every table load and call. -/
theorem execution_checked (n : Nat) (hlo : 1 ≤ n) (hhi : n ≤ 10) :
    executeProgram annotatedExternalCall (Imported.program n) (stepCount n) =
      some (resultTrace (Model.ofNatBits (Clight.StoredPolynomial.resultBits n)),
        Integers.Int.zero) := by
  interval_cases n <;> decide +kernel

/-- A complete semantic execution exists from the program's own initialized memory. -/
theorem execution [ExternalCalls] (n : Nat) (hlo : 1 ≤ n) (hhi : n ≤ 10) :
    ∃ start finish, InitialState (Imported.program n) start ∧
      Steps (Imported.program n).globalenv start
        (resultTrace (Clight.StoredPolynomial.result n)) finish ∧
      FinalState finish Integers.Int.zero := by
  rw [Clight.StoredPolynomial.result_value n hlo hhi]
  exact execute_program_sound annotated_external_executor_sound (execution_checked n hlo hhi)

/-- The value emitted by this execution satisfies the fixed-integrand accuracy bound. -/
theorem execution_accuracy [ExternalCalls] (n : Nat) (hlo : 1 ≤ n) (hhi : n ≤ 10) :
    ∃ value : Value, ∃ start finish,
      InitialState (Imported.program n) start ∧
      Steps (Imported.program n).globalenv start (resultTrace value) finish ∧
      FinalState finish Integers.Int.zero ∧
      Model.isFinite value = true ∧
      |Model.toReal value - ∫ x in (-1 : ℝ)..1, Example.integrand x| ≤
        Clight.StoredPolynomial.errorBound n := by
  obtain ⟨start, finish, hinit, hrun, hfinal⟩ := execution n hlo hhi
  exact ⟨Clight.StoredPolynomial.result n, start, finish, hinit, hrun, hfinal,
    Clight.StoredPolynomial.integral_accuracy n hlo hhi⟩

end Quadrature.Linear.StoredPrograms
